// Package treemap provides sorted maps backed by a red-black tree, specialised
// for each supported key/value primitive pair (keys and values both range over
// Int8…Int64, Char, Float32, Float64). Go has no method-level generics, so the
// per-pair sources are machine-generated rather than hand-maintained. The value
// type is a carried payload only — it never participates in comparison. For
// float keys, insertion and in-order traversal use the IEEE 754 total order
// (see cmp_float.go) rather than the default partial <, so NaN and signed
// zeroes sort deterministically; the Floor/Ceiling exact-match checks and the
// RangeKeys/HeadMap/TailMap bound checks use raw == / < / >= (matching the
// hand-written originals), so their NaN / signed-zero edge behaviour follows
// IEEE comparison, not the total order.
//
// Production sources are regenerated by the in-repo code generator. Run:
//
//	go generate ./treemap/...
//
// Test files are hand-maintained. The NavigableMap Range surface
// (SubMapRange/RangeKeysIn/RemoveRange/... consuming rangev.Int32Range) is
// int32-only in v1, so it lives in the hand-maintained
// int32_int32_navigable_range.go rather than the uniform generated sources;
// the generator does not touch that file.
package treemap

//go:generate go run ../internal/codegen treemap
