// Code generated by internal/codegen; DO NOT EDIT.

package treemap

import (
	"fmt"
	"iter"
	"strings"
)

const (
	int16Int32TreeNodeRed   = false
	int16Int32TreeNodeBlack = true
)

type int16Int32TreeNode struct {
	key    int16
	value  int32
	left   *int16Int32TreeNode
	right  *int16Int32TreeNode
	parent *int16Int32TreeNode
	color  bool
}

// Int16Int32 is a sorted map with int16 keys and int32 values, backed by a red-black tree.
// Keys are maintained in ascending order.
type Int16Int32 struct {
	root *int16Int32TreeNode
	size int
}

// NewInt16Int32 creates a new empty sorted map.
func NewInt16Int32() *Int16Int32 {
	return &Int16Int32{}
}

// Put inserts or updates a key-value pair. Returns the previous value and true if the key existed.
func (m *Int16Int32) Put(key int16, value int32) (int32, bool) {
	if m.root == nil {
		m.root = &int16Int32TreeNode{key: key, value: value, color: int16Int32TreeNodeBlack}
		m.size++
		return 0, false
	}
	node := m.root
	for {
		if key < node.key {
			if node.left == nil {
				node.left = &int16Int32TreeNode{key: key, value: value, parent: node, color: int16Int32TreeNodeRed}
				m.fixAfterInsert(node.left)
				m.size++
				return 0, false
			}
			node = node.left
		} else if key > node.key {
			if node.right == nil {
				node.right = &int16Int32TreeNode{key: key, value: value, parent: node, color: int16Int32TreeNodeRed}
				m.fixAfterInsert(node.right)
				m.size++
				return 0, false
			}
			node = node.right
		} else {
			old := node.value
			node.value = value
			return old, true
		}
	}
}

// Get returns the value for the key, or the zero value and false if not found.
func (m *Int16Int32) Get(key int16) (int32, bool) {
	node := m.findNode(key)
	if node == nil {
		return 0, false
	}
	return node.value, true
}

// GetOrDefault returns the value for the key if present, or the default value otherwise.
func (m *Int16Int32) GetOrDefault(key int16, defaultValue int32) int32 {
	if v, ok := m.Get(key); ok {
		return v
	}
	return defaultValue
}

// ContainsKey returns true if the map contains the given key.
func (m *Int16Int32) ContainsKey(key int16) bool {
	return m.findNode(key) != nil
}

// Remove removes the entry for the given key. Returns the previous value and true if found.
func (m *Int16Int32) Remove(key int16) (int32, bool) {
	node := m.findNode(key)
	if node == nil {
		return 0, false
	}
	old := node.value
	m.deleteNode(node)
	m.size--
	return old, true
}

// Len returns the number of elements. Use m.Len() == 0 to test for emptiness.
func (m *Int16Int32) Len() int {
	return m.size
}

// Clear removes all entries.
func (m *Int16Int32) Clear() {
	m.root = nil
	m.size = 0
}

// Min returns the smallest key and its value, or zero values and false if empty.
func (m *Int16Int32) Min() (int16, int32, bool) {
	if m.root == nil {
		return 0, 0, false
	}
	node := m.minNode(m.root)
	return node.key, node.value, true
}

// Max returns the largest key and its value, or zero values and false if empty.
func (m *Int16Int32) Max() (int16, int32, bool) {
	if m.root == nil {
		return 0, 0, false
	}
	node := m.maxNode(m.root)
	return node.key, node.value, true
}

// Floor returns the largest key <= the given key, or zero values and false.
func (m *Int16Int32) Floor(key int16) (int16, int32, bool) {
	var result *int16Int32TreeNode
	node := m.root
	for node != nil {
		if key == node.key {
			return node.key, node.value, true
		}
		if key > node.key {
			result = node
			node = node.right
		} else {
			node = node.left
		}
	}
	if result == nil {
		return 0, 0, false
	}
	return result.key, result.value, true
}

// Ceiling returns the smallest key >= the given key, or zero values and false.
func (m *Int16Int32) Ceiling(key int16) (int16, int32, bool) {
	var result *int16Int32TreeNode
	node := m.root
	for node != nil {
		if key == node.key {
			return node.key, node.value, true
		}
		if key < node.key {
			result = node
			node = node.left
		} else {
			node = node.right
		}
	}
	if result == nil {
		return 0, 0, false
	}
	return result.key, result.value, true
}

// All returns an iter.Seq2 that yields all key-value pairs in ascending key order.
func (m *Int16Int32) All() iter.Seq2[int16, int32] {
	return func(yield func(int16, int32) bool) {
		var inorder func(node *int16Int32TreeNode) bool
		inorder = func(node *int16Int32TreeNode) bool {
			if node == nil {
				return true
			}
			if !inorder(node.left) {
				return false
			}
			if !yield(node.key, node.value) {
				return false
			}
			return inorder(node.right)
		}
		inorder(m.root)
	}
}

// Keys returns an iter.Seq that yields all keys in ascending order.
func (m *Int16Int32) Keys() iter.Seq[int16] {
	return func(yield func(int16) bool) {
		for k, _ := range m.All() {
			if !yield(k) {
				return
			}
		}
	}
}

// Values returns an iter.Seq that yields all values in key order.
func (m *Int16Int32) Values() iter.Seq[int32] {
	return func(yield func(int32) bool) {
		for _, v := range m.All() {
			if !yield(v) {
				return
			}
		}
	}
}

// RangeKeys returns an iter.Seq2 that yields entries with keys in [fromKey, toKey).
func (m *Int16Int32) RangeKeys(fromKey, toKey int16) iter.Seq2[int16, int32] {
	return func(yield func(int16, int32) bool) {
		for k, v := range m.All() {
			if k < fromKey {
				continue
			}
			if k >= toKey {
				return
			}
			if !yield(k, v) {
				return
			}
		}
	}
}

// Higher returns the smallest key strictly greater than `key` (and its value),
// or zero values and false. Unlike Ceiling, never returns `key` itself.
func (m *Int16Int32) Higher(key int16) (int16, int32, bool) {
	var result *int16Int32TreeNode
	node := m.root
	for node != nil {
		if key < node.key {
			result = node
			node = node.left
		} else {
			node = node.right
		}
	}
	if result == nil {
		return 0, 0, false
	}
	return result.key, result.value, true
}

// Lower returns the largest key strictly less than `key` (and its value),
// or zero values and false. Unlike Floor, never returns `key` itself.
func (m *Int16Int32) Lower(key int16) (int16, int32, bool) {
	var result *int16Int32TreeNode
	node := m.root
	for node != nil {
		if key > node.key {
			result = node
			node = node.right
		} else {
			node = node.left
		}
	}
	if result == nil {
		return 0, 0, false
	}
	return result.key, result.value, true
}

// HeadMap returns an iter.Seq2 over entries with keys strictly less than toKey.
// Matches Java NavigableMap.headMap(toKey) (exclusive by default).
func (m *Int16Int32) HeadMap(toKey int16) iter.Seq2[int16, int32] {
	return func(yield func(int16, int32) bool) {
		for k, v := range m.All() {
			if k >= toKey {
				return
			}
			if !yield(k, v) {
				return
			}
		}
	}
}

// TailMap returns an iter.Seq2 over entries with keys >= fromKey.
// Matches Java NavigableMap.tailMap(fromKey) (inclusive by default).
func (m *Int16Int32) TailMap(fromKey int16) iter.Seq2[int16, int32] {
	return func(yield func(int16, int32) bool) {
		for k, v := range m.All() {
			if k < fromKey {
				continue
			}
			if !yield(k, v) {
				return
			}
		}
	}
}

// SubMap returns an iter.Seq2 over entries with keys in [fromKey, toKey).
// Alias for RangeKeys; exists for Java-NavigableMap API parity.
func (m *Int16Int32) SubMap(fromKey, toKey int16) iter.Seq2[int16, int32] {
	return m.RangeKeys(fromKey, toKey)
}

// FirstEntry is an alias of Min — the smallest key and its value, or zero/false.
func (m *Int16Int32) FirstEntry() (int16, int32, bool) { return m.Min() }

// LastEntry is an alias of Max — the largest key and its value, or zero/false.
func (m *Int16Int32) LastEntry() (int16, int32, bool) { return m.Max() }

// FloorKey returns the largest key <= the given key, or zero and false. Key form
// of Floor (drops the value).
func (m *Int16Int32) FloorKey(key int16) (int16, bool) {
	k, _, ok := m.Floor(key)
	return k, ok
}

// CeilingKey returns the smallest key >= the given key, or zero and false.
func (m *Int16Int32) CeilingKey(key int16) (int16, bool) {
	k, _, ok := m.Ceiling(key)
	return k, ok
}

// LowerKey returns the largest key strictly < the given key, or zero and false.
func (m *Int16Int32) LowerKey(key int16) (int16, bool) {
	k, _, ok := m.Lower(key)
	return k, ok
}

// HigherKey returns the smallest key strictly > the given key, or zero and false.
func (m *Int16Int32) HigherKey(key int16) (int16, bool) {
	k, _, ok := m.Higher(key)
	return k, ok
}

// FirstKey returns the smallest key, or zero and false if empty.
func (m *Int16Int32) FirstKey() (int16, bool) {
	k, _, ok := m.Min()
	return k, ok
}

// LastKey returns the largest key, or zero and false if empty.
func (m *Int16Int32) LastKey() (int16, bool) {
	k, _, ok := m.Max()
	return k, ok
}

// FloorEntry is an alias of Floor — the largest entry with key <= the given key.
func (m *Int16Int32) FloorEntry(key int16) (int16, int32, bool) {
	return m.Floor(key)
}

// CeilingEntry is an alias of Ceiling — the smallest entry with key >= the given key.
func (m *Int16Int32) CeilingEntry(key int16) (int16, int32, bool) {
	return m.Ceiling(key)
}

// LowerEntry is an alias of Lower — the largest entry with key strictly < the given key.
func (m *Int16Int32) LowerEntry(key int16) (int16, int32, bool) {
	return m.Lower(key)
}

// HigherEntry is an alias of Higher — the smallest entry with key strictly > the given key.
func (m *Int16Int32) HigherEntry(key int16) (int16, int32, bool) {
	return m.Higher(key)
}

// PollFirstEntry removes and returns the smallest entry, or zero/false if empty.
func (m *Int16Int32) PollFirstEntry() (int16, int32, bool) {
	k, v, ok := m.Min()
	if !ok {
		return 0, 0, false
	}
	m.Remove(k)
	return k, v, true
}

// PollLastEntry removes and returns the largest entry, or zero/false if empty.
func (m *Int16Int32) PollLastEntry() (int16, int32, bool) {
	k, v, ok := m.Max()
	if !ok {
		return 0, 0, false
	}
	m.Remove(k)
	return k, v, true
}

// DescendingMap returns an iter.Seq2 over entries in descending key order.
func (m *Int16Int32) DescendingMap() iter.Seq2[int16, int32] {
	return func(yield func(int16, int32) bool) {
		var reverse func(node *int16Int32TreeNode) bool
		reverse = func(node *int16Int32TreeNode) bool {
			if node == nil {
				return true
			}
			if !reverse(node.right) {
				return false
			}
			if !yield(node.key, node.value) {
				return false
			}
			return reverse(node.left)
		}
		reverse(m.root)
	}
}

// DescendingKeys returns an iter.Seq over keys in descending order.
func (m *Int16Int32) DescendingKeys() iter.Seq[int16] {
	return func(yield func(int16) bool) {
		for k := range m.DescendingMap() {
			if !yield(k) {
				return
			}
		}
	}
}

// ForEach calls the function for each key-value pair in ascending order.
func (m *Int16Int32) ForEach(f func(int16, int32)) {
	for k, v := range m.All() {
		f(k, v)
	}
}

// Select returns a new map with entries satisfying the predicate.
func (m *Int16Int32) Select(predicate func(int16, int32) bool) *Int16Int32 {
	result := NewInt16Int32()
	for k, v := range m.All() {
		if predicate(k, v) {
			result.Put(k, v)
		}
	}
	return result
}

// Reject returns a new map with entries NOT satisfying the predicate.
func (m *Int16Int32) Reject(predicate func(int16, int32) bool) *Int16Int32 {
	result := NewInt16Int32()
	for k, v := range m.All() {
		if !predicate(k, v) {
			result.Put(k, v)
		}
	}
	return result
}

// Detect returns the first entry satisfying the predicate (in key order), or (zero, zero, false).
func (m *Int16Int32) Detect(predicate func(int16, int32) bool) (int16, int32, bool) {
	for k, v := range m.All() {
		if predicate(k, v) {
			return k, v, true
		}
	}
	var zk int16
	var zv int32
	return zk, zv, false
}

// AnySatisfy returns true if any entry satisfies the predicate.
func (m *Int16Int32) AnySatisfy(predicate func(int16, int32) bool) bool {
	for k, v := range m.All() {
		if predicate(k, v) {
			return true
		}
	}
	return false
}

// AllSatisfy returns true if all entries satisfy the predicate.
func (m *Int16Int32) AllSatisfy(predicate func(int16, int32) bool) bool {
	for k, v := range m.All() {
		if !predicate(k, v) {
			return false
		}
	}
	return true
}

// NoneSatisfy returns true if no entry satisfies the predicate.
func (m *Int16Int32) NoneSatisfy(predicate func(int16, int32) bool) bool {
	for k, v := range m.All() {
		if predicate(k, v) {
			return false
		}
	}
	return true
}

// Count returns the number of entries satisfying the predicate.
func (m *Int16Int32) Count(predicate func(int16, int32) bool) int {
	c := 0
	for k, v := range m.All() {
		if predicate(k, v) {
			c++
		}
	}
	return c
}

// String returns a string representation with entries in sorted key order.
func (m *Int16Int32) String() string {
	if m.size == 0 {
		return "{}"
	}
	var sb strings.Builder
	sb.WriteString("{")
	first := true
	for k, v := range m.All() {
		if !first {
			sb.WriteString(", ")
		}
		fmt.Fprintf(&sb, "%v: %v", k, v)
		first = false
	}
	sb.WriteString("}")
	return sb.String()
}

// --- Red-black tree internals ---

func (m *Int16Int32) findNode(key int16) *int16Int32TreeNode {
	node := m.root
	for node != nil {
		if key < node.key {
			node = node.left
		} else if key > node.key {
			node = node.right
		} else {
			return node
		}
	}
	return nil
}

func (m *Int16Int32) minNode(node *int16Int32TreeNode) *int16Int32TreeNode {
	for node.left != nil {
		node = node.left
	}
	return node
}

func (m *Int16Int32) maxNode(node *int16Int32TreeNode) *int16Int32TreeNode {
	for node.right != nil {
		node = node.right
	}
	return node
}

func (m *Int16Int32) rotateLeft(x *int16Int32TreeNode) {
	y := x.right
	x.right = y.left
	if y.left != nil {
		y.left.parent = x
	}
	y.parent = x.parent
	if x.parent == nil {
		m.root = y
	} else if x == x.parent.left {
		x.parent.left = y
	} else {
		x.parent.right = y
	}
	y.left = x
	x.parent = y
}

func (m *Int16Int32) rotateRight(x *int16Int32TreeNode) {
	y := x.left
	x.left = y.right
	if y.right != nil {
		y.right.parent = x
	}
	y.parent = x.parent
	if x.parent == nil {
		m.root = y
	} else if x == x.parent.right {
		x.parent.right = y
	} else {
		x.parent.left = y
	}
	y.right = x
	x.parent = y
}

func (m *Int16Int32) fixAfterInsert(z *int16Int32TreeNode) {
	for z.parent != nil && z.parent.color == int16Int32TreeNodeRed {
		if z.parent == z.parent.parent.left {
			y := z.parent.parent.right
			if y != nil && y.color == int16Int32TreeNodeRed {
				z.parent.color = int16Int32TreeNodeBlack
				y.color = int16Int32TreeNodeBlack
				z.parent.parent.color = int16Int32TreeNodeRed
				z = z.parent.parent
			} else {
				if z == z.parent.right {
					z = z.parent
					m.rotateLeft(z)
				}
				z.parent.color = int16Int32TreeNodeBlack
				z.parent.parent.color = int16Int32TreeNodeRed
				m.rotateRight(z.parent.parent)
			}
		} else {
			y := z.parent.parent.left
			if y != nil && y.color == int16Int32TreeNodeRed {
				z.parent.color = int16Int32TreeNodeBlack
				y.color = int16Int32TreeNodeBlack
				z.parent.parent.color = int16Int32TreeNodeRed
				z = z.parent.parent
			} else {
				if z == z.parent.left {
					z = z.parent
					m.rotateRight(z)
				}
				z.parent.color = int16Int32TreeNodeBlack
				z.parent.parent.color = int16Int32TreeNodeRed
				m.rotateLeft(z.parent.parent)
			}
		}
	}
	m.root.color = int16Int32TreeNodeBlack
}

func (m *Int16Int32) deleteNode(z *int16Int32TreeNode) {
	if z.left != nil && z.right != nil {
		succ := m.minNode(z.right)
		z.key = succ.key
		z.value = succ.value
		z = succ
	}
	var child *int16Int32TreeNode
	if z.left != nil {
		child = z.left
	} else {
		child = z.right
	}
	if child != nil {
		child.parent = z.parent
		if z.parent == nil {
			m.root = child
		} else if z == z.parent.left {
			z.parent.left = child
		} else {
			z.parent.right = child
		}
		if z.color == int16Int32TreeNodeBlack {
			m.fixAfterDelete(child)
		}
	} else if z.parent == nil {
		m.root = nil
	} else {
		if z.color == int16Int32TreeNodeBlack {
			m.fixAfterDelete(z)
		}
		if z.parent != nil {
			if z == z.parent.left {
				z.parent.left = nil
			} else {
				z.parent.right = nil
			}
		}
	}
}

func (m *Int16Int32) fixAfterDelete(x *int16Int32TreeNode) {
	for x != m.root && x.color == int16Int32TreeNodeBlack {
		if x == x.parent.left {
			w := x.parent.right
			if w == nil {
				x = x.parent
				continue
			}
			if w.color == int16Int32TreeNodeRed {
				w.color = int16Int32TreeNodeBlack
				x.parent.color = int16Int32TreeNodeRed
				m.rotateLeft(x.parent)
				w = x.parent.right
			}
			if w == nil {
				x = x.parent
				continue
			}
			leftBlack := w.left == nil || w.left.color == int16Int32TreeNodeBlack
			rightBlack := w.right == nil || w.right.color == int16Int32TreeNodeBlack
			if leftBlack && rightBlack {
				w.color = int16Int32TreeNodeRed
				x = x.parent
			} else {
				if rightBlack {
					if w.left != nil {
						w.left.color = int16Int32TreeNodeBlack
					}
					w.color = int16Int32TreeNodeRed
					m.rotateRight(w)
					w = x.parent.right
				}
				w.color = x.parent.color
				x.parent.color = int16Int32TreeNodeBlack
				if w.right != nil {
					w.right.color = int16Int32TreeNodeBlack
				}
				m.rotateLeft(x.parent)
				x = m.root
			}
		} else {
			w := x.parent.left
			if w == nil {
				x = x.parent
				continue
			}
			if w.color == int16Int32TreeNodeRed {
				w.color = int16Int32TreeNodeBlack
				x.parent.color = int16Int32TreeNodeRed
				m.rotateRight(x.parent)
				w = x.parent.left
			}
			if w == nil {
				x = x.parent
				continue
			}
			leftBlack := w.left == nil || w.left.color == int16Int32TreeNodeBlack
			rightBlack := w.right == nil || w.right.color == int16Int32TreeNodeBlack
			if leftBlack && rightBlack {
				w.color = int16Int32TreeNodeRed
				x = x.parent
			} else {
				if leftBlack {
					if w.right != nil {
						w.right.color = int16Int32TreeNodeBlack
					}
					w.color = int16Int32TreeNodeRed
					m.rotateLeft(w)
					w = x.parent.left
				}
				w.color = x.parent.color
				x.parent.color = int16Int32TreeNodeBlack
				if w.left != nil {
					w.left.color = int16Int32TreeNodeBlack
				}
				m.rotateRight(x.parent)
				x = m.root
			}
		}
	}
	x.color = int16Int32TreeNodeBlack
}
