// Code generated by mapdb-codegen. DO NOT EDIT.

package treemap

import "testing"

func TestInt8Int64TreeMap_Generated_PutGet(t *testing.T) {
	m := NewInt8Int64TreeMap()
	m.Put(3, 3)
	m.Put(1, 1)
	m.Put(2, 2)
	if m.Size() != 3 {
		t.Errorf("Size = %d", m.Size())
	}
	if v, ok := m.Get(2); !ok || v != 2 {
		t.Errorf("Get = (%v,%v)", v, ok)
	}
	if _, ok := m.Get(99); ok {
		t.Error("Get missing should be false")
	}
}
func TestInt8Int64TreeMap_Generated_Remove(t *testing.T) {
	m := NewInt8Int64TreeMap()
	m.Put(1, 1)
	m.Put(2, 2)
	old, ok := m.Remove(1)
	if !ok || old != 1 {
		t.Errorf("Remove = (%v,%v)", old, ok)
	}
	if m.Size() != 1 {
		t.Errorf("Size = %d", m.Size())
	}
}
func TestInt8Int64TreeMap_Generated_ContainsKey(t *testing.T) {
	m := NewInt8Int64TreeMap()
	m.Put(1, 1)
	if !m.ContainsKey(1) {
		t.Error("Should contain")
	}
	if m.ContainsKey(99) {
		t.Error("Should not contain")
	}
}
func TestInt8Int64TreeMap_Generated_MinMax(t *testing.T) {
	m := NewInt8Int64TreeMap()
	m.Put(3, 3)
	m.Put(1, 1)
	m.Put(2, 2)
	if k, _, ok := m.Min(); !ok || k != 1 {
		t.Errorf("Min key = %v", k)
	}
	if k, _, ok := m.Max(); !ok || k != 3 {
		t.Errorf("Max key = %v", k)
	}
}
func TestInt8Int64TreeMap_Generated_FloorCeiling(t *testing.T) {
	m := NewInt8Int64TreeMap()
	m.Put(1, 1)
	m.Put(3, 3)
	if k, _, ok := m.Floor(2); !ok || k != 1 {
		t.Errorf("Floor = %v", k)
	}
	if k, _, ok := m.Ceiling(2); !ok || k != 3 {
		t.Errorf("Ceiling = %v", k)
	}
}
func TestInt8Int64TreeMap_Generated_Clear(t *testing.T) {
	m := NewInt8Int64TreeMap()
	m.Put(1, 1)
	m.Clear()
	if !m.IsEmpty() {
		t.Error("Should be empty")
	}
}
func TestInt8Int64TreeMap_Generated_All(t *testing.T) {
	m := NewInt8Int64TreeMap()
	m.Put(1, 1)
	m.Put(2, 2)
	count := 0
	for range m.All() {
		count++
	}
	if count != 2 {
		t.Errorf("All count = %d", count)
	}
}
func TestInt8Int64TreeMap_Generated_SortedOrder(t *testing.T) {
	m := NewInt8Int64TreeMap()
	m.Put(3, 3)
	m.Put(1, 1)
	m.Put(2, 2)
	var keys []int8
	for k := range m.Keys() {
		keys = append(keys, k)
	}
	for i := 1; i < len(keys); i++ {
		if keys[i] < keys[i-1] {
			t.Errorf("Keys not sorted at %d: %v", i, keys)
		}
	}
}
func TestInt8Int64TreeMap_Generated_Select(t *testing.T) {
	m := NewInt8Int64TreeMap()
	m.Put(1, 1)
	m.Put(2, 2)
	m.Put(3, 3)
	sel := m.Select(func(k int8, v int64) bool { return v > 1 })
	if sel.Size() != 2 {
		t.Errorf("Select size = %d", sel.Size())
	}
}
func TestInt8Int64TreeMap_Generated_String(t *testing.T) {
	m := NewInt8Int64TreeMap()
	m.Put(1, 1)
	if m.String() == "" {
		t.Error("empty")
	}
}
