// Code generated by internal/codegen; DO NOT EDIT.

package hashset

import (
	"iter"
)

// ImmutableBool is an immutable view of a Bool.
type ImmutableBool struct {
	delegate *Bool
}

// NewImmutableBool creates an immutable set from the given values.
func NewImmutableBool(values ...bool) *ImmutableBool {
	return &ImmutableBool{delegate: BoolOf(values...)}
}

// ImmutableBoolFrom creates an immutable copy of a mutable set.
func ImmutableBoolFrom(s *Bool) *ImmutableBool {
	copy := BoolOf(s.ToSlice()...)
	return &ImmutableBool{delegate: copy}
}

// Contains returns true if the set contains the given value.
func (s *ImmutableBool) Contains(value bool) bool {
	return s.delegate.Contains(value)
}

// Len returns the number of elements. Use s.Len() == 0 to test for emptiness.
func (s *ImmutableBool) Len() int {
	return s.delegate.Len()
}

// All returns an iter.Seq that yields all elements.
func (s *ImmutableBool) All() iter.Seq[bool] {
	return s.delegate.All()
}

// ForEach calls the given function for each element.
func (s *ImmutableBool) ForEach(f func(bool)) {
	s.delegate.ForEach(f)
}

// Select returns a new immutable set with elements satisfying the predicate.
func (s *ImmutableBool) Select(predicate func(bool) bool) *ImmutableBool {
	return &ImmutableBool{delegate: s.delegate.Select(predicate)}
}

// Reject returns a new immutable set with elements not satisfying the predicate.
func (s *ImmutableBool) Reject(predicate func(bool) bool) *ImmutableBool {
	return &ImmutableBool{delegate: s.delegate.Reject(predicate)}
}

// AnySatisfy returns true if any element satisfies the predicate.
func (s *ImmutableBool) AnySatisfy(predicate func(bool) bool) bool {
	return s.delegate.AnySatisfy(predicate)
}

// AllSatisfy returns true if all elements satisfy the predicate.
func (s *ImmutableBool) AllSatisfy(predicate func(bool) bool) bool {
	return s.delegate.AllSatisfy(predicate)
}

// NoneSatisfy returns true if no element satisfies the predicate.
func (s *ImmutableBool) NoneSatisfy(predicate func(bool) bool) bool {
	return s.delegate.NoneSatisfy(predicate)
}

// Union returns a new immutable set with elements from both sets.
func (s *ImmutableBool) Union(other *ImmutableBool) *ImmutableBool {
	return &ImmutableBool{delegate: s.delegate.Union(other.delegate)}
}

// Intersect returns a new immutable set with elements in both sets.
func (s *ImmutableBool) Intersect(other *ImmutableBool) *ImmutableBool {
	return &ImmutableBool{delegate: s.delegate.Intersect(other.delegate)}
}

// Difference returns a new immutable set with elements in this but not other.
func (s *ImmutableBool) Difference(other *ImmutableBool) *ImmutableBool {
	return &ImmutableBool{delegate: s.delegate.Difference(other.delegate)}
}

// ToSlice returns all elements as a slice.
func (s *ImmutableBool) ToSlice() []bool {
	return s.delegate.ToSlice()
}

// String returns a string representation.
func (s *ImmutableBool) String() string {
	return s.delegate.String()
}

// Equals returns true if the other immutable set has the same elements.
func (s *ImmutableBool) Equals(other *ImmutableBool) bool {
	return s.delegate.Equals(other.delegate)
}

// ToMutable returns a mutable copy of this set.
func (s *ImmutableBool) ToMutable() *Bool {
	return BoolOf(s.ToSlice()...)
}
