// Code generated by internal/codegen; DO NOT EDIT.

package hashset

import (
	"iter"
)

// ImmutableInt64 is an immutable view of a Int64.
type ImmutableInt64 struct {
	delegate *Int64
}

// NewImmutableInt64 creates an immutable set from the given values.
func NewImmutableInt64(values ...int64) *ImmutableInt64 {
	return &ImmutableInt64{delegate: Int64Of(values...)}
}

// ImmutableInt64From creates an immutable copy of a mutable set.
func ImmutableInt64From(s *Int64) *ImmutableInt64 {
	copy := Int64Of(s.ToSlice()...)
	return &ImmutableInt64{delegate: copy}
}

// Contains returns true if the set contains the given value.
func (s *ImmutableInt64) Contains(value int64) bool {
	return s.delegate.Contains(value)
}

// Len returns the number of elements. Use s.Len() == 0 to test for emptiness.
func (s *ImmutableInt64) Len() int {
	return s.delegate.Len()
}

// All returns an iter.Seq that yields all elements.
func (s *ImmutableInt64) All() iter.Seq[int64] {
	return s.delegate.All()
}

// ForEach calls the given function for each element.
func (s *ImmutableInt64) ForEach(f func(int64)) {
	s.delegate.ForEach(f)
}

// Select returns a new immutable set with elements satisfying the predicate.
func (s *ImmutableInt64) Select(predicate func(int64) bool) *ImmutableInt64 {
	return &ImmutableInt64{delegate: s.delegate.Select(predicate)}
}

// Reject returns a new immutable set with elements not satisfying the predicate.
func (s *ImmutableInt64) Reject(predicate func(int64) bool) *ImmutableInt64 {
	return &ImmutableInt64{delegate: s.delegate.Reject(predicate)}
}

// AnySatisfy returns true if any element satisfies the predicate.
func (s *ImmutableInt64) AnySatisfy(predicate func(int64) bool) bool {
	return s.delegate.AnySatisfy(predicate)
}

// AllSatisfy returns true if all elements satisfy the predicate.
func (s *ImmutableInt64) AllSatisfy(predicate func(int64) bool) bool {
	return s.delegate.AllSatisfy(predicate)
}

// NoneSatisfy returns true if no element satisfies the predicate.
func (s *ImmutableInt64) NoneSatisfy(predicate func(int64) bool) bool {
	return s.delegate.NoneSatisfy(predicate)
}

// Union returns a new immutable set with elements from both sets.
func (s *ImmutableInt64) Union(other *ImmutableInt64) *ImmutableInt64 {
	return &ImmutableInt64{delegate: s.delegate.Union(other.delegate)}
}

// Intersect returns a new immutable set with elements in both sets.
func (s *ImmutableInt64) Intersect(other *ImmutableInt64) *ImmutableInt64 {
	return &ImmutableInt64{delegate: s.delegate.Intersect(other.delegate)}
}

// Difference returns a new immutable set with elements in this but not other.
func (s *ImmutableInt64) Difference(other *ImmutableInt64) *ImmutableInt64 {
	return &ImmutableInt64{delegate: s.delegate.Difference(other.delegate)}
}

// ToSlice returns all elements as a slice.
func (s *ImmutableInt64) ToSlice() []int64 {
	return s.delegate.ToSlice()
}

// String returns a string representation.
func (s *ImmutableInt64) String() string {
	return s.delegate.String()
}

// Equals returns true if the other immutable set has the same elements.
func (s *ImmutableInt64) Equals(other *ImmutableInt64) bool {
	return s.delegate.Equals(other.delegate)
}

// ToMutable returns a mutable copy of this set.
func (s *ImmutableInt64) ToMutable() *Int64 {
	return Int64Of(s.ToSlice()...)
}
