// Code generated by mapdb-codegen. DO NOT EDIT.

package hashset

import (
	"iter"
	"sync"
)

// SynchronizedFloat32HashSet is a thread-safe wrapper around Float32HashSet.
type SynchronizedFloat32HashSet struct {
	delegate *Float32HashSet
	mu       sync.RWMutex
}

// NewSynchronizedFloat32HashSet creates a new thread-safe empty set.
func NewSynchronizedFloat32HashSet() *SynchronizedFloat32HashSet {
	return &SynchronizedFloat32HashSet{delegate: NewFloat32HashSet()}
}

func (s *SynchronizedFloat32HashSet) Add(value float32) bool {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.delegate.Add(value)
}

func (s *SynchronizedFloat32HashSet) Remove(value float32) bool {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.delegate.Remove(value)
}

func (s *SynchronizedFloat32HashSet) Contains(value float32) bool {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.delegate.Contains(value)
}

func (s *SynchronizedFloat32HashSet) Size() int {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.delegate.Size()
}

func (s *SynchronizedFloat32HashSet) IsEmpty() bool {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.delegate.IsEmpty()
}

func (s *SynchronizedFloat32HashSet) Clear() {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.delegate.Clear()
}

func (s *SynchronizedFloat32HashSet) All() iter.Seq[float32] {
	s.mu.RLock()
	snapshot := s.delegate.ToSlice()
	s.mu.RUnlock()
	return func(yield func(float32) bool) {
		for _, v := range snapshot {
			if !yield(v) {
				return
			}
		}
	}
}

func (s *SynchronizedFloat32HashSet) ToSlice() []float32 {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.delegate.ToSlice()
}

func (s *SynchronizedFloat32HashSet) String() string {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.delegate.String()
}
