// Code generated by internal/codegen; DO NOT EDIT.

package hashset

import (
	"iter"
	"sync"
	"unsafe"
)

// SynchronizedFloat32 is a thread-safe wrapper around Float32.
//
// Read methods hold an RLock; writes hold a Lock. Methods that take a
// caller-supplied function (Select, ForEach, AnySatisfy, …) snapshot
// the backing set under RLock and release it before invoking the
// callback, so the callback is free to call back into the wrapper
// without deadlocking.
//
// Methods that return a new set (Select, Reject, Union, Intersect,
// Difference, SymmetricDifference) return an unwrapped *Float32;
// the caller owns it.
type SynchronizedFloat32 struct {
	delegate *Float32
	mu       sync.RWMutex
}

// NewSynchronizedFloat32 creates a new thread-safe empty set.
func NewSynchronizedFloat32() *SynchronizedFloat32 {
	return &SynchronizedFloat32{delegate: NewFloat32()}
}

// NewSynchronizedFloat32From wraps an existing set. The
// wrapper takes ownership — callers must not mutate the delegate
// directly without locking.
func NewSynchronizedFloat32From(s *Float32) *SynchronizedFloat32 {
	return &SynchronizedFloat32{delegate: s}
}

// SynchronizedFloat32Of constructs a synchronized set from values.
func SynchronizedFloat32Of(values ...float32) *SynchronizedFloat32 {
	s := NewFloat32()
	for _, v := range values {
		s.Add(v)
	}
	return &SynchronizedFloat32{delegate: s}
}

// snapshot returns a defensive copy of the set's elements under RLock.
func (s *SynchronizedFloat32) snapshot() []float32 {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.delegate.ToSlice()
}

// ── writes ────────────────────────────────────────────────────────────

func (s *SynchronizedFloat32) Add(value float32) bool {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.delegate.Add(value)
}

func (s *SynchronizedFloat32) AddAll(values ...float32) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.delegate.AddAll(values...)
}

func (s *SynchronizedFloat32) Remove(value float32) bool {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.delegate.Remove(value)
}

func (s *SynchronizedFloat32) Clear() {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.delegate.Clear()
}

// ── simple reads ──────────────────────────────────────────────────────

func (s *SynchronizedFloat32) Contains(value float32) bool {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.delegate.Contains(value)
}

// Len returns the number of elements. Use s.Len() == 0 to test for emptiness.
func (s *SynchronizedFloat32) Len() int {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.delegate.Len()
}

func (s *SynchronizedFloat32) ToSlice() []float32 {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.delegate.ToSlice()
}

func (s *SynchronizedFloat32) String() string {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.delegate.String()
}

// ── iteration ────────────────────────────────────────────────────────

// All returns an iter.Seq over a snapshot. Iteration is lock-free.
func (s *SynchronizedFloat32) All() iter.Seq[float32] {
	snapshot := s.snapshot()
	return func(yield func(float32) bool) {
		for _, v := range snapshot {
			if !yield(v) {
				return
			}
		}
	}
}

// ── functional over snapshot ──────────────────────────────────────────

func (s *SynchronizedFloat32) ForEach(f func(float32)) {
	for _, v := range s.snapshot() {
		f(v)
	}
}

func (s *SynchronizedFloat32) AnySatisfy(predicate func(float32) bool) bool {
	for _, v := range s.snapshot() {
		if predicate(v) {
			return true
		}
	}
	return false
}

func (s *SynchronizedFloat32) AllSatisfy(predicate func(float32) bool) bool {
	for _, v := range s.snapshot() {
		if !predicate(v) {
			return false
		}
	}
	return true
}

func (s *SynchronizedFloat32) NoneSatisfy(predicate func(float32) bool) bool {
	for _, v := range s.snapshot() {
		if predicate(v) {
			return false
		}
	}
	return true
}

func (s *SynchronizedFloat32) Detect(predicate func(float32) bool) (float32, bool) {
	for _, v := range s.snapshot() {
		if predicate(v) {
			return v, true
		}
	}
	var zero float32
	return zero, false
}

// ── functional that return a new set ─────────────────────────────────

func (s *SynchronizedFloat32) Select(predicate func(float32) bool) *Float32 {
	snapshot := s.snapshot()
	result := NewFloat32()
	for _, v := range snapshot {
		if predicate(v) {
			result.Add(v)
		}
	}
	return result
}

func (s *SynchronizedFloat32) Reject(predicate func(float32) bool) *Float32 {
	snapshot := s.snapshot()
	result := NewFloat32()
	for _, v := range snapshot {
		if !predicate(v) {
			result.Add(v)
		}
	}
	return result
}

// ── set operations (two-lock, deadlock-safe) ──────────────────────────

// lockPair acquires two RLocks in pointer-address order and returns
// a release function. Guarantees no A.op(B) ⟷ B.op(A) deadlock.
func (s *SynchronizedFloat32) lockPair(other *SynchronizedFloat32) func() {
	if s == other {
		s.mu.RLock()
		return func() { s.mu.RUnlock() }
	}
	first, second := s, other
	if uintptr(unsafe.Pointer(s)) > uintptr(unsafe.Pointer(other)) {
		first, second = other, s
	}
	first.mu.RLock()
	second.mu.RLock()
	return func() { second.mu.RUnlock(); first.mu.RUnlock() }
}

func (s *SynchronizedFloat32) Union(other *SynchronizedFloat32) *Float32 {
	release := s.lockPair(other)
	defer release()
	return s.delegate.Union(other.delegate)
}

func (s *SynchronizedFloat32) Intersect(other *SynchronizedFloat32) *Float32 {
	release := s.lockPair(other)
	defer release()
	return s.delegate.Intersect(other.delegate)
}

func (s *SynchronizedFloat32) Difference(other *SynchronizedFloat32) *Float32 {
	release := s.lockPair(other)
	defer release()
	return s.delegate.Difference(other.delegate)
}

func (s *SynchronizedFloat32) SymmetricDifference(other *SynchronizedFloat32) *Float32 {
	release := s.lockPair(other)
	defer release()
	return s.delegate.SymmetricDifference(other.delegate)
}

// ── fluent mutators ───────────────────────────────────────────────────

// AddReturning adds the value and returns the receiver (mutating, fluent).
func (s *SynchronizedFloat32) AddReturning(value float32) *SynchronizedFloat32 {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.delegate.AddReturning(value)
	return s
}

// AddAllReturning adds all values and returns the receiver (mutating, fluent).
func (s *SynchronizedFloat32) AddAllReturning(values ...float32) *SynchronizedFloat32 {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.delegate.AddAllReturning(values...)
	return s
}

// RemoveReturning removes the value and returns the receiver (mutating, fluent).
func (s *SynchronizedFloat32) RemoveReturning(value float32) *SynchronizedFloat32 {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.delegate.RemoveReturning(value)
	return s
}

// RemoveAllReturning removes all given values and returns the receiver (mutating, fluent).
func (s *SynchronizedFloat32) RemoveAllReturning(values ...float32) *SynchronizedFloat32 {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.delegate.RemoveAllReturning(values...)
	return s
}

// ── conversions ───────────────────────────────────────────────────────

func (s *SynchronizedFloat32) ToImmutable() *ImmutableFloat32 {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.delegate.ToImmutable()
}

// Equals compares by contents. Locks are acquired in pointer-address
// order to prevent deadlocks under concurrent A.Equals(B) / B.Equals(A).
func (s *SynchronizedFloat32) Equals(other *SynchronizedFloat32) bool {
	release := s.lockPair(other)
	defer release()
	return s.delegate.Equals(other.delegate)
}
