// Code generated by mapdb-codegen. DO NOT EDIT.

package hashset

import (
	"iter"
	"sync"
)

// SynchronizedInt32HashSet is a thread-safe wrapper around Int32HashSet.
type SynchronizedInt32HashSet struct {
	delegate *Int32HashSet
	mu       sync.RWMutex
}

// NewSynchronizedInt32HashSet creates a new thread-safe empty set.
func NewSynchronizedInt32HashSet() *SynchronizedInt32HashSet {
	return &SynchronizedInt32HashSet{delegate: NewInt32HashSet()}
}

func (s *SynchronizedInt32HashSet) Add(value int32) bool {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.delegate.Add(value)
}

func (s *SynchronizedInt32HashSet) Remove(value int32) bool {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.delegate.Remove(value)
}

func (s *SynchronizedInt32HashSet) Contains(value int32) bool {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.delegate.Contains(value)
}

func (s *SynchronizedInt32HashSet) Size() int {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.delegate.Size()
}

func (s *SynchronizedInt32HashSet) IsEmpty() bool {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.delegate.IsEmpty()
}

func (s *SynchronizedInt32HashSet) Clear() {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.delegate.Clear()
}

func (s *SynchronizedInt32HashSet) All() iter.Seq[int32] {
	s.mu.RLock()
	snapshot := s.delegate.ToSlice()
	s.mu.RUnlock()
	return func(yield func(int32) bool) {
		for _, v := range snapshot {
			if !yield(v) {
				return
			}
		}
	}
}

func (s *SynchronizedInt32HashSet) ToSlice() []int32 {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.delegate.ToSlice()
}

func (s *SynchronizedInt32HashSet) String() string {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.delegate.String()
}
