// Code generated by internal/codegen; DO NOT EDIT.

package sentinelhashmap

import (
	"fmt"
	"iter"
	"math"
	"strings"
)

const (
	charFloat64SentinelHashMapDefaultCapacity = 16
	// Load factor 3/4 = 0.75, using integer math to avoid float conversion per insert.
	charFloat64SentinelHashMapEmptyKey   = uint16(0)
	charFloat64SentinelHashMapRemovedKey = uint16(1)
)

// CharFloat64SentinelHashMap is a sentinel-based open-addressing hash map with uint16 keys and float64 values.
// It uses sentinel values (0=empty, 1=removed) to track slot state.
// Keys 0 and 1 are stored separately in dedicated fields.
type CharFloat64SentinelHashMap struct {
	keys   []uint16
	values []float64
	size   int

	// Sentinel key storage — keys 0 and 1 are valid user keys but also
	// serve as empty/removed markers in the table, so we store them separately.
	zeroKeyPresent bool
	zeroKeyValue   float64
	oneKeyPresent  bool
	oneKeyValue    float64
}

// NewCharFloat64SentinelHashMap creates a new empty CharFloat64SentinelHashMap with default capacity.
func NewCharFloat64SentinelHashMap() *CharFloat64SentinelHashMap {
	return NewCharFloat64SentinelHashMapWithCapacity(charFloat64SentinelHashMapDefaultCapacity)
}

// NewCharFloat64SentinelHashMapWithCapacity creates a new empty CharFloat64SentinelHashMap with the given initial capacity.
func NewCharFloat64SentinelHashMapWithCapacity(capacity int) *CharFloat64SentinelHashMap {
	cap := nextPowerOfTwoCharFloat64SentinelHashMap(capacity)
	return &CharFloat64SentinelHashMap{
		keys:   make([]uint16, cap),
		values: make([]float64, cap),
		size:   0,
	}
}

// Put inserts or updates a key-value pair. Returns the previous value and true if the key existed.
func (m *CharFloat64SentinelHashMap) Put(key uint16, value float64) (float64, bool) {
	if key == charFloat64SentinelHashMapEmptyKey {
		old := m.zeroKeyValue
		existed := m.zeroKeyPresent
		m.zeroKeyValue = value
		if !m.zeroKeyPresent {
			m.zeroKeyPresent = true
			m.size++
		}
		return old, existed
	}
	if key == charFloat64SentinelHashMapRemovedKey {
		old := m.oneKeyValue
		existed := m.oneKeyPresent
		m.oneKeyValue = value
		if !m.oneKeyPresent {
			m.oneKeyPresent = true
			m.size++
		}
		return old, existed
	}
	return m.putRegular(key, value)
}

func (m *CharFloat64SentinelHashMap) putRegular(key uint16, value float64) (float64, bool) {
	if m.needsResize() {
		m.resize()
	}
	cap := len(m.keys)
	mask := cap - 1
	idx := int(m.hashKey(key)) & mask
	empty := charFloat64SentinelHashMapEmptyKey
	removed := charFloat64SentinelHashMapRemovedKey
	firstRemoved := -1

	for {
		k := m.keys[idx]
		if k == empty {
			if firstRemoved >= 0 {
				idx = firstRemoved
			}
			m.keys[idx] = key
			m.values[idx] = value
			m.size++
			return 0.0, false
		}
		if k == removed {
			if firstRemoved < 0 {
				firstRemoved = idx
			}
			idx = (idx + 1) & mask
			continue
		}
		if k == key {
			old := m.values[idx]
			m.values[idx] = value
			return old, true
		}
		idx = (idx + 1) & mask
	}
}

// Get returns the value for the given key and true if found, or the zero value and false if not.
func (m *CharFloat64SentinelHashMap) Get(key uint16) (float64, bool) {
	if key == charFloat64SentinelHashMapEmptyKey {
		if m.zeroKeyPresent {
			return m.zeroKeyValue, true
		}
		return 0.0, false
	}
	if key == charFloat64SentinelHashMapRemovedKey {
		if m.oneKeyPresent {
			return m.oneKeyValue, true
		}
		return 0.0, false
	}
	cap := len(m.keys)
	if cap == 0 {
		return 0.0, false
	}
	mask := cap - 1
	idx := int(m.hashKey(key)) & mask
	empty := charFloat64SentinelHashMapEmptyKey

	for {
		k := m.keys[idx]
		if k == empty {
			return 0.0, false
		}
		if k == key {
			return m.values[idx], true
		}
		idx = (idx + 1) & mask
	}
}

// GetOrDefault returns the value for the given key if present, or the default value otherwise.
func (m *CharFloat64SentinelHashMap) GetOrDefault(key uint16, defaultValue float64) float64 {
	if v, ok := m.Get(key); ok {
		return v
	}
	return defaultValue
}

// Remove deletes the entry for the given key. Returns the previous value and true if the key existed.
func (m *CharFloat64SentinelHashMap) Remove(key uint16) (float64, bool) {
	if key == charFloat64SentinelHashMapEmptyKey {
		if m.zeroKeyPresent {
			old := m.zeroKeyValue
			m.zeroKeyPresent = false
			m.zeroKeyValue = 0.0
			m.size--
			return old, true
		}
		return 0.0, false
	}
	if key == charFloat64SentinelHashMapRemovedKey {
		if m.oneKeyPresent {
			old := m.oneKeyValue
			m.oneKeyPresent = false
			m.oneKeyValue = 0.0
			m.size--
			return old, true
		}
		return 0.0, false
	}
	return m.removeRegular(key)
}

func (m *CharFloat64SentinelHashMap) removeRegular(key uint16) (float64, bool) {
	cap := len(m.keys)
	if cap == 0 {
		return 0.0, false
	}
	mask := cap - 1
	idx := int(m.hashKey(key)) & mask
	empty := charFloat64SentinelHashMapEmptyKey

	for {
		k := m.keys[idx]
		if k == empty {
			return 0.0, false
		}
		if k == key {
			old := m.values[idx]
			m.keys[idx] = charFloat64SentinelHashMapRemovedKey
			m.values[idx] = 0.0
			m.size--
			return old, true
		}
		idx = (idx + 1) & mask
	}
}

// ContainsKey returns true if the map contains the given key.
func (m *CharFloat64SentinelHashMap) ContainsKey(key uint16) bool {
	_, ok := m.Get(key)
	return ok
}

// ContainsValue returns true if the map contains the given value.
func (m *CharFloat64SentinelHashMap) ContainsValue(value float64) bool {
	empty := charFloat64SentinelHashMapEmptyKey
	removed := charFloat64SentinelHashMapRemovedKey
	if m.zeroKeyPresent && math.Float64bits(m.zeroKeyValue) == math.Float64bits(value) {
		return true
	}
	if m.oneKeyPresent && math.Float64bits(m.oneKeyValue) == math.Float64bits(value) {
		return true
	}
	for i := range m.keys {
		if m.keys[i] != empty && m.keys[i] != removed && math.Float64bits(m.values[i]) == math.Float64bits(value) {
			return true
		}
	}
	return false
}

// Size returns the number of key-value pairs in the map.
func (m *CharFloat64SentinelHashMap) Size() int {
	return m.size
}

// IsEmpty returns true if the map contains no entries.
func (m *CharFloat64SentinelHashMap) IsEmpty() bool {
	return m.size == 0
}

// Clear removes all entries from the map.
func (m *CharFloat64SentinelHashMap) Clear() {
	for i := range m.keys {
		m.keys[i] = 0
		m.values[i] = 0.0
	}
	m.zeroKeyPresent = false
	m.zeroKeyValue = 0.0
	m.oneKeyPresent = false
	m.oneKeyValue = 0.0
	m.size = 0
}

// All returns an iter.Seq2 that yields all key-value pairs.
func (m *CharFloat64SentinelHashMap) All() iter.Seq2[uint16, float64] {
	return func(yield func(uint16, float64) bool) {
		if m.zeroKeyPresent {
			if !yield(0, m.zeroKeyValue) {
				return
			}
		}
		if m.oneKeyPresent {
			if !yield(charFloat64SentinelHashMapRemovedKey, m.oneKeyValue) {
				return
			}
		}
		empty := charFloat64SentinelHashMapEmptyKey
		removed := charFloat64SentinelHashMapRemovedKey
		for i := range m.keys {
			if m.keys[i] != empty && m.keys[i] != removed {
				if !yield(m.keys[i], m.values[i]) {
					return
				}
			}
		}
	}
}

// Keys returns an iter.Seq that yields all keys.
func (m *CharFloat64SentinelHashMap) Keys() iter.Seq[uint16] {
	return func(yield func(uint16) bool) {
		if m.zeroKeyPresent {
			if !yield(0) {
				return
			}
		}
		if m.oneKeyPresent {
			if !yield(charFloat64SentinelHashMapRemovedKey) {
				return
			}
		}
		empty := charFloat64SentinelHashMapEmptyKey
		removed := charFloat64SentinelHashMapRemovedKey
		for i := range m.keys {
			if m.keys[i] != empty && m.keys[i] != removed {
				if !yield(m.keys[i]) {
					return
				}
			}
		}
	}
}

// Values returns an iter.Seq that yields all values.
func (m *CharFloat64SentinelHashMap) Values() iter.Seq[float64] {
	return func(yield func(float64) bool) {
		if m.zeroKeyPresent {
			if !yield(m.zeroKeyValue) {
				return
			}
		}
		if m.oneKeyPresent {
			if !yield(m.oneKeyValue) {
				return
			}
		}
		empty := charFloat64SentinelHashMapEmptyKey
		removed := charFloat64SentinelHashMapRemovedKey
		for i := range m.keys {
			if m.keys[i] != empty && m.keys[i] != removed {
				if !yield(m.values[i]) {
					return
				}
			}
		}
	}
}

// ForEach calls the given function for each key-value pair.
func (m *CharFloat64SentinelHashMap) ForEach(f func(uint16, float64)) {
	for k, v := range m.All() {
		f(k, v)
	}
}

// Select returns a new map containing only the key-value pairs that satisfy the predicate.
func (m *CharFloat64SentinelHashMap) Select(predicate func(uint16, float64) bool) *CharFloat64SentinelHashMap {
	result := NewCharFloat64SentinelHashMap()
	for k, v := range m.All() {
		if predicate(k, v) {
			result.Put(k, v)
		}
	}
	return result
}

// Reject returns a new map containing only the key-value pairs that do not satisfy the predicate.
func (m *CharFloat64SentinelHashMap) Reject(predicate func(uint16, float64) bool) *CharFloat64SentinelHashMap {
	result := NewCharFloat64SentinelHashMap()
	for k, v := range m.All() {
		if !predicate(k, v) {
			result.Put(k, v)
		}
	}
	return result
}

// AnySatisfy returns true if any key-value pair satisfies the predicate.
func (m *CharFloat64SentinelHashMap) AnySatisfy(predicate func(uint16, float64) bool) bool {
	for k, v := range m.All() {
		if predicate(k, v) {
			return true
		}
	}
	return false
}

// AllSatisfy returns true if all key-value pairs satisfy the predicate.
func (m *CharFloat64SentinelHashMap) AllSatisfy(predicate func(uint16, float64) bool) bool {
	for k, v := range m.All() {
		if !predicate(k, v) {
			return false
		}
	}
	return true
}

// NoneSatisfy returns true if no key-value pair satisfies the predicate.
func (m *CharFloat64SentinelHashMap) NoneSatisfy(predicate func(uint16, float64) bool) bool {
	return !m.AnySatisfy(predicate)
}

// String returns a string representation of the map.
func (m *CharFloat64SentinelHashMap) String() string {
	if m.size == 0 {
		return "{}"
	}
	var sb strings.Builder
	sb.WriteString("{")
	first := true
	for k, v := range m.All() {
		if !first {
			sb.WriteString(", ")
		}
		fmt.Fprintf(&sb, "%v: %v", k, v)
		first = false
	}
	sb.WriteString("}")
	return sb.String()
}

func (m *CharFloat64SentinelHashMap) hashKey(key uint16) uint64 {
	h := uint64(key) * 0x9E3779B97F4A7C15
	return h ^ (h >> 32)
}

func (m *CharFloat64SentinelHashMap) needsResize() bool {
	// Count only regular entries (not sentinel entries) for load factor
	regularEntries := m.size
	if m.zeroKeyPresent {
		regularEntries--
	}
	if m.oneKeyPresent {
		regularEntries--
	}
	return (regularEntries+1)*4 >= len(m.keys)*3 // 0.75 load factor, integer math
}

func (m *CharFloat64SentinelHashMap) resize() {
	oldKeys := m.keys
	oldValues := m.values
	newCap := len(oldKeys) * 2
	if newCap == 0 {
		newCap = charFloat64SentinelHashMapDefaultCapacity
	}

	// Save sentinel state
	savedSize := m.size
	savedZeroPresent := m.zeroKeyPresent
	savedZeroValue := m.zeroKeyValue
	savedOnePresent := m.oneKeyPresent
	savedOneValue := m.oneKeyValue

	m.keys = make([]uint16, newCap)
	m.values = make([]float64, newCap)
	m.size = 0
	m.zeroKeyPresent = false
	m.oneKeyPresent = false

	// Re-insert sentinel entries
	if savedZeroPresent {
		m.Put(0, savedZeroValue)
	}
	if savedOnePresent {
		m.Put(charFloat64SentinelHashMapRemovedKey, savedOneValue)
	}

	// Re-insert regular entries
	empty := charFloat64SentinelHashMapEmptyKey
	removed := charFloat64SentinelHashMapRemovedKey
	for i := range oldKeys {
		if oldKeys[i] != empty && oldKeys[i] != removed {
			m.Put(oldKeys[i], oldValues[i])
		}
	}
	_ = savedSize
}

func nextPowerOfTwoCharFloat64SentinelHashMap(n int) int {
	if n <= 0 {
		return 16
	}
	n--
	n |= n >> 1
	n |= n >> 2
	n |= n >> 4
	n |= n >> 8
	n |= n >> 16
	n |= n >> 32 // no-op on 32-bit platforms (Go shifts are width-defined), required on 64-bit
	n++
	return n
}
