// Code generated by internal/codegen; DO NOT EDIT.

package sentinelhashmap

import (
	"fmt"
	"iter"
	"math"
	"strings"
)

const (
	float64Int32SentinelHashMapDefaultCapacity = 16
	// Load factor 3/4 = 0.75, using integer math to avoid float conversion per insert.
	float64Int32SentinelHashMapEmptyKey   = float64(0)
	float64Int32SentinelHashMapRemovedKey = float64(1)
	// float64Int32SentinelHashMapNegZeroBits is the IEEE-754 bit pattern of -0.0, routed to a
	// dedicated field so -0.0 stays distinct from +0.0 (which collides with
	// the empty sentinel) and from the table.
	float64Int32SentinelHashMapNegZeroBits = uint64(0x8000000000000000)
)

// Float64Int32SentinelHashMap is a sentinel-based open-addressing hash map with float64 keys and int32 values.
// It uses sentinel values (0=empty, 1=removed) to track slot state.
// Keys 0 and 1 are stored separately in dedicated fields.
type Float64Int32SentinelHashMap struct {
	keys   []float64
	values []int32
	size   int

	// Sentinel key storage — keys 0 and 1 are valid user keys but also
	// serve as empty/removed markers in the table, so we store them separately.
	zeroKeyPresent    bool
	zeroKeyValue      int32
	negZeroKeyPresent bool
	negZeroKeyValue   int32
	oneKeyPresent     bool
	oneKeyValue       int32
}

// NewFloat64Int32SentinelHashMap creates a new empty Float64Int32SentinelHashMap with default capacity.
func NewFloat64Int32SentinelHashMap() *Float64Int32SentinelHashMap {
	return NewFloat64Int32SentinelHashMapWithCapacity(float64Int32SentinelHashMapDefaultCapacity)
}

// NewFloat64Int32SentinelHashMapWithCapacity creates a new empty Float64Int32SentinelHashMap with the given initial capacity.
func NewFloat64Int32SentinelHashMapWithCapacity(capacity int) *Float64Int32SentinelHashMap {
	cap := nextPowerOfTwoFloat64Int32SentinelHashMap(capacity)
	return &Float64Int32SentinelHashMap{
		keys:   make([]float64, cap),
		values: make([]int32, cap),
		size:   0,
	}
}

// Put inserts or updates a key-value pair. Returns the previous value and true if the key existed.
func (m *Float64Int32SentinelHashMap) Put(key float64, value int32) (int32, bool) {
	if math.Float64bits(key) == math.Float64bits(float64Int32SentinelHashMapEmptyKey) {
		old := m.zeroKeyValue
		existed := m.zeroKeyPresent
		m.zeroKeyValue = value
		if !m.zeroKeyPresent {
			m.zeroKeyPresent = true
			m.size++
		}
		return old, existed
	}
	if math.Float64bits(key) == float64Int32SentinelHashMapNegZeroBits {
		old := m.negZeroKeyValue
		existed := m.negZeroKeyPresent
		m.negZeroKeyValue = value
		if !m.negZeroKeyPresent {
			m.negZeroKeyPresent = true
			m.size++
		}
		return old, existed
	}
	if key == float64Int32SentinelHashMapRemovedKey {
		old := m.oneKeyValue
		existed := m.oneKeyPresent
		m.oneKeyValue = value
		if !m.oneKeyPresent {
			m.oneKeyPresent = true
			m.size++
		}
		return old, existed
	}
	return m.putRegular(key, value)
}

func (m *Float64Int32SentinelHashMap) putRegular(key float64, value int32) (int32, bool) {
	if m.needsResize() {
		m.resize()
	}
	cap := len(m.keys)
	mask := cap - 1
	idx := int(m.hashKey(key)) & mask
	empty := float64Int32SentinelHashMapEmptyKey
	removed := float64Int32SentinelHashMapRemovedKey
	firstRemoved := -1

	for {
		k := m.keys[idx]
		if k == empty {
			if firstRemoved >= 0 {
				idx = firstRemoved
			}
			m.keys[idx] = key
			m.values[idx] = value
			m.size++
			return 0, false
		}
		if k == removed {
			if firstRemoved < 0 {
				firstRemoved = idx
			}
			idx = (idx + 1) & mask
			continue
		}
		if math.Float64bits(k) == math.Float64bits(key) {
			old := m.values[idx]
			m.values[idx] = value
			return old, true
		}
		idx = (idx + 1) & mask
	}
}

// Get returns the value for the given key and true if found, or the zero value and false if not.
func (m *Float64Int32SentinelHashMap) Get(key float64) (int32, bool) {
	if math.Float64bits(key) == math.Float64bits(float64Int32SentinelHashMapEmptyKey) {
		if m.zeroKeyPresent {
			return m.zeroKeyValue, true
		}
		return 0, false
	}
	if math.Float64bits(key) == float64Int32SentinelHashMapNegZeroBits {
		if m.negZeroKeyPresent {
			return m.negZeroKeyValue, true
		}
		return 0, false
	}
	if key == float64Int32SentinelHashMapRemovedKey {
		if m.oneKeyPresent {
			return m.oneKeyValue, true
		}
		return 0, false
	}
	cap := len(m.keys)
	if cap == 0 {
		return 0, false
	}
	mask := cap - 1
	idx := int(m.hashKey(key)) & mask
	empty := float64Int32SentinelHashMapEmptyKey

	for {
		k := m.keys[idx]
		if k == empty {
			return 0, false
		}
		if math.Float64bits(k) == math.Float64bits(key) {
			return m.values[idx], true
		}
		idx = (idx + 1) & mask
	}
}

// GetOrDefault returns the value for the given key if present, or the default value otherwise.
func (m *Float64Int32SentinelHashMap) GetOrDefault(key float64, defaultValue int32) int32 {
	if v, ok := m.Get(key); ok {
		return v
	}
	return defaultValue
}

// Remove deletes the entry for the given key. Returns the previous value and true if the key existed.
func (m *Float64Int32SentinelHashMap) Remove(key float64) (int32, bool) {
	if math.Float64bits(key) == math.Float64bits(float64Int32SentinelHashMapEmptyKey) {
		if m.zeroKeyPresent {
			old := m.zeroKeyValue
			m.zeroKeyPresent = false
			m.zeroKeyValue = 0
			m.size--
			return old, true
		}
		return 0, false
	}
	if math.Float64bits(key) == float64Int32SentinelHashMapNegZeroBits {
		if m.negZeroKeyPresent {
			old := m.negZeroKeyValue
			m.negZeroKeyPresent = false
			m.negZeroKeyValue = 0
			m.size--
			return old, true
		}
		return 0, false
	}
	if key == float64Int32SentinelHashMapRemovedKey {
		if m.oneKeyPresent {
			old := m.oneKeyValue
			m.oneKeyPresent = false
			m.oneKeyValue = 0
			m.size--
			return old, true
		}
		return 0, false
	}
	return m.removeRegular(key)
}

func (m *Float64Int32SentinelHashMap) removeRegular(key float64) (int32, bool) {
	cap := len(m.keys)
	if cap == 0 {
		return 0, false
	}
	mask := cap - 1
	idx := int(m.hashKey(key)) & mask
	empty := float64Int32SentinelHashMapEmptyKey

	for {
		k := m.keys[idx]
		if k == empty {
			return 0, false
		}
		if math.Float64bits(k) == math.Float64bits(key) {
			old := m.values[idx]
			m.keys[idx] = float64Int32SentinelHashMapRemovedKey
			m.values[idx] = 0
			m.size--
			return old, true
		}
		idx = (idx + 1) & mask
	}
}

// ContainsKey returns true if the map contains the given key.
func (m *Float64Int32SentinelHashMap) ContainsKey(key float64) bool {
	_, ok := m.Get(key)
	return ok
}

// ContainsValue returns true if the map contains the given value.
func (m *Float64Int32SentinelHashMap) ContainsValue(value int32) bool {
	empty := float64Int32SentinelHashMapEmptyKey
	removed := float64Int32SentinelHashMapRemovedKey
	if m.zeroKeyPresent && m.zeroKeyValue == value {
		return true
	}
	if m.negZeroKeyPresent && m.negZeroKeyValue == value {
		return true
	}
	if m.oneKeyPresent && m.oneKeyValue == value {
		return true
	}
	for i := range m.keys {
		if m.keys[i] != empty && m.keys[i] != removed && m.values[i] == value {
			return true
		}
	}
	return false
}

// Size returns the number of key-value pairs in the map.
func (m *Float64Int32SentinelHashMap) Size() int {
	return m.size
}

// Len returns the number of elements. It is an alias for Size, matching
// Go convention (sort.Interface, container/list, bytes.Buffer).
func (m *Float64Int32SentinelHashMap) Len() int { return m.Size() }

// IsEmpty returns true if the map contains no entries.
func (m *Float64Int32SentinelHashMap) IsEmpty() bool {
	return m.size == 0
}

// Clear removes all entries from the map.
func (m *Float64Int32SentinelHashMap) Clear() {
	for i := range m.keys {
		m.keys[i] = 0.0
		m.values[i] = 0
	}
	m.zeroKeyPresent = false
	m.zeroKeyValue = 0
	m.negZeroKeyPresent = false
	m.negZeroKeyValue = 0
	m.oneKeyPresent = false
	m.oneKeyValue = 0
	m.size = 0
}

// All returns an iter.Seq2 that yields all key-value pairs.
func (m *Float64Int32SentinelHashMap) All() iter.Seq2[float64, int32] {
	return func(yield func(float64, int32) bool) {
		if m.zeroKeyPresent {
			if !yield(0.0, m.zeroKeyValue) {
				return
			}
		}
		if m.negZeroKeyPresent {
			if !yield(math.Copysign(0, -1), m.negZeroKeyValue) {
				return
			}
		}
		if m.oneKeyPresent {
			if !yield(float64Int32SentinelHashMapRemovedKey, m.oneKeyValue) {
				return
			}
		}
		empty := float64Int32SentinelHashMapEmptyKey
		removed := float64Int32SentinelHashMapRemovedKey
		for i := range m.keys {
			if m.keys[i] != empty && m.keys[i] != removed {
				if !yield(m.keys[i], m.values[i]) {
					return
				}
			}
		}
	}
}

// Keys returns an iter.Seq that yields all keys.
func (m *Float64Int32SentinelHashMap) Keys() iter.Seq[float64] {
	return func(yield func(float64) bool) {
		if m.zeroKeyPresent {
			if !yield(0.0) {
				return
			}
		}
		if m.negZeroKeyPresent {
			if !yield(math.Copysign(0, -1)) {
				return
			}
		}
		if m.oneKeyPresent {
			if !yield(float64Int32SentinelHashMapRemovedKey) {
				return
			}
		}
		empty := float64Int32SentinelHashMapEmptyKey
		removed := float64Int32SentinelHashMapRemovedKey
		for i := range m.keys {
			if m.keys[i] != empty && m.keys[i] != removed {
				if !yield(m.keys[i]) {
					return
				}
			}
		}
	}
}

// Values returns an iter.Seq that yields all values.
func (m *Float64Int32SentinelHashMap) Values() iter.Seq[int32] {
	return func(yield func(int32) bool) {
		if m.zeroKeyPresent {
			if !yield(m.zeroKeyValue) {
				return
			}
		}
		if m.negZeroKeyPresent {
			if !yield(m.negZeroKeyValue) {
				return
			}
		}
		if m.oneKeyPresent {
			if !yield(m.oneKeyValue) {
				return
			}
		}
		empty := float64Int32SentinelHashMapEmptyKey
		removed := float64Int32SentinelHashMapRemovedKey
		for i := range m.keys {
			if m.keys[i] != empty && m.keys[i] != removed {
				if !yield(m.values[i]) {
					return
				}
			}
		}
	}
}

// ForEach calls the given function for each key-value pair.
func (m *Float64Int32SentinelHashMap) ForEach(f func(float64, int32)) {
	for k, v := range m.All() {
		f(k, v)
	}
}

// Select returns a new map containing only the key-value pairs that satisfy the predicate.
func (m *Float64Int32SentinelHashMap) Select(predicate func(float64, int32) bool) *Float64Int32SentinelHashMap {
	result := NewFloat64Int32SentinelHashMap()
	for k, v := range m.All() {
		if predicate(k, v) {
			result.Put(k, v)
		}
	}
	return result
}

// Reject returns a new map containing only the key-value pairs that do not satisfy the predicate.
func (m *Float64Int32SentinelHashMap) Reject(predicate func(float64, int32) bool) *Float64Int32SentinelHashMap {
	result := NewFloat64Int32SentinelHashMap()
	for k, v := range m.All() {
		if !predicate(k, v) {
			result.Put(k, v)
		}
	}
	return result
}

// AnySatisfy returns true if any key-value pair satisfies the predicate.
func (m *Float64Int32SentinelHashMap) AnySatisfy(predicate func(float64, int32) bool) bool {
	for k, v := range m.All() {
		if predicate(k, v) {
			return true
		}
	}
	return false
}

// AllSatisfy returns true if all key-value pairs satisfy the predicate.
func (m *Float64Int32SentinelHashMap) AllSatisfy(predicate func(float64, int32) bool) bool {
	for k, v := range m.All() {
		if !predicate(k, v) {
			return false
		}
	}
	return true
}

// NoneSatisfy returns true if no key-value pair satisfies the predicate.
func (m *Float64Int32SentinelHashMap) NoneSatisfy(predicate func(float64, int32) bool) bool {
	return !m.AnySatisfy(predicate)
}

// String returns a string representation of the map.
func (m *Float64Int32SentinelHashMap) String() string {
	if m.size == 0 {
		return "{}"
	}
	var sb strings.Builder
	sb.WriteString("{")
	first := true
	for k, v := range m.All() {
		if !first {
			sb.WriteString(", ")
		}
		fmt.Fprintf(&sb, "%v: %v", k, v)
		first = false
	}
	sb.WriteString("}")
	return sb.String()
}

func (m *Float64Int32SentinelHashMap) hashKey(key float64) uint64 {
	h := math.Float64bits(key) * 0x9E3779B97F4A7C15
	return h ^ (h >> 32)
}

func (m *Float64Int32SentinelHashMap) needsResize() bool {
	// Count only regular entries (not sentinel entries) for load factor
	regularEntries := m.size
	if m.zeroKeyPresent {
		regularEntries--
	}
	if m.negZeroKeyPresent {
		regularEntries--
	}
	if m.oneKeyPresent {
		regularEntries--
	}
	return (regularEntries+1)*4 >= len(m.keys)*3 // 0.75 load factor, integer math
}

func (m *Float64Int32SentinelHashMap) resize() {
	oldKeys := m.keys
	oldValues := m.values
	newCap := len(oldKeys) * 2
	if newCap == 0 {
		newCap = float64Int32SentinelHashMapDefaultCapacity
	}

	// Save sentinel state
	savedSize := m.size
	savedZeroPresent := m.zeroKeyPresent
	savedZeroValue := m.zeroKeyValue
	savedNegZeroPresent := m.negZeroKeyPresent
	savedNegZeroValue := m.negZeroKeyValue
	savedOnePresent := m.oneKeyPresent
	savedOneValue := m.oneKeyValue

	m.keys = make([]float64, newCap)
	m.values = make([]int32, newCap)
	m.size = 0
	m.zeroKeyPresent = false
	m.negZeroKeyPresent = false
	m.oneKeyPresent = false

	// Re-insert sentinel entries
	if savedZeroPresent {
		m.Put(0.0, savedZeroValue)
	}
	if savedNegZeroPresent {
		m.Put(math.Copysign(0, -1), savedNegZeroValue)
	}
	if savedOnePresent {
		m.Put(float64Int32SentinelHashMapRemovedKey, savedOneValue)
	}

	// Re-insert regular entries
	empty := float64Int32SentinelHashMapEmptyKey
	removed := float64Int32SentinelHashMapRemovedKey
	for i := range oldKeys {
		if oldKeys[i] != empty && oldKeys[i] != removed {
			m.Put(oldKeys[i], oldValues[i])
		}
	}
	_ = savedSize
}

func nextPowerOfTwoFloat64Int32SentinelHashMap(n int) int {
	if n <= 0 {
		return 16
	}
	n--
	n |= n >> 1
	n |= n >> 2
	n |= n >> 4
	n |= n >> 8
	n |= n >> 16
	n |= n >> 32 // no-op on 32-bit platforms (Go shifts are width-defined), required on 64-bit
	n++
	return n
}
