// Code generated by internal/codegen; DO NOT EDIT.

package tuple

import (
	"fmt"
	"math"
)

// CharFloat64Pair is an immutable pair of (uint16, float64).
type CharFloat64Pair struct {
	one uint16
	two float64
}

// NewCharFloat64Pair creates a new CharFloat64Pair.
func NewCharFloat64Pair(one uint16, two float64) CharFloat64Pair {
	return CharFloat64Pair{one: one, two: two}
}

// One returns the first element.
func (p CharFloat64Pair) One() uint16 {
	return p.one
}

// Two returns the second element.
func (p CharFloat64Pair) Two() float64 {
	return p.two
}

// Equals returns true if both elements are equal.
func (p CharFloat64Pair) Equals(other CharFloat64Pair) bool {
	return p.one == other.one && math.Float64bits(p.two) == math.Float64bits(other.two)
}

// String returns a string representation.
func (p CharFloat64Pair) String() string {
	return fmt.Sprintf("(%v, %v)", p.one, p.two)
}

// CompareTo compares this pair to another. Compares first element first,
// then second element if first elements are equal.
// Returns negative if p < other, zero if equal, positive if p > other.
func (p CharFloat64Pair) CompareTo(other CharFloat64Pair) int {
	if p.one < other.one {
		return -1
	}
	if p.one > other.one {
		return 1
	}
	if p.two < other.two {
		return -1
	}
	if p.two > other.two {
		return 1
	}
	return 0
}

// Swap returns a new pair with elements swapped: (two, one).
func (p CharFloat64Pair) Swap() Float64CharPair {
	return NewFloat64CharPair(p.two, p.one)
}
