// Code generated by mapdb-codegen. DO NOT EDIT.

package tuple

import (
	"fmt"
)

// CharInt64Pair is an immutable pair of (uint16, int64).
type CharInt64Pair struct {
	one uint16
	two int64
}

// NewCharInt64Pair creates a new CharInt64Pair.
func NewCharInt64Pair(one uint16, two int64) CharInt64Pair {
	return CharInt64Pair{one: one, two: two}
}

// One returns the first element.
func (p CharInt64Pair) One() uint16 {
	return p.one
}

// Two returns the second element.
func (p CharInt64Pair) Two() int64 {
	return p.two
}

// Equals returns true if both elements are equal.
func (p CharInt64Pair) Equals(other CharInt64Pair) bool {
	return p.one == other.one && p.two == other.two
}

// String returns a string representation.
func (p CharInt64Pair) String() string {
	return fmt.Sprintf("(%v, %v)", p.one, p.two)
}

// CompareTo compares this pair to another. Compares first element first,
// then second element if first elements are equal.
// Returns negative if p < other, zero if equal, positive if p > other.
func (p CharInt64Pair) CompareTo(other CharInt64Pair) int {
	if p.one < other.one {
		return -1
	}
	if p.one > other.one {
		return 1
	}
	if p.two < other.two {
		return -1
	}
	if p.two > other.two {
		return 1
	}
	return 0
}

// Swap returns a new pair with elements swapped: (two, one).
func (p CharInt64Pair) Swap() Int64CharPair {
	return NewInt64CharPair(p.two, p.one)
}
