// Code generated by mapdb-codegen. DO NOT EDIT.

package hashmap

import (
	"iter"
)

// ImmutableFloat32Int8HashMap is an immutable view of a Float32Int8HashMap.
// It exposes only read operations. Any attempt to modify requires
// creating a mutable copy first via ToMutable().
type ImmutableFloat32Int8HashMap struct {
	delegate *Float32Int8HashMap
}

// NewImmutableFloat32Int8HashMap creates an immutable map from key-value pairs.
func NewImmutableFloat32Int8HashMap(pairs ...struct {
	Key   float32
	Value int8
}) *ImmutableFloat32Int8HashMap {
	m := NewFloat32Int8HashMapWithCapacity(len(pairs) * 2)
	for _, p := range pairs {
		m.Put(p.Key, p.Value)
	}
	return &ImmutableFloat32Int8HashMap{delegate: m}
}

// ImmutableFloat32Int8HashMapFrom creates an immutable copy of a mutable map.
func ImmutableFloat32Int8HashMapFrom(m *Float32Int8HashMap) *ImmutableFloat32Int8HashMap {
	copy := NewFloat32Int8HashMapWithCapacity(m.Size() * 2)
	m.ForEach(func(k float32, v int8) {
		copy.Put(k, v)
	})
	return &ImmutableFloat32Int8HashMap{delegate: copy}
}

// Get returns the value for the given key and true if found.
func (m *ImmutableFloat32Int8HashMap) Get(key float32) (int8, bool) {
	return m.delegate.Get(key)
}

// GetOrDefault returns the value for the given key if present, or the default value.
func (m *ImmutableFloat32Int8HashMap) GetOrDefault(key float32, defaultValue int8) int8 {
	return m.delegate.GetOrDefault(key, defaultValue)
}

// ContainsKey returns true if the map contains the given key.
func (m *ImmutableFloat32Int8HashMap) ContainsKey(key float32) bool {
	return m.delegate.ContainsKey(key)
}

// ContainsValue returns true if the map contains the given value.
func (m *ImmutableFloat32Int8HashMap) ContainsValue(value int8) bool {
	return m.delegate.ContainsValue(value)
}

// Size returns the number of key-value pairs.
func (m *ImmutableFloat32Int8HashMap) Size() int {
	return m.delegate.Size()
}

// IsEmpty returns true if the map contains no entries.
func (m *ImmutableFloat32Int8HashMap) IsEmpty() bool {
	return m.delegate.IsEmpty()
}

// All returns an iter.Seq2 that yields all key-value pairs.
func (m *ImmutableFloat32Int8HashMap) All() iter.Seq2[float32, int8] {
	return m.delegate.All()
}

// Keys returns an iter.Seq that yields all keys.
func (m *ImmutableFloat32Int8HashMap) Keys() iter.Seq[float32] {
	return m.delegate.Keys()
}

// Values returns an iter.Seq that yields all values.
func (m *ImmutableFloat32Int8HashMap) Values() iter.Seq[int8] {
	return m.delegate.Values()
}

// ForEach calls the given function for each key-value pair.
func (m *ImmutableFloat32Int8HashMap) ForEach(f func(float32, int8)) {
	m.delegate.ForEach(f)
}

// Select returns a new immutable map with entries that satisfy the predicate.
func (m *ImmutableFloat32Int8HashMap) Select(predicate func(float32, int8) bool) *ImmutableFloat32Int8HashMap {
	return &ImmutableFloat32Int8HashMap{delegate: m.delegate.Select(predicate)}
}

// Reject returns a new immutable map with entries that do not satisfy the predicate.
func (m *ImmutableFloat32Int8HashMap) Reject(predicate func(float32, int8) bool) *ImmutableFloat32Int8HashMap {
	return &ImmutableFloat32Int8HashMap{delegate: m.delegate.Reject(predicate)}
}

// AnySatisfy returns true if any entry satisfies the predicate.
func (m *ImmutableFloat32Int8HashMap) AnySatisfy(predicate func(float32, int8) bool) bool {
	return m.delegate.AnySatisfy(predicate)
}

// AllSatisfy returns true if all entries satisfy the predicate.
func (m *ImmutableFloat32Int8HashMap) AllSatisfy(predicate func(float32, int8) bool) bool {
	return m.delegate.AllSatisfy(predicate)
}

// NoneSatisfy returns true if no entry satisfies the predicate.
func (m *ImmutableFloat32Int8HashMap) NoneSatisfy(predicate func(float32, int8) bool) bool {
	return m.delegate.NoneSatisfy(predicate)
}

// KeysToSlice returns all keys as a slice.
func (m *ImmutableFloat32Int8HashMap) KeysToSlice() []float32 {
	return m.delegate.KeysToSlice()
}

// ValuesToSlice returns all values as a slice.
func (m *ImmutableFloat32Int8HashMap) ValuesToSlice() []int8 {
	return m.delegate.ValuesToSlice()
}

// String returns a string representation.
func (m *ImmutableFloat32Int8HashMap) String() string {
	return m.delegate.String()
}

// Equals returns true if the other immutable map has the same entries.
func (m *ImmutableFloat32Int8HashMap) Equals(other *ImmutableFloat32Int8HashMap) bool {
	return m.delegate.Equals(other.delegate)
}

// ToMutable returns a mutable copy of this map.
func (m *ImmutableFloat32Int8HashMap) ToMutable() *Float32Int8HashMap {
	copy := NewFloat32Int8HashMapWithCapacity(m.Size() * 2)
	m.ForEach(func(k float32, v int8) {
		copy.Put(k, v)
	})
	return copy
}
