// Code generated by internal/codegen; DO NOT EDIT.

package hashmap

import (
	"iter"
)

// ImmutableFloat32Int16 is an immutable view of a Float32Int16.
// It exposes only read operations. Any attempt to modify requires
// creating a mutable copy first via ToMutable().
type ImmutableFloat32Int16 struct {
	delegate *Float32Int16
}

// NewImmutableFloat32Int16 creates an immutable map from key-value pairs.
func NewImmutableFloat32Int16(pairs ...struct {
	Key   float32
	Value int16
}) *ImmutableFloat32Int16 {
	m := NewFloat32Int16WithCapacity(len(pairs) * 2)
	for _, p := range pairs {
		m.Put(p.Key, p.Value)
	}
	return &ImmutableFloat32Int16{delegate: m}
}

// ImmutableFloat32Int16From creates an immutable copy of a mutable map.
func ImmutableFloat32Int16From(m *Float32Int16) *ImmutableFloat32Int16 {
	copy := NewFloat32Int16WithCapacity(m.Len() * 2)
	m.ForEach(func(k float32, v int16) {
		copy.Put(k, v)
	})
	return &ImmutableFloat32Int16{delegate: copy}
}

// Get returns the value for the given key and true if found.
func (m *ImmutableFloat32Int16) Get(key float32) (int16, bool) {
	return m.delegate.Get(key)
}

// GetOrDefault returns the value for the given key if present, or the default value.
func (m *ImmutableFloat32Int16) GetOrDefault(key float32, defaultValue int16) int16 {
	return m.delegate.GetOrDefault(key, defaultValue)
}

// ContainsKey returns true if the map contains the given key.
func (m *ImmutableFloat32Int16) ContainsKey(key float32) bool {
	return m.delegate.ContainsKey(key)
}

// ContainsValue returns true if the map contains the given value.
func (m *ImmutableFloat32Int16) ContainsValue(value int16) bool {
	return m.delegate.ContainsValue(value)
}

// Len returns the number of elements. Use m.Len() == 0 to test for emptiness.
func (m *ImmutableFloat32Int16) Len() int {
	return m.delegate.Len()
}

// All returns an iter.Seq2 that yields all key-value pairs.
func (m *ImmutableFloat32Int16) All() iter.Seq2[float32, int16] {
	return m.delegate.All()
}

// Keys returns an iter.Seq that yields all keys.
func (m *ImmutableFloat32Int16) Keys() iter.Seq[float32] {
	return m.delegate.Keys()
}

// Values returns an iter.Seq that yields all values.
func (m *ImmutableFloat32Int16) Values() iter.Seq[int16] {
	return m.delegate.Values()
}

// ForEach calls the given function for each key-value pair.
func (m *ImmutableFloat32Int16) ForEach(f func(float32, int16)) {
	m.delegate.ForEach(f)
}

// Select returns a new immutable map with entries that satisfy the predicate.
func (m *ImmutableFloat32Int16) Select(predicate func(float32, int16) bool) *ImmutableFloat32Int16 {
	return &ImmutableFloat32Int16{delegate: m.delegate.Select(predicate)}
}

// Reject returns a new immutable map with entries that do not satisfy the predicate.
func (m *ImmutableFloat32Int16) Reject(predicate func(float32, int16) bool) *ImmutableFloat32Int16 {
	return &ImmutableFloat32Int16{delegate: m.delegate.Reject(predicate)}
}

// AnySatisfy returns true if any entry satisfies the predicate.
func (m *ImmutableFloat32Int16) AnySatisfy(predicate func(float32, int16) bool) bool {
	return m.delegate.AnySatisfy(predicate)
}

// AllSatisfy returns true if all entries satisfy the predicate.
func (m *ImmutableFloat32Int16) AllSatisfy(predicate func(float32, int16) bool) bool {
	return m.delegate.AllSatisfy(predicate)
}

// NoneSatisfy returns true if no entry satisfies the predicate.
func (m *ImmutableFloat32Int16) NoneSatisfy(predicate func(float32, int16) bool) bool {
	return m.delegate.NoneSatisfy(predicate)
}

// KeysToSlice returns all keys as a slice.
func (m *ImmutableFloat32Int16) KeysToSlice() []float32 {
	return m.delegate.KeysToSlice()
}

// ValuesToSlice returns all values as a slice.
func (m *ImmutableFloat32Int16) ValuesToSlice() []int16 {
	return m.delegate.ValuesToSlice()
}

// String returns a string representation.
func (m *ImmutableFloat32Int16) String() string {
	return m.delegate.String()
}

// Equals returns true if the other immutable map has the same entries.
func (m *ImmutableFloat32Int16) Equals(other *ImmutableFloat32Int16) bool {
	return m.delegate.Equals(other.delegate)
}

// ToMutable returns a mutable copy of this map.
func (m *ImmutableFloat32Int16) ToMutable() *Float32Int16 {
	copy := NewFloat32Int16WithCapacity(m.Len() * 2)
	m.ForEach(func(k float32, v int16) {
		copy.Put(k, v)
	})
	return copy
}
