// Code generated by internal/codegen; DO NOT EDIT.

package hashmap

import (
	"iter"
)

// ImmutableInt32Int32 is an immutable view of a Int32Int32.
// It exposes only read operations. Any attempt to modify requires
// creating a mutable copy first via ToMutable().
type ImmutableInt32Int32 struct {
	delegate *Int32Int32
}

// NewImmutableInt32Int32 creates an immutable map from key-value pairs.
func NewImmutableInt32Int32(pairs ...struct {
	Key   int32
	Value int32
}) *ImmutableInt32Int32 {
	m := NewInt32Int32WithCapacity(len(pairs) * 2)
	for _, p := range pairs {
		m.Put(p.Key, p.Value)
	}
	return &ImmutableInt32Int32{delegate: m}
}

// ImmutableInt32Int32From creates an immutable copy of a mutable map.
func ImmutableInt32Int32From(m *Int32Int32) *ImmutableInt32Int32 {
	copy := NewInt32Int32WithCapacity(m.Len() * 2)
	m.ForEach(func(k int32, v int32) {
		copy.Put(k, v)
	})
	return &ImmutableInt32Int32{delegate: copy}
}

// Get returns the value for the given key and true if found.
func (m *ImmutableInt32Int32) Get(key int32) (int32, bool) {
	return m.delegate.Get(key)
}

// GetOrDefault returns the value for the given key if present, or the default value.
func (m *ImmutableInt32Int32) GetOrDefault(key int32, defaultValue int32) int32 {
	return m.delegate.GetOrDefault(key, defaultValue)
}

// ContainsKey returns true if the map contains the given key.
func (m *ImmutableInt32Int32) ContainsKey(key int32) bool {
	return m.delegate.ContainsKey(key)
}

// ContainsValue returns true if the map contains the given value.
func (m *ImmutableInt32Int32) ContainsValue(value int32) bool {
	return m.delegate.ContainsValue(value)
}

// Len returns the number of elements. Use m.Len() == 0 to test for emptiness.
func (m *ImmutableInt32Int32) Len() int {
	return m.delegate.Len()
}

// All returns an iter.Seq2 that yields all key-value pairs.
func (m *ImmutableInt32Int32) All() iter.Seq2[int32, int32] {
	return m.delegate.All()
}

// Keys returns an iter.Seq that yields all keys.
func (m *ImmutableInt32Int32) Keys() iter.Seq[int32] {
	return m.delegate.Keys()
}

// Values returns an iter.Seq that yields all values.
func (m *ImmutableInt32Int32) Values() iter.Seq[int32] {
	return m.delegate.Values()
}

// ForEach calls the given function for each key-value pair.
func (m *ImmutableInt32Int32) ForEach(f func(int32, int32)) {
	m.delegate.ForEach(f)
}

// Select returns a new immutable map with entries that satisfy the predicate.
func (m *ImmutableInt32Int32) Select(predicate func(int32, int32) bool) *ImmutableInt32Int32 {
	return &ImmutableInt32Int32{delegate: m.delegate.Select(predicate)}
}

// Reject returns a new immutable map with entries that do not satisfy the predicate.
func (m *ImmutableInt32Int32) Reject(predicate func(int32, int32) bool) *ImmutableInt32Int32 {
	return &ImmutableInt32Int32{delegate: m.delegate.Reject(predicate)}
}

// AnySatisfy returns true if any entry satisfies the predicate.
func (m *ImmutableInt32Int32) AnySatisfy(predicate func(int32, int32) bool) bool {
	return m.delegate.AnySatisfy(predicate)
}

// AllSatisfy returns true if all entries satisfy the predicate.
func (m *ImmutableInt32Int32) AllSatisfy(predicate func(int32, int32) bool) bool {
	return m.delegate.AllSatisfy(predicate)
}

// NoneSatisfy returns true if no entry satisfies the predicate.
func (m *ImmutableInt32Int32) NoneSatisfy(predicate func(int32, int32) bool) bool {
	return m.delegate.NoneSatisfy(predicate)
}

// KeysToSlice returns all keys as a slice.
func (m *ImmutableInt32Int32) KeysToSlice() []int32 {
	return m.delegate.KeysToSlice()
}

// ValuesToSlice returns all values as a slice.
func (m *ImmutableInt32Int32) ValuesToSlice() []int32 {
	return m.delegate.ValuesToSlice()
}

// String returns a string representation.
func (m *ImmutableInt32Int32) String() string {
	return m.delegate.String()
}

// Equals returns true if the other immutable map has the same entries.
func (m *ImmutableInt32Int32) Equals(other *ImmutableInt32Int32) bool {
	return m.delegate.Equals(other.delegate)
}

// ToMutable returns a mutable copy of this map.
func (m *ImmutableInt32Int32) ToMutable() *Int32Int32 {
	copy := NewInt32Int32WithCapacity(m.Len() * 2)
	m.ForEach(func(k int32, v int32) {
		copy.Put(k, v)
	})
	return copy
}
