// Code generated by internal/codegen; DO NOT EDIT.

package hashmap

import (
	"iter"
)

// ImmutableFloat64Object is an immutable view of a Float64Object.
type ImmutableFloat64Object[V any] struct {
	delegate *Float64Object[V]
}

// NewImmutableFloat64ObjectFrom creates an immutable float64-object map by copying entries from a mutable map.
func NewImmutableFloat64ObjectFrom[V any](m *Float64Object[V]) *ImmutableFloat64Object[V] {
	copy := NewFloat64ObjectWithCapacity[V](m.Len() * 2)
	m.ForEach(func(k float64, v V) {
		copy.Put(k, v)
	})
	return &ImmutableFloat64Object[V]{delegate: copy}
}

// Get returns the value for the given key and true if found.
func (m *ImmutableFloat64Object[V]) Get(key float64) (V, bool) {
	return m.delegate.Get(key)
}

// GetOrDefault returns the value for the given key if present, or the default value.
func (m *ImmutableFloat64Object[V]) GetOrDefault(key float64, defaultValue V) V {
	return m.delegate.GetOrDefault(key, defaultValue)
}

// ContainsKey returns true if the map contains the given key.
func (m *ImmutableFloat64Object[V]) ContainsKey(key float64) bool {
	return m.delegate.ContainsKey(key)
}

// Len returns the number of elements. Use m.Len() == 0 to test for emptiness.
func (m *ImmutableFloat64Object[V]) Len() int {
	return m.delegate.Len()
}

// All returns an iter.Seq2 that yields all key-value pairs.
func (m *ImmutableFloat64Object[V]) All() iter.Seq2[float64, V] {
	return m.delegate.All()
}

// Keys returns an iter.Seq that yields all keys.
func (m *ImmutableFloat64Object[V]) Keys() iter.Seq[float64] {
	return m.delegate.Keys()
}

// Values returns an iter.Seq that yields all values.
func (m *ImmutableFloat64Object[V]) Values() iter.Seq[V] {
	return m.delegate.Values()
}

// ForEach calls the given function for each key-value pair.
func (m *ImmutableFloat64Object[V]) ForEach(f func(float64, V)) {
	m.delegate.ForEach(f)
}

// Select returns a new immutable map with entries satisfying the predicate.
func (m *ImmutableFloat64Object[V]) Select(predicate func(float64, V) bool) *ImmutableFloat64Object[V] {
	return &ImmutableFloat64Object[V]{delegate: m.delegate.Select(predicate)}
}

// Reject returns a new immutable map with entries not satisfying the predicate.
func (m *ImmutableFloat64Object[V]) Reject(predicate func(float64, V) bool) *ImmutableFloat64Object[V] {
	return &ImmutableFloat64Object[V]{delegate: m.delegate.Reject(predicate)}
}

// String returns a string representation.
func (m *ImmutableFloat64Object[V]) String() string {
	return m.delegate.String()
}

// ToMutable returns a mutable copy of this map.
func (m *ImmutableFloat64Object[V]) ToMutable() *Float64Object[V] {
	copy := NewFloat64ObjectWithCapacity[V](m.Len() * 2)
	m.ForEach(func(k float64, v V) {
		copy.Put(k, v)
	})
	return copy
}
