// Code generated by mapdb-codegen. DO NOT EDIT.

package hashmap

import (
	"iter"
)

// ImmutableInt16Float64HashMap is an immutable view of a Int16Float64HashMap.
// It exposes only read operations. Any attempt to modify requires
// creating a mutable copy first via ToMutable().
type ImmutableInt16Float64HashMap struct {
	delegate *Int16Float64HashMap
}

// NewImmutableInt16Float64HashMap creates an immutable map from key-value pairs.
func NewImmutableInt16Float64HashMap(pairs ...struct {
	Key   int16
	Value float64
}) *ImmutableInt16Float64HashMap {
	m := NewInt16Float64HashMapWithCapacity(len(pairs) * 2)
	for _, p := range pairs {
		m.Put(p.Key, p.Value)
	}
	return &ImmutableInt16Float64HashMap{delegate: m}
}

// ImmutableInt16Float64HashMapFrom creates an immutable copy of a mutable map.
func ImmutableInt16Float64HashMapFrom(m *Int16Float64HashMap) *ImmutableInt16Float64HashMap {
	copy := NewInt16Float64HashMapWithCapacity(m.Size() * 2)
	m.ForEach(func(k int16, v float64) {
		copy.Put(k, v)
	})
	return &ImmutableInt16Float64HashMap{delegate: copy}
}

// Get returns the value for the given key and true if found.
func (m *ImmutableInt16Float64HashMap) Get(key int16) (float64, bool) {
	return m.delegate.Get(key)
}

// GetOrDefault returns the value for the given key if present, or the default value.
func (m *ImmutableInt16Float64HashMap) GetOrDefault(key int16, defaultValue float64) float64 {
	return m.delegate.GetOrDefault(key, defaultValue)
}

// ContainsKey returns true if the map contains the given key.
func (m *ImmutableInt16Float64HashMap) ContainsKey(key int16) bool {
	return m.delegate.ContainsKey(key)
}

// ContainsValue returns true if the map contains the given value.
func (m *ImmutableInt16Float64HashMap) ContainsValue(value float64) bool {
	return m.delegate.ContainsValue(value)
}

// Size returns the number of key-value pairs.
func (m *ImmutableInt16Float64HashMap) Size() int {
	return m.delegate.Size()
}

// IsEmpty returns true if the map contains no entries.
func (m *ImmutableInt16Float64HashMap) IsEmpty() bool {
	return m.delegate.IsEmpty()
}

// All returns an iter.Seq2 that yields all key-value pairs.
func (m *ImmutableInt16Float64HashMap) All() iter.Seq2[int16, float64] {
	return m.delegate.All()
}

// Keys returns an iter.Seq that yields all keys.
func (m *ImmutableInt16Float64HashMap) Keys() iter.Seq[int16] {
	return m.delegate.Keys()
}

// Values returns an iter.Seq that yields all values.
func (m *ImmutableInt16Float64HashMap) Values() iter.Seq[float64] {
	return m.delegate.Values()
}

// ForEach calls the given function for each key-value pair.
func (m *ImmutableInt16Float64HashMap) ForEach(f func(int16, float64)) {
	m.delegate.ForEach(f)
}

// Select returns a new immutable map with entries that satisfy the predicate.
func (m *ImmutableInt16Float64HashMap) Select(predicate func(int16, float64) bool) *ImmutableInt16Float64HashMap {
	return &ImmutableInt16Float64HashMap{delegate: m.delegate.Select(predicate)}
}

// Reject returns a new immutable map with entries that do not satisfy the predicate.
func (m *ImmutableInt16Float64HashMap) Reject(predicate func(int16, float64) bool) *ImmutableInt16Float64HashMap {
	return &ImmutableInt16Float64HashMap{delegate: m.delegate.Reject(predicate)}
}

// AnySatisfy returns true if any entry satisfies the predicate.
func (m *ImmutableInt16Float64HashMap) AnySatisfy(predicate func(int16, float64) bool) bool {
	return m.delegate.AnySatisfy(predicate)
}

// AllSatisfy returns true if all entries satisfy the predicate.
func (m *ImmutableInt16Float64HashMap) AllSatisfy(predicate func(int16, float64) bool) bool {
	return m.delegate.AllSatisfy(predicate)
}

// NoneSatisfy returns true if no entry satisfies the predicate.
func (m *ImmutableInt16Float64HashMap) NoneSatisfy(predicate func(int16, float64) bool) bool {
	return m.delegate.NoneSatisfy(predicate)
}

// KeysToSlice returns all keys as a slice.
func (m *ImmutableInt16Float64HashMap) KeysToSlice() []int16 {
	return m.delegate.KeysToSlice()
}

// ValuesToSlice returns all values as a slice.
func (m *ImmutableInt16Float64HashMap) ValuesToSlice() []float64 {
	return m.delegate.ValuesToSlice()
}

// String returns a string representation.
func (m *ImmutableInt16Float64HashMap) String() string {
	return m.delegate.String()
}

// Equals returns true if the other immutable map has the same entries.
func (m *ImmutableInt16Float64HashMap) Equals(other *ImmutableInt16Float64HashMap) bool {
	return m.delegate.Equals(other.delegate)
}

// ToMutable returns a mutable copy of this map.
func (m *ImmutableInt16Float64HashMap) ToMutable() *Int16Float64HashMap {
	copy := NewInt16Float64HashMapWithCapacity(m.Size() * 2)
	m.ForEach(func(k int16, v float64) {
		copy.Put(k, v)
	})
	return copy
}
