// Code generated by internal/codegen; DO NOT EDIT.

package hashmap

import (
	"fmt"
	"iter"
	"strings"

	"github.com/mapdb/mapdb-golang/pump"
)

const (
	int16Int32DefaultCapacity = 16
	// Load factor 3/4 = 0.75, using integer math to avoid float conversion per insert.
)

// int16Int32Entry holds a single slot in the hash map for cache locality.
type int16Int32Entry struct {
	key      int16
	value    int32
	occupied bool
}

// Int16Int32 is an open-addressing hash map with int16 keys and int32 values.
type Int16Int32 struct {
	entries []int16Int32Entry
	size    int
}

// NewInt16Int32 creates a new empty Int16Int32 with default capacity.
func NewInt16Int32() *Int16Int32 {
	return NewInt16Int32WithCapacity(int16Int32DefaultCapacity)
}

// NewInt16Int32WithCapacity creates a new empty Int16Int32 with the given initial capacity.
func NewInt16Int32WithCapacity(capacity int) *Int16Int32 {
	cap := nextPowerOfTwoInt16Int32(capacity)
	return &Int16Int32{
		entries: make([]int16Int32Entry, cap),
		size:    0,
	}
}

// Int16Int32Of creates a new Int16Int32 from key-value pairs.
func Int16Int32Of(pairs ...struct {
	Key   int16
	Value int32
}) *Int16Int32 {
	m := NewInt16Int32WithCapacity(len(pairs) * 2)
	for _, p := range pairs {
		m.Put(p.Key, p.Value)
	}
	return m
}

// Int16Int32BulkLoad builds a Int16Int32 from keys/values in a single pass,
// presizing the table once to fit len(keys) at the 0.75 load factor. keys[i] and
// values[i] form one entry, so the slices must have equal length (a mismatch is a
// programmer error and panics). The input need not be sorted.
//
// On a duplicate key it returns pump.ErrDuplicateKey unless policy is
// pump.IgnoreDuplicates, in which case the first value for a key is kept.
// The result is observably identical to the same entries inserted one-by-one
// with Put into a table of the same final capacity (same probe layout, same
// iteration order). The size is a hint: this constructor may grow if the source
// has more distinct keys than expected — use Int16Int32BulkLoadExact for the
// zero-rehash guarantee.
func Int16Int32BulkLoad(keys []int16, values []int32, policy pump.DuplicatePolicy) (*Int16Int32, error) {
	if len(keys) != len(values) {
		panic("mapdb: Int16Int32BulkLoad: len(keys) != len(values)")
	}
	m := &Int16Int32{entries: make([]int16Int32Entry, Int16Int32bulkCap(len(keys)))}
	if err := m.bulkInsert(keys, values, policy); err != nil {
		return nil, err
	}
	return m, nil
}

// Int16Int32BulkLoadExact is like Int16Int32BulkLoad but guarantees zero
// mid-load rehash: the table is sized for exactly n consumed entries. It returns
// pump.ErrTooManyElements if the source yields more than n entries, even when
// the extra entries are duplicate keys skipped by pump.IgnoreDuplicates. n must
// be non-negative (negative panics).
func Int16Int32BulkLoadExact(keys []int16, values []int32, n int, policy pump.DuplicatePolicy) (*Int16Int32, error) {
	if len(keys) != len(values) {
		panic("mapdb: Int16Int32BulkLoadExact: len(keys) != len(values)")
	}
	if n < 0 {
		panic("mapdb: Int16Int32BulkLoadExact: negative n")
	}
	m := &Int16Int32{entries: make([]int16Int32Entry, Int16Int32bulkCap(n))}
	if len(keys) > n {
		return nil, pump.ErrTooManyElements
	}
	for i := range keys {
		dup, err := m.bulkPut(keys[i], values[i], policy)
		if err != nil {
			return nil, err
		}
		_ = dup
	}
	return m, nil
}

// bulkInsert inserts every (key, value) pair into a presized table, growing if a
// duplicate-free run would cross the load factor (only possible in the hint path).
func (m *Int16Int32) bulkInsert(keys []int16, values []int32, policy pump.DuplicatePolicy) error {
	for i := range keys {
		if m.needsResize() {
			m.resize()
		}
		if _, err := m.bulkPut(keys[i], values[i], policy); err != nil {
			return err
		}
	}
	return nil
}

// bulkPut inserts a single entry via the ordinary probe without a resize check
// (callers guarantee capacity). It applies the duplicate policy and reports
// whether the key was already present.
func (m *Int16Int32) bulkPut(key int16, value int32, policy pump.DuplicatePolicy) (bool, error) {
	mask := len(m.entries) - 1
	idx := int(m.hashKey(key)) & mask
	for {
		if !m.entries[idx].occupied {
			m.entries[idx].key = key
			m.entries[idx].value = value
			m.entries[idx].occupied = true
			m.size++
			return false, nil
		}
		if m.entries[idx].key == key {
			if policy == pump.IgnoreDuplicates {
				return true, nil
			}
			return true, pump.ErrDuplicateKey
		}
		idx = (idx + 1) & mask
	}
}

// Int16Int32bulkCap returns the presized table capacity for n entries that
// avoids any mid-load rehash, using the shared zero-rehash formula. It widens to
// the family's default minimum so very small loads still get a usable table.
func Int16Int32bulkCap(n int) int {
	c := pump.HashCapacityFor(n)
	if c < int16Int32DefaultCapacity {
		return int16Int32DefaultCapacity
	}
	return c
}

// Put inserts or updates a key-value pair. Returns the previous value and true if the key existed.
func (m *Int16Int32) Put(key int16, value int32) (int32, bool) {
	if m.needsResize() {
		m.resize()
	}
	cap := len(m.entries)
	mask := cap - 1
	idx := int(m.hashKey(key)) & mask

	for {
		if !m.entries[idx].occupied {
			m.entries[idx].key = key
			m.entries[idx].value = value
			m.entries[idx].occupied = true
			m.size++
			return 0, false
		}
		if m.entries[idx].key == key {
			old := m.entries[idx].value
			m.entries[idx].value = value
			return old, true
		}
		idx = (idx + 1) & mask
	}
}

// Get returns the value for the given key and true if found, or the zero value and false if not.
func (m *Int16Int32) Get(key int16) (int32, bool) {
	cap := len(m.entries)
	if cap == 0 {
		return 0, false
	}
	mask := cap - 1
	idx := int(m.hashKey(key)) & mask

	for {
		if !m.entries[idx].occupied {
			return 0, false
		}
		if m.entries[idx].key == key {
			return m.entries[idx].value, true
		}
		idx = (idx + 1) & mask
	}
}

// GetOrDefault returns the value for the given key if present, or the default value otherwise.
func (m *Int16Int32) GetOrDefault(key int16, defaultValue int32) int32 {
	if v, ok := m.Get(key); ok {
		return v
	}
	return defaultValue
}

// Remove deletes the entry for the given key. Returns the previous value and true if the key existed.
func (m *Int16Int32) Remove(key int16) (int32, bool) {
	cap := len(m.entries)
	if cap == 0 {
		return 0, false
	}
	mask := cap - 1
	idx := int(m.hashKey(key)) & mask

	for {
		if !m.entries[idx].occupied {
			return 0, false
		}
		if m.entries[idx].key == key {
			old := m.entries[idx].value
			m.entries[idx].occupied = false
			m.entries[idx].key = 0
			m.entries[idx].value = 0
			m.size--
			// Backward-shift deletion: the sibling of linear probing that
			// closes the hole by pulling each subsequent probed-past entry
			// one slot back until we reach an empty slot or an entry whose
			// preferred index equals its current index. This is distinct
			// from Robin Hood hashing (which is an insertion strategy).
			m.rehashFrom(idx, mask)
			return old, true
		}
		idx = (idx + 1) & mask
	}
}

// ContainsKey returns true if the map contains the given key.
func (m *Int16Int32) ContainsKey(key int16) bool {
	_, ok := m.Get(key)
	return ok
}

// ContainsValue returns true if the map contains the given value.
func (m *Int16Int32) ContainsValue(value int32) bool {
	for i := range m.entries {
		if m.entries[i].occupied && m.entries[i].value == value {
			return true
		}
	}
	return false
}

// Len returns the number of elements. Use m.Len() == 0 to test for emptiness.
func (m *Int16Int32) Len() int {
	return m.size
}

// Clear removes all entries from the map.
func (m *Int16Int32) Clear() {
	for i := range m.entries {
		m.entries[i] = int16Int32Entry{}
	}
	m.size = 0
}

// All returns an iter.Seq2 that yields all key-value pairs.
func (m *Int16Int32) All() iter.Seq2[int16, int32] {
	return func(yield func(int16, int32) bool) {
		for i := range m.entries {
			if m.entries[i].occupied {
				if !yield(m.entries[i].key, m.entries[i].value) {
					return
				}
			}
		}
	}
}

// Keys returns an iter.Seq that yields all keys.
func (m *Int16Int32) Keys() iter.Seq[int16] {
	return func(yield func(int16) bool) {
		for i := range m.entries {
			if m.entries[i].occupied {
				if !yield(m.entries[i].key) {
					return
				}
			}
		}
	}
}

// Values returns an iter.Seq that yields all values.
func (m *Int16Int32) Values() iter.Seq[int32] {
	return func(yield func(int32) bool) {
		for i := range m.entries {
			if m.entries[i].occupied {
				if !yield(m.entries[i].value) {
					return
				}
			}
		}
	}
}

// ForEach calls the given function for each key-value pair.
func (m *Int16Int32) ForEach(f func(int16, int32)) {
	for i := range m.entries {
		if m.entries[i].occupied {
			f(m.entries[i].key, m.entries[i].value)
		}
	}
}

// ForEachKey calls the given function for each key.
func (m *Int16Int32) ForEachKey(f func(int16)) {
	for i := range m.entries {
		if m.entries[i].occupied {
			f(m.entries[i].key)
		}
	}
}

// ForEachValue calls the given function for each value.
func (m *Int16Int32) ForEachValue(f func(int32)) {
	for i := range m.entries {
		if m.entries[i].occupied {
			f(m.entries[i].value)
		}
	}
}

// Select returns a new map containing only the key-value pairs that satisfy the predicate.
func (m *Int16Int32) Select(predicate func(int16, int32) bool) *Int16Int32 {
	result := NewInt16Int32()
	for i := range m.entries {
		if m.entries[i].occupied && predicate(m.entries[i].key, m.entries[i].value) {
			result.Put(m.entries[i].key, m.entries[i].value)
		}
	}
	return result
}

// Reject returns a new map containing only the key-value pairs that do not satisfy the predicate.
func (m *Int16Int32) Reject(predicate func(int16, int32) bool) *Int16Int32 {
	result := NewInt16Int32()
	for i := range m.entries {
		if m.entries[i].occupied && !predicate(m.entries[i].key, m.entries[i].value) {
			result.Put(m.entries[i].key, m.entries[i].value)
		}
	}
	return result
}

// Detect returns the first key-value pair that satisfies the predicate, or zero values and false.
func (m *Int16Int32) Detect(predicate func(int16, int32) bool) (int16, int32, bool) {
	for i := range m.entries {
		if m.entries[i].occupied && predicate(m.entries[i].key, m.entries[i].value) {
			return m.entries[i].key, m.entries[i].value, true
		}
	}
	return 0, 0, false
}

// AnySatisfy returns true if any key-value pair satisfies the predicate.
func (m *Int16Int32) AnySatisfy(predicate func(int16, int32) bool) bool {
	for i := range m.entries {
		if m.entries[i].occupied && predicate(m.entries[i].key, m.entries[i].value) {
			return true
		}
	}
	return false
}

// AllSatisfy returns true if all key-value pairs satisfy the predicate.
func (m *Int16Int32) AllSatisfy(predicate func(int16, int32) bool) bool {
	for i := range m.entries {
		if m.entries[i].occupied && !predicate(m.entries[i].key, m.entries[i].value) {
			return false
		}
	}
	return true
}

// NoneSatisfy returns true if no key-value pair satisfies the predicate.
func (m *Int16Int32) NoneSatisfy(predicate func(int16, int32) bool) bool {
	for i := range m.entries {
		if m.entries[i].occupied && predicate(m.entries[i].key, m.entries[i].value) {
			return false
		}
	}
	return true
}

// Count returns the number of key-value pairs that satisfy the predicate.
func (m *Int16Int32) Count(predicate func(int16, int32) bool) int {
	count := 0
	for i := range m.entries {
		if m.entries[i].occupied && predicate(m.entries[i].key, m.entries[i].value) {
			count++
		}
	}
	return count
}

// String returns a string representation of the map.
func (m *Int16Int32) String() string {
	if m.size == 0 {
		return "{}"
	}
	var sb strings.Builder
	sb.WriteString("{")
	first := true
	for i := range m.entries {
		if m.entries[i].occupied {
			if !first {
				sb.WriteString(", ")
			}
			fmt.Fprintf(&sb, "%v: %v", m.entries[i].key, m.entries[i].value)
			first = false
		}
	}
	sb.WriteString("}")
	return sb.String()
}

// Equals returns true if the other map has the same key-value pairs.
func (m *Int16Int32) Equals(other *Int16Int32) bool {
	if m.size != other.size {
		return false
	}
	for i := range m.entries {
		if m.entries[i].occupied {
			v, ok := other.Get(m.entries[i].key)
			if !ok || !(v == m.entries[i].value) {
				return false
			}
		}
	}
	return true
}

// KeysToSlice returns all keys as a slice.
func (m *Int16Int32) KeysToSlice() []int16 {
	result := make([]int16, 0, m.size)
	for i := range m.entries {
		if m.entries[i].occupied {
			result = append(result, m.entries[i].key)
		}
	}
	return result
}

// ValuesToSlice returns all values as a slice.
func (m *Int16Int32) ValuesToSlice() []int32 {
	result := make([]int32, 0, m.size)
	for i := range m.entries {
		if m.entries[i].occupied {
			result = append(result, m.entries[i].value)
		}
	}
	return result
}

// ToImmutable returns an immutable copy of this map.
func (m *Int16Int32) ToImmutable() *ImmutableInt16Int32 {
	return ImmutableInt16Int32From(m)
}

// InjectInto performs a left fold over all key-value pairs.
func (m *Int16Int32) InjectInto(initial int32, f func(int32, int16, int32) int32) int32 {
	result := initial
	for i := range m.entries {
		if m.entries[i].occupied {
			result = f(result, m.entries[i].key, m.entries[i].value)
		}
	}
	return result
}

// AddToValue adds the given amount to the value for the key.
// If the key is not present, inserts it with the given amount as value.
// Returns the new value.
func (m *Int16Int32) AddToValue(key int16, amount int32) int32 {
	if v, ok := m.Get(key); ok {
		newVal := v + amount
		m.Put(key, newVal)
		return newVal
	}
	m.Put(key, amount)
	return amount
}

// UpdateValue updates the value for the key using the function.
// If key is absent, inserts initialValue first then applies the function.
// Returns the new value.
func (m *Int16Int32) UpdateValue(key int16, initialValue int32, f func(int32) int32) int32 {
	if v, ok := m.Get(key); ok {
		newVal := f(v)
		m.Put(key, newVal)
		return newVal
	}
	newVal := f(initialValue)
	m.Put(key, newVal)
	return newVal
}

// PutReturning returns the map after putting the key-value pair (fluent API).
func (m *Int16Int32) PutReturning(key int16, value int32) *Int16Int32 {
	m.Put(key, value)
	return m
}

// RemoveKeyReturning returns the map after removing the key (fluent API).
func (m *Int16Int32) RemoveKeyReturning(key int16) *Int16Int32 {
	m.Remove(key)
	return m
}

// WithoutAllKeys removes all given keys (fluent API).
func (m *Int16Int32) WithoutAllKeys(keys []int16) *Int16Int32 {
	for _, k := range keys {
		m.Remove(k)
	}
	return m
}

// SumOfValues returns the sum of all values.
func (m *Int16Int32) SumOfValues() int32 {
	var sum int32
	for i := range m.entries {
		if m.entries[i].occupied {
			sum += m.entries[i].value
		}
	}
	return sum
}

// Entry returns a handle for in-place check-and-modify operations on the
// given key. The handle is not thread-safe: external synchronisation (the
// SynchronizedInt16Int32 wrapper's Lock / RLock, or your own mutex) is required
// when multiple goroutines share the same underlying map. The name is
// modelled on Rust's std::collections::hash_map::Entry, not on Java's
// ConcurrentMap.compute; there is no internal locking, no CAS, and no
// atomicity guarantee across callback invocation.
func (m *Int16Int32) Entry(key int16) Int16Int32Entry {
	return Int16Int32Entry{m: m, key: key}
}

// Int16Int32Entry provides in-place check-and-modify operations for a single
// key. Not thread-safe — see Int16Int32.Entry.
type Int16Int32Entry struct {
	m   *Int16Int32
	key int16
}

// OrInsert inserts the default value if the key is absent, and returns the current value.
func (e Int16Int32Entry) OrInsert(defaultValue int32) int32 {
	if v, ok := e.m.Get(e.key); ok {
		return v
	}
	e.m.Put(e.key, defaultValue)
	return defaultValue
}

// OrInsertWith inserts the value from the function if the key is absent,
// and returns the current value.
func (e Int16Int32Entry) OrInsertWith(f func() int32) int32 {
	if v, ok := e.m.Get(e.key); ok {
		return v
	}
	val := f()
	e.m.Put(e.key, val)
	return val
}

// AndModify calls f with a pointer to the value if the key is present,
// and returns the entry for fluent chaining. If the key is absent, f is
// not called and the entry is returned unchanged.
//
// CAUTION: f must not call Put / OrInsert / OrInsertWith on the same map.
// Those calls may trigger a resize that reallocates the underlying
// entries slice, leaving f's pointer dangling into the old slice. To
// guard against silent data loss this path panics if it detects a
// resize happened during f — see the post-call check below.
func (e Int16Int32Entry) AndModify(f func(*int32)) Int16Int32Entry {
	cap := len(e.m.entries)
	if cap == 0 {
		return e
	}
	mask := cap - 1
	idx := int(e.m.hashKey(e.key)) & mask
	for {
		if !e.m.entries[idx].occupied {
			return e
		}
		if e.m.entries[idx].key == e.key {
			// Detect backing-slice identity before and after the callback.
			// If the slice header changed (resize) or length changed (rehash),
			// the pointer we passed to f aliased the pre-resize storage and
			// the mutation is lost. Panic rather than silently dropping data.
			prevPtr := &e.m.entries[0]
			prevLen := len(e.m.entries)
			f(&e.m.entries[idx].value)
			if prevLen != len(e.m.entries) || prevPtr != &e.m.entries[0] {
				panic("Int16Int32Entry.AndModify: map was resized during callback — do not mutate the map from within AndModify")
			}
			return e
		}
		idx = (idx + 1) & mask
	}
}

func (m *Int16Int32) hashKey(key int16) uint64 {
	h := uint64(key) * 0x9E3779B97F4A7C15
	return h ^ (h >> 32)
}

func (m *Int16Int32) needsResize() bool {
	return (m.size+1)*4 >= len(m.entries)*3 // 0.75 load factor, integer math
}

func (m *Int16Int32) resize() {
	oldEntries := m.entries
	newCap := len(oldEntries) * 2
	if newCap == 0 {
		newCap = int16Int32DefaultCapacity
	}
	m.entries = make([]int16Int32Entry, newCap)
	m.size = 0

	for i := range oldEntries {
		if oldEntries[i].occupied {
			m.Put(oldEntries[i].key, oldEntries[i].value)
		}
	}
}

// rehashFrom fixes the invariant after a deletion using backward-shift.
func (m *Int16Int32) rehashFrom(deleted int, mask int) {
	c := len(m.entries)
	idx := (deleted + 1) & mask
	for m.entries[idx].occupied {
		ideal := int(m.hashKey(m.entries[idx].key)) & mask
		distCurrent := (idx - ideal + c) & mask
		distGap := (deleted - ideal + c) & mask
		if distCurrent > distGap {
			m.entries[deleted] = m.entries[idx]
			m.entries[idx] = int16Int32Entry{}
			deleted = idx
		}
		idx = (idx + 1) & mask
		if idx == deleted {
			break
		}
	}
}

func nextPowerOfTwoInt16Int32(n int) int {
	if n <= 0 {
		return 16
	}
	n--
	n |= n >> 1
	n |= n >> 2
	n |= n >> 4
	n |= n >> 8
	n |= n >> 16
	n |= n >> 32 // no-op on 32-bit platforms (Go shifts are width-defined), required on 64-bit
	n++
	return n
}
