// Code generated by internal/codegen; DO NOT EDIT.

package hashmap

import (
	"fmt"
	"iter"
	"strings"
)

const (
	int16ObjectDefaultCapacity = 16
)

// Int16Object is an open-addressing hash map with int16 keys and generic values.
// The key type is specialized to avoid boxing overhead. It uses grouped
// Swiss-table probing (SWAR control-byte matcher + triangular probe sequence);
// occupancy is tracked out-of-band by ctrl. Iteration order is unspecified.
type Int16Object[V any] struct {
	ctrl       []uint8
	keys       []int16
	values     []V
	size       int
	growthLeft int
}

// NewInt16Object creates a new empty Int16Object with default capacity.
func NewInt16Object[V any]() *Int16Object[V] {
	return NewInt16ObjectWithCapacity[V](int16ObjectDefaultCapacity)
}

// NewInt16ObjectWithCapacity creates a new empty Int16Object sized to hold at
// least the given number of entries without resizing.
func NewInt16ObjectWithCapacity[V any](capacity int) *Int16Object[V] {
	cap := swissCapacityFor(capacity)
	return &Int16Object[V]{
		ctrl:       newSwissCtrl(cap),
		keys:       make([]int16, cap),
		values:     make([]V, cap),
		size:       0,
		growthLeft: swissMaxLoad(cap),
	}
}

// Put inserts or updates a key-value pair. Returns the previous value and true if the key existed.
func (m *Int16Object[V]) Put(key int16, value V) (V, bool) {
	if m.growthLeft == 0 {
		m.rehashForInsert()
	}
	cap := len(m.keys)
	mask := cap - 1
	hash := m.hashKey(key)
	tag := uint8(hash & 0x7F)
	group := (int(hash>>7) & mask) &^ (swissGroupWidth - 1)
	stride := 0
	firstDeleted := -1

	for {
		g := swissLoadGroup(m.ctrl, group)
		for matches := swissMatchByte(g, tag); matches != 0; matches &= matches - 1 {
			idx := (group + swissLowestLane(matches)) & mask
			if m.keys[idx] == key {
				old := m.values[idx]
				m.values[idx] = value
				return old, true
			}
		}
		if firstDeleted < 0 {
			if d := swissMatchByte(g, swissDeleted); d != 0 {
				firstDeleted = (group + swissLowestLane(d)) & mask
			}
		}
		if empty := swissMatchEmpty(g); empty != 0 {
			idx := (group + swissLowestLane(empty)) & mask
			if firstDeleted >= 0 {
				idx = firstDeleted
			} else {
				m.growthLeft--
			}
			m.keys[idx] = key
			m.values[idx] = value
			swissSetCtrl(m.ctrl, idx, tag, cap)
			m.size++
			var zero V
			return zero, false
		}
		stride += swissGroupWidth
		group = (group + stride) & mask
	}
}

// Get returns the value for the given key and true if found, or the zero value and false if not.
func (m *Int16Object[V]) Get(key int16) (V, bool) {
	if m.size == 0 {
		var zero V
		return zero, false
	}
	idx, ok := m.findIndex(key)
	if !ok {
		var zero V
		return zero, false
	}
	return m.values[idx], true
}

// findIndex returns the bucket index of key and true if present.
func (m *Int16Object[V]) findIndex(key int16) (int, bool) {
	cap := len(m.keys)
	mask := cap - 1
	hash := m.hashKey(key)
	tag := uint8(hash & 0x7F)
	group := (int(hash>>7) & mask) &^ (swissGroupWidth - 1)
	stride := 0
	for {
		g := swissLoadGroup(m.ctrl, group)
		for matches := swissMatchByte(g, tag); matches != 0; matches &= matches - 1 {
			idx := (group + swissLowestLane(matches)) & mask
			if m.keys[idx] == key {
				return idx, true
			}
		}
		if swissMatchEmpty(g) != 0 {
			return 0, false
		}
		stride += swissGroupWidth
		group = (group + stride) & mask
	}
}

// GetOrDefault returns the value for the given key if present, or the default value otherwise.
func (m *Int16Object[V]) GetOrDefault(key int16, defaultValue V) V {
	if v, ok := m.Get(key); ok {
		return v
	}
	return defaultValue
}

// Remove deletes the entry for the given key. Returns the previous value and true if the key existed.
func (m *Int16Object[V]) Remove(key int16) (V, bool) {
	if m.size == 0 {
		var zero V
		return zero, false
	}
	idx, ok := m.findIndex(key)
	if !ok {
		var zero V
		return zero, false
	}
	old := m.values[idx]
	// Always tombstone (DELETED); zero the slot so the GC can reclaim the value.
	swissSetCtrl(m.ctrl, idx, swissDeleted, len(m.keys))
	m.keys[idx] = 0
	var zeroV V
	m.values[idx] = zeroV
	m.size--
	return old, true
}

// ContainsKey returns true if the map contains the given key.
func (m *Int16Object[V]) ContainsKey(key int16) bool {
	_, ok := m.Get(key)
	return ok
}

// Len returns the number of elements. Use m.Len() == 0 to test for emptiness.
func (m *Int16Object[V]) Len() int {
	return m.size
}

// Clear removes all entries from the map, retaining the allocation.
func (m *Int16Object[V]) Clear() {
	var zeroV V
	cap := len(m.keys)
	for i := range m.ctrl {
		m.ctrl[i] = swissEmpty
	}
	for i := range m.keys {
		m.keys[i] = 0
		m.values[i] = zeroV
	}
	m.size = 0
	m.growthLeft = swissMaxLoad(cap)
}

// All returns an iter.Seq2 that yields all key-value pairs.
func (m *Int16Object[V]) All() iter.Seq2[int16, V] {
	return func(yield func(int16, V) bool) {
		for i := range m.keys {
			if m.ctrl[i] <= 0x7F {
				if !yield(m.keys[i], m.values[i]) {
					return
				}
			}
		}
	}
}

// Keys returns an iter.Seq that yields all keys.
func (m *Int16Object[V]) Keys() iter.Seq[int16] {
	return func(yield func(int16) bool) {
		for i := range m.keys {
			if m.ctrl[i] <= 0x7F {
				if !yield(m.keys[i]) {
					return
				}
			}
		}
	}
}

// Values returns an iter.Seq that yields all values.
func (m *Int16Object[V]) Values() iter.Seq[V] {
	return func(yield func(V) bool) {
		for i := range m.keys {
			if m.ctrl[i] <= 0x7F {
				if !yield(m.values[i]) {
					return
				}
			}
		}
	}
}

// ForEach calls the given function for each key-value pair.
func (m *Int16Object[V]) ForEach(f func(int16, V)) {
	for i := range m.keys {
		if m.ctrl[i] <= 0x7F {
			f(m.keys[i], m.values[i])
		}
	}
}

// Select returns a new map containing only entries that satisfy the predicate.
func (m *Int16Object[V]) Select(predicate func(int16, V) bool) *Int16Object[V] {
	result := NewInt16Object[V]()
	for i := range m.keys {
		if m.ctrl[i] <= 0x7F && predicate(m.keys[i], m.values[i]) {
			result.Put(m.keys[i], m.values[i])
		}
	}
	return result
}

// Reject returns a new map containing only entries that do not satisfy the predicate.
func (m *Int16Object[V]) Reject(predicate func(int16, V) bool) *Int16Object[V] {
	result := NewInt16Object[V]()
	for i := range m.keys {
		if m.ctrl[i] <= 0x7F && !predicate(m.keys[i], m.values[i]) {
			result.Put(m.keys[i], m.values[i])
		}
	}
	return result
}

// String returns a string representation of the map.
func (m *Int16Object[V]) String() string {
	if m.size == 0 {
		return "{}"
	}
	var sb strings.Builder
	sb.WriteString("{")
	first := true
	for i := range m.keys {
		if m.ctrl[i] <= 0x7F {
			if !first {
				sb.WriteString(", ")
			}
			fmt.Fprintf(&sb, "%v: %v", m.keys[i], m.values[i])
			first = false
		}
	}
	sb.WriteString("}")
	return sb.String()
}

func (m *Int16Object[V]) hashKey(key int16) uint64 {
	h := uint64(key) * 0x9E3779B97F4A7C15
	return h ^ (h >> 32)
}

// rehashForInsert is called when growthLeft has hit zero and one more entry
// must be inserted: rebuild in place to flush tombstones, or double.
func (m *Int16Object[V]) rehashForInsert() {
	cap := len(m.keys)
	if m.size+1 <= swissMaxLoad(cap) {
		m.rehashTo(cap)
	} else {
		m.rehashTo(cap * 2)
	}
}

func (m *Int16Object[V]) rehashTo(newCap int) {
	oldKeys := m.keys
	oldValues := m.values
	oldCtrl := m.ctrl
	m.ctrl = newSwissCtrl(newCap)
	m.keys = make([]int16, newCap)
	m.values = make([]V, newCap)
	m.size = 0
	m.growthLeft = swissMaxLoad(newCap)
	for i := range oldKeys {
		if oldCtrl[i] <= 0x7F {
			m.insertNoGrow(oldKeys[i], oldValues[i])
		}
	}
}

func (m *Int16Object[V]) insertNoGrow(key int16, value V) {
	cap := len(m.keys)
	mask := cap - 1
	hash := m.hashKey(key)
	tag := uint8(hash & 0x7F)
	group := (int(hash>>7) & mask) &^ (swissGroupWidth - 1)
	stride := 0
	for {
		g := swissLoadGroup(m.ctrl, group)
		if empty := swissMatchEmpty(g); empty != 0 {
			idx := (group + swissLowestLane(empty)) & mask
			m.keys[idx] = key
			m.values[idx] = value
			swissSetCtrl(m.ctrl, idx, tag, cap)
			m.size++
			m.growthLeft--
			return
		}
		stride += swissGroupWidth
		group = (group + stride) & mask
	}
}
