// Code generated by internal/codegen; DO NOT EDIT.

package hashmap

import (
	"fmt"
	"iter"
	"strings"
)

const (
	objectFloat64DefaultCapacity = 16
)

// ObjectFloat64 is an open-addressing hash map with generic comparable keys and float64 values.
// The value type is specialized to avoid boxing overhead. It uses grouped
// Swiss-table probing (SWAR control-byte matcher + triangular probe sequence);
// occupancy is tracked out-of-band by ctrl. Iteration order is unspecified.
type ObjectFloat64[K comparable] struct {
	ctrl       []uint8
	keys       []K
	values     []float64
	size       int
	growthLeft int
}

// NewObjectFloat64 creates a new empty ObjectFloat64 with default capacity.
func NewObjectFloat64[K comparable]() *ObjectFloat64[K] {
	return NewObjectFloat64WithCapacity[K](objectFloat64DefaultCapacity)
}

// NewObjectFloat64WithCapacity creates a new empty ObjectFloat64 sized to hold at
// least the given number of entries without resizing.
func NewObjectFloat64WithCapacity[K comparable](capacity int) *ObjectFloat64[K] {
	cap := swissCapacityFor(capacity)
	return &ObjectFloat64[K]{
		ctrl:       newSwissCtrl(cap),
		keys:       make([]K, cap),
		values:     make([]float64, cap),
		size:       0,
		growthLeft: swissMaxLoad(cap),
	}
}

// Put inserts or updates a key-value pair. Returns the previous value and true if the key existed.
func (m *ObjectFloat64[K]) Put(key K, value float64) (float64, bool) {
	if m.growthLeft == 0 {
		m.rehashForInsert()
	}
	cap := len(m.keys)
	mask := cap - 1
	hash := hashComparable(key)
	tag := uint8(hash & 0x7F)
	group := (int(hash>>7) & mask) &^ (swissGroupWidth - 1)
	stride := 0
	firstDeleted := -1

	for {
		g := swissLoadGroup(m.ctrl, group)
		for matches := swissMatchByte(g, tag); matches != 0; matches &= matches - 1 {
			idx := (group + swissLowestLane(matches)) & mask
			if m.keys[idx] == key {
				old := m.values[idx]
				m.values[idx] = value
				return old, true
			}
		}
		if firstDeleted < 0 {
			if d := swissMatchByte(g, swissDeleted); d != 0 {
				firstDeleted = (group + swissLowestLane(d)) & mask
			}
		}
		if empty := swissMatchEmpty(g); empty != 0 {
			idx := (group + swissLowestLane(empty)) & mask
			if firstDeleted >= 0 {
				idx = firstDeleted
			} else {
				m.growthLeft--
			}
			m.keys[idx] = key
			m.values[idx] = value
			swissSetCtrl(m.ctrl, idx, tag, cap)
			m.size++
			return 0.0, false
		}
		stride += swissGroupWidth
		group = (group + stride) & mask
	}
}

// Get returns the value for the given key and true if found, or the zero value and false if not.
func (m *ObjectFloat64[K]) Get(key K) (float64, bool) {
	if m.size == 0 {
		return 0.0, false
	}
	idx, ok := m.findIndex(key)
	if !ok {
		return 0.0, false
	}
	return m.values[idx], true
}

// findIndex returns the bucket index of key and true if present.
func (m *ObjectFloat64[K]) findIndex(key K) (int, bool) {
	cap := len(m.keys)
	mask := cap - 1
	hash := hashComparable(key)
	tag := uint8(hash & 0x7F)
	group := (int(hash>>7) & mask) &^ (swissGroupWidth - 1)
	stride := 0
	for {
		g := swissLoadGroup(m.ctrl, group)
		for matches := swissMatchByte(g, tag); matches != 0; matches &= matches - 1 {
			idx := (group + swissLowestLane(matches)) & mask
			if m.keys[idx] == key {
				return idx, true
			}
		}
		if swissMatchEmpty(g) != 0 {
			return 0, false
		}
		stride += swissGroupWidth
		group = (group + stride) & mask
	}
}

// GetOrDefault returns the value for the given key if present, or the default value otherwise.
func (m *ObjectFloat64[K]) GetOrDefault(key K, defaultValue float64) float64 {
	if v, ok := m.Get(key); ok {
		return v
	}
	return defaultValue
}

// Remove deletes the entry for the given key. Returns the previous value and true if the key existed.
func (m *ObjectFloat64[K]) Remove(key K) (float64, bool) {
	if m.size == 0 {
		return 0.0, false
	}
	idx, ok := m.findIndex(key)
	if !ok {
		return 0.0, false
	}
	old := m.values[idx]
	// Always tombstone (DELETED); zero the slot so the GC can reclaim the key.
	swissSetCtrl(m.ctrl, idx, swissDeleted, len(m.keys))
	var zeroK K
	m.keys[idx] = zeroK
	m.values[idx] = 0.0
	m.size--
	return old, true
}

// ContainsKey returns true if the map contains the given key.
func (m *ObjectFloat64[K]) ContainsKey(key K) bool {
	_, ok := m.Get(key)
	return ok
}

// Len returns the number of elements. Use m.Len() == 0 to test for emptiness.
func (m *ObjectFloat64[K]) Len() int {
	return m.size
}

// Clear removes all entries from the map, retaining the allocation.
func (m *ObjectFloat64[K]) Clear() {
	var zeroK K
	cap := len(m.keys)
	for i := range m.ctrl {
		m.ctrl[i] = swissEmpty
	}
	for i := range m.keys {
		m.keys[i] = zeroK
		m.values[i] = 0.0
	}
	m.size = 0
	m.growthLeft = swissMaxLoad(cap)
}

// All returns an iter.Seq2 that yields all key-value pairs.
func (m *ObjectFloat64[K]) All() iter.Seq2[K, float64] {
	return func(yield func(K, float64) bool) {
		for i := range m.keys {
			if m.ctrl[i] <= 0x7F {
				if !yield(m.keys[i], m.values[i]) {
					return
				}
			}
		}
	}
}

// Keys returns an iter.Seq that yields all keys.
func (m *ObjectFloat64[K]) Keys() iter.Seq[K] {
	return func(yield func(K) bool) {
		for i := range m.keys {
			if m.ctrl[i] <= 0x7F {
				if !yield(m.keys[i]) {
					return
				}
			}
		}
	}
}

// Values returns an iter.Seq that yields all values.
func (m *ObjectFloat64[K]) Values() iter.Seq[float64] {
	return func(yield func(float64) bool) {
		for i := range m.keys {
			if m.ctrl[i] <= 0x7F {
				if !yield(m.values[i]) {
					return
				}
			}
		}
	}
}

// ForEach calls the given function for each key-value pair.
func (m *ObjectFloat64[K]) ForEach(f func(K, float64)) {
	for i := range m.keys {
		if m.ctrl[i] <= 0x7F {
			f(m.keys[i], m.values[i])
		}
	}
}

// Select returns a new map containing only entries that satisfy the predicate.
func (m *ObjectFloat64[K]) Select(predicate func(K, float64) bool) *ObjectFloat64[K] {
	result := NewObjectFloat64[K]()
	for i := range m.keys {
		if m.ctrl[i] <= 0x7F && predicate(m.keys[i], m.values[i]) {
			result.Put(m.keys[i], m.values[i])
		}
	}
	return result
}

// Reject returns a new map containing only entries that do not satisfy the predicate.
func (m *ObjectFloat64[K]) Reject(predicate func(K, float64) bool) *ObjectFloat64[K] {
	result := NewObjectFloat64[K]()
	for i := range m.keys {
		if m.ctrl[i] <= 0x7F && !predicate(m.keys[i], m.values[i]) {
			result.Put(m.keys[i], m.values[i])
		}
	}
	return result
}

// String returns a string representation of the map.
func (m *ObjectFloat64[K]) String() string {
	if m.size == 0 {
		return "{}"
	}
	var sb strings.Builder
	sb.WriteString("{")
	first := true
	for i := range m.keys {
		if m.ctrl[i] <= 0x7F {
			if !first {
				sb.WriteString(", ")
			}
			fmt.Fprintf(&sb, "%v: %v", m.keys[i], m.values[i])
			first = false
		}
	}
	sb.WriteString("}")
	return sb.String()
}

// rehashForInsert is called when growthLeft has hit zero and one more entry
// must be inserted: rebuild in place to flush tombstones, or double.
func (m *ObjectFloat64[K]) rehashForInsert() {
	cap := len(m.keys)
	if m.size+1 <= swissMaxLoad(cap) {
		m.rehashTo(cap)
	} else {
		m.rehashTo(cap * 2)
	}
}

func (m *ObjectFloat64[K]) rehashTo(newCap int) {
	oldKeys := m.keys
	oldValues := m.values
	oldCtrl := m.ctrl
	m.ctrl = newSwissCtrl(newCap)
	m.keys = make([]K, newCap)
	m.values = make([]float64, newCap)
	m.size = 0
	m.growthLeft = swissMaxLoad(newCap)
	for i := range oldKeys {
		if oldCtrl[i] <= 0x7F {
			m.insertNoGrow(oldKeys[i], oldValues[i])
		}
	}
}

func (m *ObjectFloat64[K]) insertNoGrow(key K, value float64) {
	cap := len(m.keys)
	mask := cap - 1
	hash := hashComparable(key)
	tag := uint8(hash & 0x7F)
	group := (int(hash>>7) & mask) &^ (swissGroupWidth - 1)
	stride := 0
	for {
		g := swissLoadGroup(m.ctrl, group)
		if empty := swissMatchEmpty(g); empty != 0 {
			idx := (group + swissLowestLane(empty)) & mask
			m.keys[idx] = key
			m.values[idx] = value
			swissSetCtrl(m.ctrl, idx, tag, cap)
			m.size++
			m.growthLeft--
			return
		}
		stride += swissGroupWidth
		group = (group + stride) & mask
	}
}
