// Code generated by internal/codegen; DO NOT EDIT.

package hashmap

import (
	"fmt"
	"iter"
	"strings"
)

const (
	objectFloat64DefaultCapacity = 16
	// Load factor 3/4 = 0.75, using integer math to avoid float conversion per insert.
)

// ObjectFloat64 is an open-addressing hash map with generic comparable keys and float64 values.
// The value type is specialized to avoid boxing overhead.
type ObjectFloat64[K comparable] struct {
	keys     []K
	values   []float64
	occupied []bool
	size     int
}

// NewObjectFloat64 creates a new empty ObjectFloat64 with default capacity.
func NewObjectFloat64[K comparable]() *ObjectFloat64[K] {
	return NewObjectFloat64WithCapacity[K](objectFloat64DefaultCapacity)
}

// NewObjectFloat64WithCapacity creates a new empty ObjectFloat64 with the given initial capacity.
func NewObjectFloat64WithCapacity[K comparable](capacity int) *ObjectFloat64[K] {
	cap := nextPowerOfTwoObjectFloat64(capacity)
	return &ObjectFloat64[K]{
		keys:     make([]K, cap),
		values:   make([]float64, cap),
		occupied: make([]bool, cap),
		size:     0,
	}
}

// Put inserts or updates a key-value pair. Returns the previous value and true if the key existed.
func (m *ObjectFloat64[K]) Put(key K, value float64) (float64, bool) {
	if m.needsResize() {
		m.resize()
	}
	cap := len(m.keys)
	mask := cap - 1
	idx := int(hashComparable(key)) & mask

	for {
		if !m.occupied[idx] {
			m.keys[idx] = key
			m.values[idx] = value
			m.occupied[idx] = true
			m.size++
			return 0.0, false
		}
		if m.keys[idx] == key {
			old := m.values[idx]
			m.values[idx] = value
			return old, true
		}
		idx = (idx + 1) & mask
	}
}

// Get returns the value for the given key and true if found, or the zero value and false if not.
func (m *ObjectFloat64[K]) Get(key K) (float64, bool) {
	cap := len(m.keys)
	if cap == 0 {
		return 0.0, false
	}
	mask := cap - 1
	idx := int(hashComparable(key)) & mask

	for {
		if !m.occupied[idx] {
			return 0.0, false
		}
		if m.keys[idx] == key {
			return m.values[idx], true
		}
		idx = (idx + 1) & mask
	}
}

// GetOrDefault returns the value for the given key if present, or the default value otherwise.
func (m *ObjectFloat64[K]) GetOrDefault(key K, defaultValue float64) float64 {
	if v, ok := m.Get(key); ok {
		return v
	}
	return defaultValue
}

// Remove deletes the entry for the given key. Returns the previous value and true if the key existed.
func (m *ObjectFloat64[K]) Remove(key K) (float64, bool) {
	cap := len(m.keys)
	if cap == 0 {
		return 0.0, false
	}
	mask := cap - 1
	idx := int(hashComparable(key)) & mask

	for {
		if !m.occupied[idx] {
			return 0.0, false
		}
		if m.keys[idx] == key {
			old := m.values[idx]
			m.occupied[idx] = false
			var zeroK K
			m.keys[idx] = zeroK
			m.values[idx] = 0.0
			m.size--
			m.rehashFromObjectFloat64(idx, mask)
			return old, true
		}
		idx = (idx + 1) & mask
	}
}

// ContainsKey returns true if the map contains the given key.
func (m *ObjectFloat64[K]) ContainsKey(key K) bool {
	_, ok := m.Get(key)
	return ok
}

// Len returns the number of elements. Use m.Len() == 0 to test for emptiness.
func (m *ObjectFloat64[K]) Len() int {
	return m.size
}

// Clear removes all entries from the map.
func (m *ObjectFloat64[K]) Clear() {
	var zeroK K
	for i := range m.occupied {
		m.occupied[i] = false
		m.keys[i] = zeroK
		m.values[i] = 0.0
	}
	m.size = 0
}

// All returns an iter.Seq2 that yields all key-value pairs.
func (m *ObjectFloat64[K]) All() iter.Seq2[K, float64] {
	return func(yield func(K, float64) bool) {
		for i := range m.occupied {
			if m.occupied[i] {
				if !yield(m.keys[i], m.values[i]) {
					return
				}
			}
		}
	}
}

// Keys returns an iter.Seq that yields all keys.
func (m *ObjectFloat64[K]) Keys() iter.Seq[K] {
	return func(yield func(K) bool) {
		for i := range m.occupied {
			if m.occupied[i] {
				if !yield(m.keys[i]) {
					return
				}
			}
		}
	}
}

// Values returns an iter.Seq that yields all values.
func (m *ObjectFloat64[K]) Values() iter.Seq[float64] {
	return func(yield func(float64) bool) {
		for i := range m.occupied {
			if m.occupied[i] {
				if !yield(m.values[i]) {
					return
				}
			}
		}
	}
}

// ForEach calls the given function for each key-value pair.
func (m *ObjectFloat64[K]) ForEach(f func(K, float64)) {
	for i := range m.occupied {
		if m.occupied[i] {
			f(m.keys[i], m.values[i])
		}
	}
}

// Select returns a new map containing only entries that satisfy the predicate.
func (m *ObjectFloat64[K]) Select(predicate func(K, float64) bool) *ObjectFloat64[K] {
	result := NewObjectFloat64[K]()
	for i := range m.occupied {
		if m.occupied[i] && predicate(m.keys[i], m.values[i]) {
			result.Put(m.keys[i], m.values[i])
		}
	}
	return result
}

// Reject returns a new map containing only entries that do not satisfy the predicate.
func (m *ObjectFloat64[K]) Reject(predicate func(K, float64) bool) *ObjectFloat64[K] {
	result := NewObjectFloat64[K]()
	for i := range m.occupied {
		if m.occupied[i] && !predicate(m.keys[i], m.values[i]) {
			result.Put(m.keys[i], m.values[i])
		}
	}
	return result
}

// String returns a string representation of the map.
func (m *ObjectFloat64[K]) String() string {
	if m.size == 0 {
		return "{}"
	}
	var sb strings.Builder
	sb.WriteString("{")
	first := true
	for i := range m.occupied {
		if m.occupied[i] {
			if !first {
				sb.WriteString(", ")
			}
			fmt.Fprintf(&sb, "%v: %v", m.keys[i], m.values[i])
			first = false
		}
	}
	sb.WriteString("}")
	return sb.String()
}

func (m *ObjectFloat64[K]) needsResize() bool {
	return (m.size+1)*4 >= len(m.keys)*3 // 0.75 load factor, integer math
}

func (m *ObjectFloat64[K]) resize() {
	oldKeys := m.keys
	oldValues := m.values
	oldOccupied := m.occupied
	newCap := len(oldKeys) * 2
	if newCap == 0 {
		newCap = objectFloat64DefaultCapacity
	}
	m.keys = make([]K, newCap)
	m.values = make([]float64, newCap)
	m.occupied = make([]bool, newCap)
	m.size = 0

	for i := range oldOccupied {
		if oldOccupied[i] {
			m.Put(oldKeys[i], oldValues[i])
		}
	}
}

func (m *ObjectFloat64[K]) rehashFromObjectFloat64(deleted int, mask int) {
	idx := (deleted + 1) & mask
	for m.occupied[idx] {
		ideal := int(hashComparable(m.keys[idx])) & mask
		if (idx-ideal+len(m.keys))&mask > (idx-deleted+len(m.keys))&mask {
		} else {
			m.keys[deleted] = m.keys[idx]
			m.values[deleted] = m.values[idx]
			m.occupied[deleted] = true
			m.occupied[idx] = false
			var zeroK K
			m.keys[idx] = zeroK
			m.values[idx] = 0.0
			deleted = idx
		}
		idx = (idx + 1) & mask
	}
}

func nextPowerOfTwoObjectFloat64(n int) int {
	if n <= 0 {
		return 16
	}
	n--
	n |= n >> 1
	n |= n >> 2
	n |= n >> 4
	n |= n >> 8
	n |= n >> 16
	n |= n >> 32 // no-op on 32-bit platforms (Go shifts are width-defined), required on 64-bit
	n++
	return n
}
