// Code generated by mapdb-codegen. DO NOT EDIT.

package hashmap

import (
	"iter"
	"sync"
)

// SynchronizedInt16Int16HashMap is a thread-safe wrapper around Int16Int16HashMap.
// Read methods use RLock, write methods use Lock.
type SynchronizedInt16Int16HashMap struct {
	delegate *Int16Int16HashMap
	mu       sync.RWMutex
}

// NewSynchronizedInt16Int16HashMap wraps a mutable map with synchronization.
func NewSynchronizedInt16Int16HashMap() *SynchronizedInt16Int16HashMap {
	return &SynchronizedInt16Int16HashMap{delegate: NewInt16Int16HashMap()}
}

// NewSynchronizedInt16Int16HashMapFrom wraps an existing map with synchronization.
func NewSynchronizedInt16Int16HashMapFrom(m *Int16Int16HashMap) *SynchronizedInt16Int16HashMap {
	return &SynchronizedInt16Int16HashMap{delegate: m}
}

// Put inserts or updates a key-value pair. Returns the previous value and true if the key existed.
func (m *SynchronizedInt16Int16HashMap) Put(key int16, value int16) (int16, bool) {
	m.mu.Lock()
	defer m.mu.Unlock()
	return m.delegate.Put(key, value)
}

// Get returns the value for the given key and true if found.
func (m *SynchronizedInt16Int16HashMap) Get(key int16) (int16, bool) {
	m.mu.RLock()
	defer m.mu.RUnlock()
	return m.delegate.Get(key)
}

// GetOrDefault returns the value for the given key if present, or the default value.
func (m *SynchronizedInt16Int16HashMap) GetOrDefault(key int16, defaultValue int16) int16 {
	m.mu.RLock()
	defer m.mu.RUnlock()
	return m.delegate.GetOrDefault(key, defaultValue)
}

// Remove deletes the entry for the given key. Returns the previous value and true if found.
func (m *SynchronizedInt16Int16HashMap) Remove(key int16) (int16, bool) {
	m.mu.Lock()
	defer m.mu.Unlock()
	return m.delegate.Remove(key)
}

// ContainsKey returns true if the map contains the given key.
func (m *SynchronizedInt16Int16HashMap) ContainsKey(key int16) bool {
	m.mu.RLock()
	defer m.mu.RUnlock()
	return m.delegate.ContainsKey(key)
}

// Size returns the number of key-value pairs.
func (m *SynchronizedInt16Int16HashMap) Size() int {
	m.mu.RLock()
	defer m.mu.RUnlock()
	return m.delegate.Size()
}

// IsEmpty returns true if the map contains no entries.
func (m *SynchronizedInt16Int16HashMap) IsEmpty() bool {
	m.mu.RLock()
	defer m.mu.RUnlock()
	return m.delegate.IsEmpty()
}

// Clear removes all entries.
func (m *SynchronizedInt16Int16HashMap) Clear() {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.delegate.Clear()
}

// All returns an iter.Seq2 over a snapshot of all key-value pairs.
// The snapshot is taken under lock; iteration is lock-free.
func (m *SynchronizedInt16Int16HashMap) All() iter.Seq2[int16, int16] {
	m.mu.RLock()
	keys := m.delegate.KeysToSlice()
	values := m.delegate.ValuesToSlice()
	m.mu.RUnlock()
	return func(yield func(int16, int16) bool) {
		for i := range keys {
			if !yield(keys[i], values[i]) {
				return
			}
		}
	}
}

// ForEach calls the function for each key-value pair under read lock.
func (m *SynchronizedInt16Int16HashMap) ForEach(f func(int16, int16)) {
	m.mu.RLock()
	defer m.mu.RUnlock()
	m.delegate.ForEach(f)
}

// String returns a string representation.
func (m *SynchronizedInt16Int16HashMap) String() string {
	m.mu.RLock()
	defer m.mu.RUnlock()
	return m.delegate.String()
}
