// Package stack provides LIFO (last-in, first-out) array-backed stacks
// specialised for each supported primitive type (Int8…Int64, Char, Float32,
// Float64), with immutable and synchronized wrappers. Go has no method-level
// generics, so the per-primitive sources are machine-generated rather than
// hand-maintained.
//
// Production sources are regenerated by the in-repo code generator. Run:
//
//	go generate ./stack/...
//
// Test files are hand-maintained.
package stack

//go:generate go run ../internal/codegen stack
