// Code generated by internal/codegen; DO NOT EDIT.

package stack

import (
	"iter"
	"sync"
	"unsafe"

	"github.com/mapdb/mapdb-golang/internal/segment"
)

// SynchronizedInt8 is a thread-safe wrapper around Int8.
//
// Read methods hold an RLock; writes hold a Lock. Callback methods
// (ForEach/Select/…) snapshot under RLock and run the callback
// unlocked so it can safely re-enter the wrapper.
type SynchronizedInt8 struct {
	delegate *Int8
	mu       sync.RWMutex
}

// NewSynchronizedInt8 creates a new thread-safe empty stack.
func NewSynchronizedInt8() *SynchronizedInt8 {
	return &SynchronizedInt8{delegate: NewInt8()}
}

// NewSynchronizedInt8From wraps an existing stack. The
// wrapper takes ownership — do not mutate the delegate directly.
func NewSynchronizedInt8From(s *Int8) *SynchronizedInt8 {
	return &SynchronizedInt8{delegate: s}
}

// snapshot copies the stack contents under RLock. The returned slice
// is ordered the same way the delegate's ToSlice would order it.
func (s *SynchronizedInt8) snapshot() []int8 {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.delegate.ToSlice()
}

// ── writes ────────────────────────────────────────────────────────────

func (s *SynchronizedInt8) Push(value int8) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.delegate.Push(value)
}

func (s *SynchronizedInt8) Pop() (int8, bool) {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.delegate.Pop()
}

func (s *SynchronizedInt8) Clear() {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.delegate.Clear()
}

// ── simple reads ──────────────────────────────────────────────────────

func (s *SynchronizedInt8) Peek() (int8, bool) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.delegate.Peek()
}

func (s *SynchronizedInt8) PeekAt(index int) int8 {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.delegate.PeekAt(index)
}

// Len returns the number of elements. Use s.Len() == 0 to test for emptiness.
func (s *SynchronizedInt8) Len() int {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.delegate.Len()
}

func (s *SynchronizedInt8) Contains(value int8) bool {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.delegate.Contains(value)
}

func (s *SynchronizedInt8) ToSlice() []int8 {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.delegate.ToSlice()
}

func (s *SynchronizedInt8) String() string {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.delegate.String()
}

// ── iteration ────────────────────────────────────────────────────────

func (s *SynchronizedInt8) All() iter.Seq[int8] {
	snapshot := s.snapshot()
	return func(yield func(int8) bool) {
		for _, v := range snapshot {
			if !yield(v) {
				return
			}
		}
	}
}

// Segments cuts a point-in-time snapshot into up to n balanced, contiguous,
// non-overlapping views covering it exactly once, satisfying par.Segmenter[int8].
// The snapshot is taken once under lock; the views iterate it lock-free — the
// same snapshot contract as All.
func (s *SynchronizedInt8) Segments(n int) []iter.Seq[int8] {
	return segment.Split(s.snapshot(), n)
}

// ── functional over snapshot ──────────────────────────────────────────

func (s *SynchronizedInt8) ForEach(f func(int8)) {
	for _, v := range s.snapshot() {
		f(v)
	}
}

func (s *SynchronizedInt8) AnySatisfy(predicate func(int8) bool) bool {
	for _, v := range s.snapshot() {
		if predicate(v) {
			return true
		}
	}
	return false
}

func (s *SynchronizedInt8) AllSatisfy(predicate func(int8) bool) bool {
	for _, v := range s.snapshot() {
		if !predicate(v) {
			return false
		}
	}
	return true
}

func (s *SynchronizedInt8) NoneSatisfy(predicate func(int8) bool) bool {
	for _, v := range s.snapshot() {
		if predicate(v) {
			return false
		}
	}
	return true
}

func (s *SynchronizedInt8) Count(predicate func(int8) bool) int {
	n := 0
	for _, v := range s.snapshot() {
		if predicate(v) {
			n++
		}
	}
	return n
}

func (s *SynchronizedInt8) Detect(predicate func(int8) bool) (int8, bool) {
	for _, v := range s.snapshot() {
		if predicate(v) {
			return v, true
		}
	}
	var zero int8
	return zero, false
}

func (s *SynchronizedInt8) InjectInto(initial int8, f func(int8, int8) int8) int8 {
	acc := initial
	for _, v := range s.snapshot() {
		acc = f(acc, v)
	}
	return acc
}

// ── functional that return a new stack ───────────────────────────────

func (s *SynchronizedInt8) Select(predicate func(int8) bool) *Int8 {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.delegate.Select(predicate)
}

func (s *SynchronizedInt8) Reject(predicate func(int8) bool) *Int8 {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.delegate.Reject(predicate)
}

// ── fluent mutators ───────────────────────────────────────────────────

func (s *SynchronizedInt8) AddReturning(value int8) *SynchronizedInt8 {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.delegate.AddReturning(value)
	return s
}

func (s *SynchronizedInt8) AddAllReturning(values ...int8) *SynchronizedInt8 {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.delegate.AddAllReturning(values...)
	return s
}

// ── conversions & equals ──────────────────────────────────────────────

func (s *SynchronizedInt8) ToImmutable() *ImmutableInt8 {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.delegate.ToImmutable()
}

// Equals compares by contents. Locks are acquired in pointer-address
// order to prevent A.Equals(B) / B.Equals(A) deadlocks.
func (s *SynchronizedInt8) Equals(other *SynchronizedInt8) bool {
	if s == other {
		s.mu.RLock()
		defer s.mu.RUnlock()
		return s.delegate.Equals(other.delegate)
	}
	first, second := s, other
	if uintptr(unsafe.Pointer(s)) > uintptr(unsafe.Pointer(other)) {
		first, second = other, s
	}
	first.mu.RLock()
	defer first.mu.RUnlock()
	second.mu.RLock()
	defer second.mu.RUnlock()
	return s.delegate.Equals(other.delegate)
}
