// Code generated by internal/codegen; DO NOT EDIT.

package priorityqueue

import (
	"fmt"
	"strings"
)

// Int8 is a min-heap priority queue of int8 values.
// O(log n) Push/Pop, O(1) Peek.
type Int8 struct {
	items []int8
}

// NewInt8 creates a new empty Int8.
func NewInt8() *Int8 {
	return &Int8{items: make([]int8, 0, 16)}
}

// Int8Of creates a new Int8 and heapifies the given values in O(n).
func Int8Of(values ...int8) *Int8 {
	q := &Int8{items: make([]int8, len(values))}
	copy(q.items, values)
	if len(q.items) > 1 {
		for i := len(q.items)/2 - 1; i >= 0; i-- {
			q.siftDown(i)
		}
	}
	return q
}

// Push adds a value to the heap. O(log n).
func (q *Int8) Push(value int8) {
	q.items = append(q.items, value)
	q.siftUp(len(q.items) - 1)
}

// Pop removes and returns the smallest element. The bool is false if the
// queue is empty. O(log n).
func (q *Int8) Pop() (int8, bool) {
	if len(q.items) == 0 {
		return 0, false
	}
	top := q.items[0]
	last := len(q.items) - 1
	q.items[0] = q.items[last]
	q.items = q.items[:last]
	if len(q.items) > 0 {
		q.siftDown(0)
	}
	return top, true
}

// Peek returns the smallest element without removing it. The bool is false
// if the queue is empty.
func (q *Int8) Peek() (int8, bool) {
	if len(q.items) == 0 {
		return 0, false
	}
	return q.items[0], true
}

// Len returns the number of elements in the queue. Use q.Len() == 0 to test
// for emptiness.
func (q *Int8) Len() int { return len(q.items) }

// Clear removes all elements.
func (q *Int8) Clear() { q.items = q.items[:0] }

// Contains returns true if the queue contains the given value. O(n).
func (q *Int8) Contains(value int8) bool {
	for _, v := range q.items {
		if v == value {
			return true
		}
	}
	return false
}

// ToSlice returns a copy of the internal heap array (NOT sorted).
func (q *Int8) ToSlice() []int8 {
	out := make([]int8, len(q.items))
	copy(out, q.items)
	return out
}

// DrainSorted pops all elements in ascending order, consuming the queue.
func (q *Int8) DrainSorted() []int8 {
	out := make([]int8, 0, len(q.items))
	for len(q.items) > 0 {
		v, _ := q.Pop()
		out = append(out, v)
	}
	return out
}

// String returns a string representation in heap-array order.
func (q *Int8) String() string {
	if len(q.items) == 0 {
		return "[]"
	}
	var sb strings.Builder
	sb.WriteString("[")
	for i, v := range q.items {
		if i > 0 {
			sb.WriteString(", ")
		}
		fmt.Fprintf(&sb, "%v", v)
	}
	sb.WriteString("]")
	return sb.String()
}

func (q *Int8) less(a, b int) bool {
	return q.items[a] < q.items[b]
}

func (q *Int8) siftUp(start int) {
	i := start
	for i > 0 {
		parent := (i - 1) / 2
		if q.less(i, parent) {
			q.items[i], q.items[parent] = q.items[parent], q.items[i]
			i = parent
		} else {
			break
		}
	}
}

func (q *Int8) siftDown(start int) {
	i := start
	n := len(q.items)
	for {
		left := 2*i + 1
		if left >= n {
			break
		}
		right := left + 1
		best := left
		if right < n && q.less(right, left) {
			best = right
		}
		if q.less(best, i) {
			q.items[best], q.items[i] = q.items[i], q.items[best]
			i = best
		} else {
			break
		}
	}
}
