// Code generated by internal/codegen; DO NOT EDIT.

package priorityqueue

import (
	"iter"
	"sync"

	"github.com/mapdb/mapdb-golang/internal/segment"
)

// SynchronizedFloat32 is a thread-safe wrapper around Float32.
type SynchronizedFloat32 struct {
	delegate *Float32
	mu       sync.RWMutex
}

// NewSynchronizedFloat32 creates a new thread-safe empty priority queue.
func NewSynchronizedFloat32() *SynchronizedFloat32 {
	return &SynchronizedFloat32{delegate: NewFloat32()}
}

func (q *SynchronizedFloat32) Push(value float32) {
	q.mu.Lock()
	defer q.mu.Unlock()
	q.delegate.Push(value)
}

func (q *SynchronizedFloat32) Pop() (float32, bool) {
	q.mu.Lock()
	defer q.mu.Unlock()
	return q.delegate.Pop()
}

func (q *SynchronizedFloat32) Peek() (float32, bool) {
	q.mu.RLock()
	defer q.mu.RUnlock()
	return q.delegate.Peek()
}

func (q *SynchronizedFloat32) Len() int {
	q.mu.RLock()
	defer q.mu.RUnlock()
	return q.delegate.Len()
}

func (q *SynchronizedFloat32) Clear() {
	q.mu.Lock()
	defer q.mu.Unlock()
	q.delegate.Clear()
}

func (q *SynchronizedFloat32) Contains(value float32) bool {
	q.mu.RLock()
	defer q.mu.RUnlock()
	return q.delegate.Contains(value)
}

func (q *SynchronizedFloat32) ToSlice() []float32 {
	q.mu.RLock()
	defer q.mu.RUnlock()
	return q.delegate.ToSlice()
}

// All returns an iter.Seq over a point-in-time snapshot in heap-array order (see
// Float32.All). The snapshot is taken once under RLock; iteration is lock-free.
func (q *SynchronizedFloat32) All() iter.Seq[float32] {
	snapshot := q.ToSlice()
	return func(yield func(float32) bool) {
		for _, v := range snapshot {
			if !yield(v) {
				return
			}
		}
	}
}

// Segments cuts a heap-array snapshot into up to n balanced, contiguous,
// non-overlapping views covering it exactly once, satisfying par.Segmenter[float32].
// The snapshot (ToSlice) is taken once under RLock; the views iterate it lock-free.
func (q *SynchronizedFloat32) Segments(n int) []iter.Seq[float32] {
	return segment.Split(q.ToSlice(), n)
}

func (q *SynchronizedFloat32) DrainSorted() []float32 {
	q.mu.Lock()
	defer q.mu.Unlock()
	return q.delegate.DrainSorted()
}

func (q *SynchronizedFloat32) String() string {
	q.mu.RLock()
	defer q.mu.RUnlock()
	return q.delegate.String()
}
