// Code generated by mapdb-codegen. DO NOT EDIT.

package bag

import (
	"iter"
	"sync"
)

// SynchronizedFloat32HashBag is a thread-safe wrapper around Float32HashBag.
type SynchronizedFloat32HashBag struct {
	delegate *Float32HashBag
	mu       sync.RWMutex
}

// NewSynchronizedFloat32HashBag creates a new thread-safe empty bag.
func NewSynchronizedFloat32HashBag() *SynchronizedFloat32HashBag {
	return &SynchronizedFloat32HashBag{delegate: NewFloat32HashBag()}
}

func (b *SynchronizedFloat32HashBag) Add(value float32) {
	b.mu.Lock()
	defer b.mu.Unlock()
	b.delegate.Add(value)
}

func (b *SynchronizedFloat32HashBag) AddOccurrences(value float32, occurrences int) int {
	b.mu.Lock()
	defer b.mu.Unlock()
	return b.delegate.AddOccurrences(value, occurrences)
}

func (b *SynchronizedFloat32HashBag) Remove(value float32) bool {
	b.mu.Lock()
	defer b.mu.Unlock()
	return b.delegate.Remove(value)
}

func (b *SynchronizedFloat32HashBag) OccurrencesOf(value float32) int {
	b.mu.RLock()
	defer b.mu.RUnlock()
	return b.delegate.OccurrencesOf(value)
}

func (b *SynchronizedFloat32HashBag) Contains(value float32) bool {
	b.mu.RLock()
	defer b.mu.RUnlock()
	return b.delegate.Contains(value)
}

func (b *SynchronizedFloat32HashBag) Size() int {
	b.mu.RLock()
	defer b.mu.RUnlock()
	return b.delegate.Size()
}

func (b *SynchronizedFloat32HashBag) SizeDistinct() int {
	b.mu.RLock()
	defer b.mu.RUnlock()
	return b.delegate.SizeDistinct()
}

func (b *SynchronizedFloat32HashBag) IsEmpty() bool {
	b.mu.RLock()
	defer b.mu.RUnlock()
	return b.delegate.IsEmpty()
}

func (b *SynchronizedFloat32HashBag) Clear() {
	b.mu.Lock()
	defer b.mu.Unlock()
	b.delegate.Clear()
}

func (b *SynchronizedFloat32HashBag) All() iter.Seq[float32] {
	b.mu.RLock()
	snapshot := b.delegate.ToSlice()
	b.mu.RUnlock()
	return func(yield func(float32) bool) {
		for _, v := range snapshot {
			if !yield(v) {
				return
			}
		}
	}
}

func (b *SynchronizedFloat32HashBag) String() string {
	b.mu.RLock()
	defer b.mu.RUnlock()
	return b.delegate.String()
}
