// Code generated by mapdb-codegen. DO NOT EDIT.

package collection

import "iter"

// Int16CharMapIterable is the read-only interface for any map from int16 to uint16.
// Satisfied by: Int16CharHashMap, Int16CharTreeMap, Int16CharSentinelHashMap,
// ImmutableInt16CharHashMap.
type Int16CharMapIterable interface {
	// Get returns the value for the key, or (zero, false) if not found.
	Get(key int16) (uint16, bool)

	// GetOrDefault returns the value for the key, or defaultValue if not found.
	GetOrDefault(key int16, defaultValue uint16) uint16

	// ContainsKey returns true if the map contains the given key.
	ContainsKey(key int16) bool

	// Size returns the number of key-value pairs.
	Size() int

	// IsEmpty returns true if the map contains no entries.
	IsEmpty() bool

	// All returns an iter.Seq2 that yields all key-value pairs.
	All() iter.Seq2[int16, uint16]

	// Keys returns an iter.Seq that yields all keys.
	Keys() iter.Seq[int16]

	// Values returns an iter.Seq that yields all values.
	Values() iter.Seq[uint16]

	// ForEach calls the given function for each key-value pair.
	ForEach(f func(int16, uint16))

	// AnySatisfy returns true if any entry satisfies the predicate.
	AnySatisfy(predicate func(int16, uint16) bool) bool

	// AllSatisfy returns true if all entries satisfy the predicate.
	AllSatisfy(predicate func(int16, uint16) bool) bool

	// NoneSatisfy returns true if no entry satisfies the predicate.
	NoneSatisfy(predicate func(int16, uint16) bool) bool

	// String returns a string representation.
	String() string
}

// Int16CharMutableMap extends Int16CharMapIterable with mutation operations.
// Satisfied by: Int16CharHashMap, Int16CharTreeMap, Int16CharSentinelHashMap.
type Int16CharMutableMap interface {
	Int16CharMapIterable

	// Put adds or updates a key-value pair. Returns (old value, existed).
	Put(key int16, value uint16) (uint16, bool)

	// Remove removes the key. Returns (old value, existed).
	Remove(key int16) (uint16, bool)

	// Clear removes all entries.
	Clear()
}
