// Code generated by mapdb-codegen. DO NOT EDIT.

package arraylist

import (
	"fmt"
	"iter"
	"sort"
	"strings"
)

// Float64ArrayList is a resizable array-backed list of float64 values.
type Float64ArrayList struct {
	items []float64
	size  int
}

// NewFloat64ArrayList creates a new empty Float64ArrayList.
func NewFloat64ArrayList() *Float64ArrayList {
	return &Float64ArrayList{
		items: make([]float64, 0, 16),
		size:  0,
	}
}

// NewFloat64ArrayListWithCapacity creates a new empty Float64ArrayList with the given initial capacity.
func NewFloat64ArrayListWithCapacity(capacity int) *Float64ArrayList {
	return &Float64ArrayList{
		items: make([]float64, 0, capacity),
		size:  0,
	}
}

// Float64ArrayListOf creates a new Float64ArrayList from the given values.
func Float64ArrayListOf(values ...float64) *Float64ArrayList {
	l := &Float64ArrayList{
		items: make([]float64, len(values)),
		size:  len(values),
	}
	copy(l.items, values)
	return l
}

// Add appends a value to the end of the list.
func (l *Float64ArrayList) Add(value float64) {
	if l.size == cap(l.items) {
		l.grow()
	}
	l.items = l.items[:l.size+1]
	l.items[l.size] = value
	l.size++
}

// AddAll appends all values to the end of the list.
func (l *Float64ArrayList) AddAll(values ...float64) {
	for _, v := range values {
		l.Add(v)
	}
}

// Get returns the value at the given index, or an error if the index is out of bounds.
func (l *Float64ArrayList) Get(index int) (float64, error) {
	if index < 0 || index >= l.size {
		return 0.0, fmt.Errorf("Float64ArrayList: index out of bounds: %d (size %d)", index, l.size)
	}
	return l.items[index], nil
}

// Set sets the value at the given index, returning the previous value.
// Returns an error if the index is out of bounds.
func (l *Float64ArrayList) Set(index int, value float64) (float64, error) {
	if index < 0 || index >= l.size {
		return 0.0, fmt.Errorf("Float64ArrayList: index out of bounds: %d (size %d)", index, l.size)
	}
	old := l.items[index]
	l.items[index] = value
	return old, nil
}

// RemoveAtIndex removes the value at the given index and returns it.
// Returns an error if the index is out of bounds.
func (l *Float64ArrayList) RemoveAtIndex(index int) (float64, error) {
	if index < 0 || index >= l.size {
		return 0.0, fmt.Errorf("Float64ArrayList: index out of bounds: %d (size %d)", index, l.size)
	}
	old := l.items[index]
	copy(l.items[index:], l.items[index+1:l.size])
	l.size--
	l.items = l.items[:l.size]
	return old, nil
}

// Remove removes the first occurrence of the value. Returns true if found and removed.
func (l *Float64ArrayList) Remove(value float64) bool {
	for i := 0; i < l.size; i++ {
		if l.items[i] == value {
			_, _ = l.RemoveAtIndex(i)
			return true
		}
	}
	return false
}

// Contains returns true if the list contains the given value.
func (l *Float64ArrayList) Contains(value float64) bool {
	for i := 0; i < l.size; i++ {
		if l.items[i] == value {
			return true
		}
	}
	return false
}

// IndexOf returns the index of the first occurrence of the value, or -1 if not found.
func (l *Float64ArrayList) IndexOf(value float64) int {
	for i := 0; i < l.size; i++ {
		if l.items[i] == value {
			return i
		}
	}
	return -1
}

// Size returns the number of elements in the list.
func (l *Float64ArrayList) Size() int {
	return l.size
}

// IsEmpty returns true if the list contains no elements.
func (l *Float64ArrayList) IsEmpty() bool {
	return l.size == 0
}

// Clear removes all elements from the list.
func (l *Float64ArrayList) Clear() {
	l.items = l.items[:0]
	l.size = 0
}

// All returns an iter.Seq that yields all elements in order.
func (l *Float64ArrayList) All() iter.Seq[float64] {
	return func(yield func(float64) bool) {
		for i := 0; i < l.size; i++ {
			if !yield(l.items[i]) {
				return
			}
		}
	}
}

// AllWithIndex returns an iter.Seq2 that yields (index, value) pairs.
func (l *Float64ArrayList) AllWithIndex() iter.Seq2[int, float64] {
	return func(yield func(int, float64) bool) {
		for i := 0; i < l.size; i++ {
			if !yield(i, l.items[i]) {
				return
			}
		}
	}
}

// ForEach calls the given function for each element.
func (l *Float64ArrayList) ForEach(f func(float64)) {
	for i := 0; i < l.size; i++ {
		f(l.items[i])
	}
}

// ForEachWithIndex calls the given function with each element and its index.
func (l *Float64ArrayList) ForEachWithIndex(f func(float64, int)) {
	for i := 0; i < l.size; i++ {
		f(l.items[i], i)
	}
}

// Select returns a new list containing only elements that satisfy the predicate.
func (l *Float64ArrayList) Select(predicate func(float64) bool) *Float64ArrayList {
	result := NewFloat64ArrayList()
	for i := 0; i < l.size; i++ {
		if predicate(l.items[i]) {
			result.Add(l.items[i])
		}
	}
	return result
}

// Reject returns a new list containing only elements that do not satisfy the predicate.
func (l *Float64ArrayList) Reject(predicate func(float64) bool) *Float64ArrayList {
	result := NewFloat64ArrayList()
	for i := 0; i < l.size; i++ {
		if !predicate(l.items[i]) {
			result.Add(l.items[i])
		}
	}
	return result
}

// Detect returns the first element that satisfies the predicate, or the zero value and false.
func (l *Float64ArrayList) Detect(predicate func(float64) bool) (float64, bool) {
	for i := 0; i < l.size; i++ {
		if predicate(l.items[i]) {
			return l.items[i], true
		}
	}
	return 0.0, false
}

// AnySatisfy returns true if any element satisfies the predicate.
func (l *Float64ArrayList) AnySatisfy(predicate func(float64) bool) bool {
	for i := 0; i < l.size; i++ {
		if predicate(l.items[i]) {
			return true
		}
	}
	return false
}

// AllSatisfy returns true if all elements satisfy the predicate.
func (l *Float64ArrayList) AllSatisfy(predicate func(float64) bool) bool {
	for i := 0; i < l.size; i++ {
		if !predicate(l.items[i]) {
			return false
		}
	}
	return true
}

// NoneSatisfy returns true if no element satisfies the predicate.
func (l *Float64ArrayList) NoneSatisfy(predicate func(float64) bool) bool {
	for i := 0; i < l.size; i++ {
		if predicate(l.items[i]) {
			return false
		}
	}
	return true
}

// Count returns the number of elements that satisfy the predicate.
func (l *Float64ArrayList) Count(predicate func(float64) bool) int {
	count := 0
	for i := 0; i < l.size; i++ {
		if predicate(l.items[i]) {
			count++
		}
	}
	return count
}

// InjectInto performs a left fold over the list.
func (l *Float64ArrayList) InjectInto(initial float64, f func(float64, float64) float64) float64 {
	result := initial
	for i := 0; i < l.size; i++ {
		result = f(result, l.items[i])
	}
	return result
}

// Sum returns the sum of all elements.
func (l *Float64ArrayList) Sum() float64 {
	var sum float64
	for i := 0; i < l.size; i++ {
		sum += l.items[i]
	}
	return sum
}

// Min returns the minimum element, or the zero value and false if empty.
func (l *Float64ArrayList) Min() (float64, bool) {
	if l.size == 0 {
		return 0.0, false
	}
	min := l.items[0]
	for i := 1; i < l.size; i++ {
		if l.items[i] < min {
			min = l.items[i]
		}
	}
	return min, true
}

// Max returns the maximum element, or the zero value and false if empty.
func (l *Float64ArrayList) Max() (float64, bool) {
	if l.size == 0 {
		return 0.0, false
	}
	max := l.items[0]
	for i := 1; i < l.size; i++ {
		if l.items[i] > max {
			max = l.items[i]
		}
	}
	return max, true
}

// Sort sorts the list in ascending order.
func (l *Float64ArrayList) Sort() {
	sort.Slice(l.items[:l.size], func(i, j int) bool {
		return l.items[i] < l.items[j]
	})
}

// SortWithComparator sorts the list using the given comparison function.
func (l *Float64ArrayList) SortWithComparator(less func(float64, float64) bool) {
	sort.Slice(l.items[:l.size], func(i, j int) bool {
		return less(l.items[i], l.items[j])
	})
}

// BinarySearch searches for a value in a sorted list. Returns the index and true if found.
func (l *Float64ArrayList) BinarySearch(value float64) (int, bool) {
	lo, hi := 0, l.size-1
	for lo <= hi {
		mid := lo + (hi-lo)/2
		if l.items[mid] == value {
			return mid, true
		}
		if l.items[mid] < value {
			lo = mid + 1
		} else {
			hi = mid - 1
		}
	}
	return lo, false
}

// Reversed returns a new list with elements in reverse order.
func (l *Float64ArrayList) Reversed() *Float64ArrayList {
	result := NewFloat64ArrayListWithCapacity(l.size)
	for i := l.size - 1; i >= 0; i-- {
		result.Add(l.items[i])
	}
	return result
}

// Distinct returns a new list with duplicate elements removed (preserving first occurrence order).
func (l *Float64ArrayList) Distinct() *Float64ArrayList {
	seen := make(map[float64]struct{})
	result := NewFloat64ArrayList()
	for i := 0; i < l.size; i++ {
		if _, ok := seen[l.items[i]]; !ok {
			seen[l.items[i]] = struct{}{}
			result.Add(l.items[i])
		}
	}
	return result
}

// ToSlice returns a copy of the list elements as a slice.
func (l *Float64ArrayList) ToSlice() []float64 {
	result := make([]float64, l.size)
	copy(result, l.items[:l.size])
	return result
}

// With returns the list after adding the value (fluent API).
func (l *Float64ArrayList) With(value float64) *Float64ArrayList {
	l.Add(value)
	return l
}

// Without returns the list after removing the first occurrence of value (fluent API).
func (l *Float64ArrayList) Without(value float64) *Float64ArrayList {
	l.Remove(value)
	return l
}

// String returns a string representation of the list.
func (l *Float64ArrayList) String() string {
	if l.size == 0 {
		return "[]"
	}
	var sb strings.Builder
	sb.WriteString("[")
	for i := 0; i < l.size; i++ {
		if i > 0 {
			sb.WriteString(", ")
		}
		fmt.Fprintf(&sb, "%v", l.items[i])
	}
	sb.WriteString("]")
	return sb.String()
}

// Equals returns true if the other list has the same elements in the same order.
func (l *Float64ArrayList) Equals(other *Float64ArrayList) bool {
	if l.size != other.size {
		return false
	}
	for i := 0; i < l.size; i++ {
		if l.items[i] != other.items[i] {
			return false
		}
	}
	return true
}

// WithAll returns the list after adding all values (fluent API).
func (l *Float64ArrayList) WithAll(values ...float64) *Float64ArrayList {
	l.AddAll(values...)
	return l
}

// WithoutAll removes all occurrences of the given values.
func (l *Float64ArrayList) WithoutAll(values ...float64) *Float64ArrayList {
	remove := make(map[float64]struct{})
	for _, v := range values {
		remove[v] = struct{}{}
	}
	result := NewFloat64ArrayList()
	for i := 0; i < l.size; i++ {
		if _, skip := remove[l.items[i]]; !skip {
			result.Add(l.items[i])
		}
	}
	l.items = result.items
	l.size = result.size
	return l
}

// ToImmutable returns an immutable copy of this list.
func (l *Float64ArrayList) ToImmutable() *ImmutableFloat64ArrayList {
	return ImmutableFloat64ArrayListFrom(l)
}

func (l *Float64ArrayList) grow() {
	newCap := cap(l.items) * 2
	if newCap == 0 {
		newCap = 16
	}
	newItems := make([]float64, l.size, newCap)
	copy(newItems, l.items[:l.size])
	l.items = newItems
}
