// Code generated by internal/codegen; DO NOT EDIT.

package arraylist

import (
	"iter"
	"sync"
	"unsafe"
)

// SynchronizedChar is a thread-safe wrapper around Char.
//
// Read methods hold an RLock; writes hold a Lock. Methods that take
// a caller-supplied function (Select, ForEach, InjectInto, …) snapshot
// the backing slice under RLock and release it before invoking the
// callback, so the callback is free to call back into the wrapper
// without deadlocking.
//
// Methods that return a fresh collection (Select, Reject, Distinct,
// Reversed) return an unwrapped *Char: the caller owns it and
// is free to add their own synchronisation if they need it.
type SynchronizedChar struct {
	delegate *Char
	mu       sync.RWMutex
}

// NewSynchronizedChar creates a new thread-safe empty list.
func NewSynchronizedChar() *SynchronizedChar {
	return &SynchronizedChar{delegate: NewChar()}
}

// NewSynchronizedCharWithCapacity creates a new thread-safe
// empty list with the given initial capacity.
func NewSynchronizedCharWithCapacity(capacity int) *SynchronizedChar {
	return &SynchronizedChar{delegate: NewCharWithCapacity(capacity)}
}

// NewSynchronizedCharFrom wraps an existing list. The
// wrapper takes ownership of the delegate — callers must not continue
// to mutate it directly without locking.
func NewSynchronizedCharFrom(l *Char) *SynchronizedChar {
	return &SynchronizedChar{delegate: l}
}

// SynchronizedCharOf creates a new thread-safe list
// containing the given values in order.
func SynchronizedCharOf(values ...uint16) *SynchronizedChar {
	return &SynchronizedChar{delegate: CharOf(values...)}
}

// snapshot returns a defensive copy of the backing slice taken under
// RLock. Callers iterate the snapshot without holding the lock.
func (l *SynchronizedChar) snapshot() []uint16 {
	l.mu.RLock()
	defer l.mu.RUnlock()
	return l.delegate.ToSlice()
}

// ── simple writes ─────────────────────────────────────────────────────

func (l *SynchronizedChar) Add(value uint16) {
	l.mu.Lock()
	defer l.mu.Unlock()
	l.delegate.Add(value)
}

func (l *SynchronizedChar) AddAll(values ...uint16) {
	l.mu.Lock()
	defer l.mu.Unlock()
	l.delegate.AddAll(values...)
}

func (l *SynchronizedChar) AddAtIndex(index int, value uint16) {
	l.mu.Lock()
	defer l.mu.Unlock()
	l.delegate.AddAtIndex(index, value)
}

func (l *SynchronizedChar) Set(index int, value uint16) uint16 {
	l.mu.Lock()
	defer l.mu.Unlock()
	return l.delegate.Set(index, value)
}

func (l *SynchronizedChar) RemoveAtIndex(index int) uint16 {
	l.mu.Lock()
	defer l.mu.Unlock()
	return l.delegate.RemoveAtIndex(index)
}

func (l *SynchronizedChar) Remove(value uint16) bool {
	l.mu.Lock()
	defer l.mu.Unlock()
	return l.delegate.Remove(value)
}

func (l *SynchronizedChar) Clear() {
	l.mu.Lock()
	defer l.mu.Unlock()
	l.delegate.Clear()
}

// Sort sorts the backing list in place. Holds the write lock for the
// duration; do not call back into this wrapper from a custom comparator.
func (l *SynchronizedChar) Sort() {
	l.mu.Lock()
	defer l.mu.Unlock()
	l.delegate.Sort()
}

// SortWithComparator sorts using the given less function, under the
// write lock. The comparator must not call back into this wrapper.
func (l *SynchronizedChar) SortWithComparator(less func(uint16, uint16) bool) {
	l.mu.Lock()
	defer l.mu.Unlock()
	l.delegate.SortWithComparator(less)
}

// ── simple reads ──────────────────────────────────────────────────────

func (l *SynchronizedChar) Get(index int) uint16 {
	l.mu.RLock()
	defer l.mu.RUnlock()
	return l.delegate.Get(index)
}

func (l *SynchronizedChar) Contains(value uint16) bool {
	l.mu.RLock()
	defer l.mu.RUnlock()
	return l.delegate.Contains(value)
}

func (l *SynchronizedChar) IndexOf(value uint16) int {
	l.mu.RLock()
	defer l.mu.RUnlock()
	return l.delegate.IndexOf(value)
}

func (l *SynchronizedChar) Len() int {
	l.mu.RLock()
	defer l.mu.RUnlock()
	return l.delegate.Len()
}

func (l *SynchronizedChar) ToSlice() []uint16 {
	l.mu.RLock()
	defer l.mu.RUnlock()
	return l.delegate.ToSlice()
}

func (l *SynchronizedChar) String() string {
	l.mu.RLock()
	defer l.mu.RUnlock()
	return l.delegate.String()
}

func (l *SynchronizedChar) Sum() int64 {
	l.mu.RLock()
	defer l.mu.RUnlock()
	return l.delegate.Sum()
}

func (l *SynchronizedChar) Min() (uint16, bool) {
	l.mu.RLock()
	defer l.mu.RUnlock()
	return l.delegate.Min()
}

func (l *SynchronizedChar) Max() (uint16, bool) {
	l.mu.RLock()
	defer l.mu.RUnlock()
	return l.delegate.Max()
}

// BinarySearch requires the delegate to be sorted. Callers must
// ensure that (e.g. by calling Sort() beforehand, both happening
// before any concurrent Add).
func (l *SynchronizedChar) BinarySearch(value uint16) (int, bool) {
	l.mu.RLock()
	defer l.mu.RUnlock()
	return l.delegate.BinarySearch(value)
}

// Equals returns true if the other list has the same elements in the
// same order. Both wrappers are locked under RLock to prevent torn
// reads; locks are acquired in pointer-address order so two goroutines
// calling A.Equals(B) and B.Equals(A) concurrently cannot deadlock.
func (l *SynchronizedChar) Equals(other *SynchronizedChar) bool {
	if l == other {
		l.mu.RLock()
		defer l.mu.RUnlock()
		return l.delegate.Equals(other.delegate)
	}
	first, second := l, other
	if uintptr(unsafe.Pointer(l)) > uintptr(unsafe.Pointer(other)) {
		first, second = other, l
	}
	first.mu.RLock()
	defer first.mu.RUnlock()
	second.mu.RLock()
	defer second.mu.RUnlock()
	return l.delegate.Equals(other.delegate)
}

// ── iteration (snapshot-based) ────────────────────────────────────────

// All returns an iter.Seq over a snapshot. Iteration is lock-free.
func (l *SynchronizedChar) All() iter.Seq[uint16] {
	snapshot := l.snapshot()
	return func(yield func(uint16) bool) {
		for _, v := range snapshot {
			if !yield(v) {
				return
			}
		}
	}
}

// AllWithIndex returns an iter.Seq2 over a snapshot. Iteration is lock-free.
func (l *SynchronizedChar) AllWithIndex() iter.Seq2[int, uint16] {
	snapshot := l.snapshot()
	return func(yield func(int, uint16) bool) {
		for i, v := range snapshot {
			if !yield(i, v) {
				return
			}
		}
	}
}

// ── functional over snapshot ──────────────────────────────────────────

func (l *SynchronizedChar) ForEach(f func(uint16)) {
	for _, v := range l.snapshot() {
		f(v)
	}
}

func (l *SynchronizedChar) ForEachWithIndex(f func(uint16, int)) {
	for i, v := range l.snapshot() {
		f(v, i)
	}
}

func (l *SynchronizedChar) AnySatisfy(predicate func(uint16) bool) bool {
	for _, v := range l.snapshot() {
		if predicate(v) {
			return true
		}
	}
	return false
}

func (l *SynchronizedChar) AllSatisfy(predicate func(uint16) bool) bool {
	for _, v := range l.snapshot() {
		if !predicate(v) {
			return false
		}
	}
	return true
}

func (l *SynchronizedChar) NoneSatisfy(predicate func(uint16) bool) bool {
	for _, v := range l.snapshot() {
		if predicate(v) {
			return false
		}
	}
	return true
}

func (l *SynchronizedChar) Count(predicate func(uint16) bool) int {
	n := 0
	for _, v := range l.snapshot() {
		if predicate(v) {
			n++
		}
	}
	return n
}

func (l *SynchronizedChar) Detect(predicate func(uint16) bool) (uint16, bool) {
	for _, v := range l.snapshot() {
		if predicate(v) {
			return v, true
		}
	}
	var zero uint16
	return zero, false
}

func (l *SynchronizedChar) InjectInto(initial uint16, f func(uint16, uint16) uint16) uint16 {
	acc := initial
	for _, v := range l.snapshot() {
		acc = f(acc, v)
	}
	return acc
}

// ── functional that return a new list ─────────────────────────────────

// Select returns a new (unsynchronized) list of elements satisfying the predicate.
func (l *SynchronizedChar) Select(predicate func(uint16) bool) *Char {
	snapshot := l.snapshot()
	result := NewChar()
	for _, v := range snapshot {
		if predicate(v) {
			result.Add(v)
		}
	}
	return result
}

// Reject returns a new (unsynchronized) list of elements not satisfying the predicate.
func (l *SynchronizedChar) Reject(predicate func(uint16) bool) *Char {
	snapshot := l.snapshot()
	result := NewChar()
	for _, v := range snapshot {
		if !predicate(v) {
			result.Add(v)
		}
	}
	return result
}

// Distinct returns a new (unsynchronized) list with duplicates removed,
// order preserved.
func (l *SynchronizedChar) Distinct() *Char {
	l.mu.RLock()
	defer l.mu.RUnlock()
	return l.delegate.Distinct()
}

// Reversed returns a new (unsynchronized) list in reverse order.
func (l *SynchronizedChar) Reversed() *Char {
	l.mu.RLock()
	defer l.mu.RUnlock()
	return l.delegate.Reversed()
}

// ── fluent mutators ───────────────────────────────────────────────────
// All return the wrapper so chained calls stay thread-safe.

func (l *SynchronizedChar) AddReturning(value uint16) *SynchronizedChar {
	l.mu.Lock()
	defer l.mu.Unlock()
	l.delegate.AddReturning(value)
	return l
}

func (l *SynchronizedChar) AddAllReturning(values ...uint16) *SynchronizedChar {
	l.mu.Lock()
	defer l.mu.Unlock()
	l.delegate.AddAllReturning(values...)
	return l
}

func (l *SynchronizedChar) RemoveReturning(value uint16) *SynchronizedChar {
	l.mu.Lock()
	defer l.mu.Unlock()
	l.delegate.RemoveReturning(value)
	return l
}

func (l *SynchronizedChar) RemoveAllReturning(values ...uint16) *SynchronizedChar {
	l.mu.Lock()
	defer l.mu.Unlock()
	l.delegate.RemoveAllReturning(values...)
	return l
}

// ── conversions ───────────────────────────────────────────────────────

// ToImmutable returns an immutable copy of the underlying list taken
// while holding the read lock. The returned value is independent of
// this wrapper.
func (l *SynchronizedChar) ToImmutable() *ImmutableChar {
	l.mu.RLock()
	defer l.mu.RUnlock()
	return l.delegate.ToImmutable()
}
