// Code generated by mapdb-codegen. DO NOT EDIT.

package arraylist

import (
	"iter"
	"sync"
)

// SynchronizedInt64ArrayList is a thread-safe wrapper around Int64ArrayList.
type SynchronizedInt64ArrayList struct {
	delegate *Int64ArrayList
	mu       sync.RWMutex
}

// NewSynchronizedInt64ArrayList creates a new thread-safe empty list.
func NewSynchronizedInt64ArrayList() *SynchronizedInt64ArrayList {
	return &SynchronizedInt64ArrayList{delegate: NewInt64ArrayList()}
}

// NewSynchronizedInt64ArrayListFrom wraps an existing list.
func NewSynchronizedInt64ArrayListFrom(l *Int64ArrayList) *SynchronizedInt64ArrayList {
	return &SynchronizedInt64ArrayList{delegate: l}
}

func (l *SynchronizedInt64ArrayList) Add(value int64) {
	l.mu.Lock()
	defer l.mu.Unlock()
	l.delegate.Add(value)
}

func (l *SynchronizedInt64ArrayList) Get(index int) (int64, error) {
	l.mu.RLock()
	defer l.mu.RUnlock()
	return l.delegate.Get(index)
}

func (l *SynchronizedInt64ArrayList) Set(index int, value int64) (int64, error) {
	l.mu.Lock()
	defer l.mu.Unlock()
	return l.delegate.Set(index, value)
}

func (l *SynchronizedInt64ArrayList) RemoveAtIndex(index int) (int64, error) {
	l.mu.Lock()
	defer l.mu.Unlock()
	return l.delegate.RemoveAtIndex(index)
}

func (l *SynchronizedInt64ArrayList) Contains(value int64) bool {
	l.mu.RLock()
	defer l.mu.RUnlock()
	return l.delegate.Contains(value)
}

func (l *SynchronizedInt64ArrayList) Size() int {
	l.mu.RLock()
	defer l.mu.RUnlock()
	return l.delegate.Size()
}

func (l *SynchronizedInt64ArrayList) IsEmpty() bool {
	l.mu.RLock()
	defer l.mu.RUnlock()
	return l.delegate.IsEmpty()
}

func (l *SynchronizedInt64ArrayList) Clear() {
	l.mu.Lock()
	defer l.mu.Unlock()
	l.delegate.Clear()
}

// All returns an iter.Seq over a snapshot. Iteration is lock-free.
func (l *SynchronizedInt64ArrayList) All() iter.Seq[int64] {
	l.mu.RLock()
	snapshot := l.delegate.ToSlice()
	l.mu.RUnlock()
	return func(yield func(int64) bool) {
		for _, v := range snapshot {
			if !yield(v) {
				return
			}
		}
	}
}

func (l *SynchronizedInt64ArrayList) ToSlice() []int64 {
	l.mu.RLock()
	defer l.mu.RUnlock()
	return l.delegate.ToSlice()
}

func (l *SynchronizedInt64ArrayList) String() string {
	l.mu.RLock()
	defer l.mu.RUnlock()
	return l.delegate.String()
}
