// Code generated by internal/codegen; DO NOT EDIT.

package priority_queue

import (
	"sync"
)

// SynchronizedFloat64PriorityQueue is a thread-safe wrapper around Float64PriorityQueue.
type SynchronizedFloat64PriorityQueue struct {
	delegate *Float64PriorityQueue
	mu       sync.RWMutex
}

// NewSynchronizedFloat64PriorityQueue creates a new thread-safe empty priority queue.
func NewSynchronizedFloat64PriorityQueue() *SynchronizedFloat64PriorityQueue {
	return &SynchronizedFloat64PriorityQueue{delegate: NewFloat64PriorityQueue()}
}

func (q *SynchronizedFloat64PriorityQueue) Push(value float64) {
	q.mu.Lock()
	defer q.mu.Unlock()
	q.delegate.Push(value)
}

func (q *SynchronizedFloat64PriorityQueue) Pop() (float64, error) {
	q.mu.Lock()
	defer q.mu.Unlock()
	return q.delegate.Pop()
}

func (q *SynchronizedFloat64PriorityQueue) Peek() (float64, error) {
	q.mu.RLock()
	defer q.mu.RUnlock()
	return q.delegate.Peek()
}

func (q *SynchronizedFloat64PriorityQueue) Size() int {
	q.mu.RLock()
	defer q.mu.RUnlock()
	return q.delegate.Size()
}

// Len returns the number of elements. It is an alias for Size, matching
// Go convention (sort.Interface, container/list, bytes.Buffer).
func (q *SynchronizedFloat64PriorityQueue) Len() int { return q.Size() }

func (q *SynchronizedFloat64PriorityQueue) IsEmpty() bool {
	q.mu.RLock()
	defer q.mu.RUnlock()
	return q.delegate.IsEmpty()
}

func (q *SynchronizedFloat64PriorityQueue) Clear() {
	q.mu.Lock()
	defer q.mu.Unlock()
	q.delegate.Clear()
}

func (q *SynchronizedFloat64PriorityQueue) Contains(value float64) bool {
	q.mu.RLock()
	defer q.mu.RUnlock()
	return q.delegate.Contains(value)
}

func (q *SynchronizedFloat64PriorityQueue) ToSlice() []float64 {
	q.mu.RLock()
	defer q.mu.RUnlock()
	return q.delegate.ToSlice()
}

func (q *SynchronizedFloat64PriorityQueue) DrainSorted() []float64 {
	q.mu.Lock()
	defer q.mu.Unlock()
	return q.delegate.DrainSorted()
}

func (q *SynchronizedFloat64PriorityQueue) String() string {
	q.mu.RLock()
	defer q.mu.RUnlock()
	return q.delegate.String()
}
