// Package deque provides double-ended queues backed by power-of-two ring
// buffers, specialised for each supported primitive type (Int8…Int64, Char,
// Float32, Float64), with synchronized wrappers. Go has no method-level
// generics, so the per-primitive sources are machine-generated rather than
// hand-maintained.
//
// Production sources are regenerated by the in-repo code generator. Run:
//
//	go generate ./deque/...
//
// Test files are hand-maintained.
package deque

//go:generate go run ../internal/codegen deque
