// Code generated by mapdb-codegen. DO NOT EDIT.

package deque

import (
	"testing"
)

func TestInt16ArrayDeque_Generated_AddLastRemoveFirst(t *testing.T) {
	d := NewInt16ArrayDeque()
	d.AddLast(1)
	d.AddLast(2)
	d.AddLast(3)
	if d.Size() != 3 {
		t.Errorf("Size = %d, want 3", d.Size())
	}
	v0, err := d.RemoveFirst()
	if err != nil || !(v0 == 1) {
		t.Errorf("RemoveFirst = %v, err=%v, want 1", v0, err)
	}
	v1, err := d.RemoveFirst()
	if err != nil || !(v1 == 2) {
		t.Errorf("RemoveFirst = %v, err=%v, want 2", v1, err)
	}
	v2, err := d.RemoveFirst()
	if err != nil || !(v2 == 3) {
		t.Errorf("RemoveFirst = %v, err=%v, want 3", v2, err)
	}
	if !d.IsEmpty() {
		t.Errorf("IsEmpty = false, want true")
	}
}

func TestInt16ArrayDeque_Generated_AddFirstRemoveLast(t *testing.T) {
	d := NewInt16ArrayDeque()
	d.AddFirst(1)
	d.AddFirst(2)
	d.AddFirst(3)
	got, err := d.PeekFirst()
	if err != nil || !(got == 3) {
		t.Errorf("PeekFirst = %v, err=%v, want 3", got, err)
	}
	got, err = d.PeekLast()
	if err != nil || !(got == 1) {
		t.Errorf("PeekLast = %v, err=%v, want 1", got, err)
	}
	got, _ = d.RemoveLast()
	if !(got == 1) {
		t.Errorf("RemoveLast = %v, want 1", got)
	}
	got, _ = d.RemoveLast()
	if !(got == 2) {
		t.Errorf("RemoveLast = %v, want 2", got)
	}
	got, _ = d.RemoveLast()
	if !(got == 3) {
		t.Errorf("RemoveLast = %v, want 3", got)
	}
}

func TestInt16ArrayDeque_Generated_RemoveEmpty(t *testing.T) {
	d := NewInt16ArrayDeque()
	if _, err := d.RemoveFirst(); err == nil {
		t.Errorf("RemoveFirst on empty: want error")
	}
	if _, err := d.RemoveLast(); err == nil {
		t.Errorf("RemoveLast on empty: want error")
	}
	if _, err := d.PeekFirst(); err == nil {
		t.Errorf("PeekFirst on empty: want error")
	}
	if _, err := d.PeekLast(); err == nil {
		t.Errorf("PeekLast on empty: want error")
	}
}

func TestInt16ArrayDeque_Generated_MixedOps(t *testing.T) {
	d := NewInt16ArrayDeque()
	d.AddLast(2)
	d.AddFirst(1)
	d.AddLast(3)
	got, _ := d.RemoveFirst()
	if !(got == 1) {
		t.Errorf("RemoveFirst after mixed ops = %v, want 1", got)
	}
	got, _ = d.RemoveLast()
	if !(got == 3) {
		t.Errorf("RemoveLast after mixed ops = %v, want 3", got)
	}
	got, _ = d.RemoveFirst()
	if !(got == 2) {
		t.Errorf("RemoveFirst last = %v, want 2", got)
	}
}

func TestInt16ArrayDeque_Generated_ContainsAndClear(t *testing.T) {
	d := NewInt16ArrayDeque()
	d.AddLast(1)
	d.AddLast(2)
	if !d.Contains(1) {
		t.Errorf("Contains(1) = false, want true")
	}
	d.Clear()
	if !d.IsEmpty() {
		t.Errorf("IsEmpty after Clear = false, want true")
	}
}

func TestInt16ArrayDeque_Generated_ToSlice(t *testing.T) {
	d := Int16ArrayDequeOf(1, 2, 3)
	out := d.ToSlice()
	if len(out) != 3 {
		t.Errorf("ToSlice len = %d, want 3", len(out))
	}
}

func TestInt16ArrayDeque_Generated_Equals(t *testing.T) {
	a := Int16ArrayDequeOf(1, 2)
	b := Int16ArrayDequeOf(1, 2)
	if !a.Equals(b) {
		t.Errorf("Equals = false, want true")
	}
}

func TestInt16ArrayDeque_Generated_String(t *testing.T) {
	d := NewInt16ArrayDeque()
	d.AddLast(1)
	if d.String() == "" {
		t.Errorf("String is empty")
	}
}
