// Code generated by mapdb-codegen. DO NOT EDIT.

package deque

import (
	"fmt"
	"strings"
)

// Int32ArrayDeque is a double-ended queue of int32 values, backed by a slice.
// Back ops (AddLast, RemoveLast) are O(1) amortized; front ops
// (AddFirst, RemoveFirst) are O(n) because they shift.
type Int32ArrayDeque struct {
	items []int32
}

// NewInt32ArrayDeque creates a new empty Int32ArrayDeque.
func NewInt32ArrayDeque() *Int32ArrayDeque {
	return &Int32ArrayDeque{items: make([]int32, 0, 16)}
}

// Int32ArrayDequeOf creates a new Int32ArrayDeque from the given values in
// front-to-back order.
func Int32ArrayDequeOf(values ...int32) *Int32ArrayDeque {
	d := &Int32ArrayDeque{items: make([]int32, len(values))}
	copy(d.items, values)
	return d
}

// AddFirst prepends a value to the front of the deque. O(n).
func (d *Int32ArrayDeque) AddFirst(value int32) {
	d.items = append(d.items, 0)
	copy(d.items[1:], d.items[:len(d.items)-1])
	d.items[0] = value
}

// AddLast appends a value to the back of the deque. O(1) amortized.
func (d *Int32ArrayDeque) AddLast(value int32) {
	d.items = append(d.items, value)
}

// RemoveFirst removes and returns the front element, or an error if empty. O(n).
func (d *Int32ArrayDeque) RemoveFirst() (int32, error) {
	if len(d.items) == 0 {
		return 0, fmt.Errorf("Int32ArrayDeque: RemoveFirst on empty deque")
	}
	v := d.items[0]
	copy(d.items, d.items[1:])
	d.items = d.items[:len(d.items)-1]
	return v, nil
}

// RemoveLast removes and returns the back element, or an error if empty. O(1).
func (d *Int32ArrayDeque) RemoveLast() (int32, error) {
	if len(d.items) == 0 {
		return 0, fmt.Errorf("Int32ArrayDeque: RemoveLast on empty deque")
	}
	last := d.items[len(d.items)-1]
	d.items = d.items[:len(d.items)-1]
	return last, nil
}

// PeekFirst returns the front element without removing it, or an error if empty.
func (d *Int32ArrayDeque) PeekFirst() (int32, error) {
	if len(d.items) == 0 {
		return 0, fmt.Errorf("Int32ArrayDeque: PeekFirst on empty deque")
	}
	return d.items[0], nil
}

// PeekLast returns the back element without removing it, or an error if empty.
func (d *Int32ArrayDeque) PeekLast() (int32, error) {
	if len(d.items) == 0 {
		return 0, fmt.Errorf("Int32ArrayDeque: PeekLast on empty deque")
	}
	return d.items[len(d.items)-1], nil
}

// Size returns the number of elements in the deque.
func (d *Int32ArrayDeque) Size() int { return len(d.items) }

// IsEmpty returns true if the deque contains no elements.
func (d *Int32ArrayDeque) IsEmpty() bool { return len(d.items) == 0 }

// Clear removes all elements.
func (d *Int32ArrayDeque) Clear() { d.items = d.items[:0] }

// Contains returns true if the deque contains the given value.
func (d *Int32ArrayDeque) Contains(value int32) bool {
	for _, v := range d.items {
		if v == value {
			return true
		}
	}
	return false
}

// ForEach applies the function to each element from front to back.
func (d *Int32ArrayDeque) ForEach(f func(int32)) {
	for _, v := range d.items {
		f(v)
	}
}

// AnySatisfy returns true if any element satisfies the predicate.
func (d *Int32ArrayDeque) AnySatisfy(predicate func(int32) bool) bool {
	for _, v := range d.items {
		if predicate(v) {
			return true
		}
	}
	return false
}

// AllSatisfy returns true if every element satisfies the predicate.
func (d *Int32ArrayDeque) AllSatisfy(predicate func(int32) bool) bool {
	for _, v := range d.items {
		if !predicate(v) {
			return false
		}
	}
	return true
}

// ToSlice returns a copy of the elements in front-to-back order.
func (d *Int32ArrayDeque) ToSlice() []int32 {
	out := make([]int32, len(d.items))
	copy(out, d.items)
	return out
}

// Equals returns true if the other deque has the same elements in the same order.
func (d *Int32ArrayDeque) Equals(other *Int32ArrayDeque) bool {
	if len(d.items) != len(other.items) {
		return false
	}
	for i, v := range d.items {
		if !(v == other.items[i]) {
			return false
		}
	}
	return true
}

// String returns a string representation in front-to-back order.
func (d *Int32ArrayDeque) String() string {
	if len(d.items) == 0 {
		return "[]"
	}
	var sb strings.Builder
	sb.WriteString("[")
	for i, v := range d.items {
		if i > 0 {
			sb.WriteString(", ")
		}
		fmt.Fprintf(&sb, "%v", v)
	}
	sb.WriteString("]")
	return sb.String()
}
