// Code generated by internal/codegen; DO NOT EDIT.

package deque

import (
	"fmt"
	"iter"
	"strings"

	"github.com/mapdb/mapdb-golang/internal/segment"
)

// Int8 is a double-ended queue of int8 values, backed by a
// power-of-two ring buffer. AddFirst, AddLast, RemoveFirst, RemoveLast,
// PeekFirst and PeekLast are all O(1) amortised.
//
// The public API is intentionally identical to the slice-backed deque
// that preceded it: callers that iterate via ToSlice or ForEach see
// elements in logical front-to-back order regardless of where head
// happens to sit in the underlying buffer.
type Int8 struct {
	items []int8 // len == capacity, always a power of two; indexed modulo cap
	head  int    // index of the front element (0 when empty)
	size  int    // number of logical elements
}

// initialDequeCap is the smallest power-of-two capacity allocated for a
// freshly constructed deque. It matches the previous slice-backed
// implementation's starting capacity so behaviour around the first few
// reallocations stays comparable.
const initialInt8DequeCap = 16

// ceilPow2 rounds n up to the next power of two, with a floor of
// initialInt8DequeCap. Used when sizing the buffer to fit a
// caller-supplied slice in Int8Of.
func ceilPow2Int8Deque(n int) int {
	cap := initialInt8DequeCap
	for cap < n {
		cap <<= 1
	}
	return cap
}

// NewInt8 creates a new empty Int8.
func NewInt8() *Int8 {
	return &Int8{items: make([]int8, initialInt8DequeCap)}
}

// NewInt8WithCapacity creates a new empty Int8 whose backing ring
// buffer is sized (rounded up to a power of two) to hold capacity elements
// without growing. It is the deque's bulk-load convenience: presize once, then
// push the prepared values in a single O(n) pass. A negative capacity panics.
func NewInt8WithCapacity(capacity int) *Int8 {
	if capacity < 0 {
		panic("mapdb: NewInt8WithCapacity: negative capacity")
	}
	return &Int8{items: make([]int8, ceilPow2Int8Deque(capacity))}
}

// Int8Of creates a new Int8 from the given values in
// front-to-back order.
func Int8Of(values ...int8) *Int8 {
	d := &Int8{
		items: make([]int8, ceilPow2Int8Deque(len(values))),
		size:  len(values),
	}
	copy(d.items, values)
	return d
}

// grow doubles the backing buffer and repacks elements so that head is at 0.
// Called lazily when size would exceed capacity.
func (d *Int8) grow() {
	newCap := len(d.items) * 2
	if newCap == 0 {
		newCap = initialInt8DequeCap
	}
	next := make([]int8, newCap)
	// Copy tail segment (head..end), then wrap segment (0..head) so that
	// logical order is preserved and head resets to 0.
	n := copy(next, d.items[d.head:])
	copy(next[n:], d.items[:d.head])
	d.items = next
	d.head = 0
}

// AddFirst prepends a value to the front of the deque. O(1) amortised.
func (d *Int8) AddFirst(value int8) {
	if d.size == len(d.items) {
		d.grow()
	}
	mask := len(d.items) - 1
	d.head = (d.head - 1) & mask
	d.items[d.head] = value
	d.size++
}

// AddLast appends a value to the back of the deque. O(1) amortised.
func (d *Int8) AddLast(value int8) {
	if d.size == len(d.items) {
		d.grow()
	}
	mask := len(d.items) - 1
	d.items[(d.head+d.size)&mask] = value
	d.size++
}

// RemoveFirst removes and returns the front element. The bool is false if empty. O(1).
func (d *Int8) RemoveFirst() (int8, bool) {
	if d.size == 0 {
		return 0, false
	}
	mask := len(d.items) - 1
	v := d.items[d.head]
	d.items[d.head] = 0 // let GC reclaim references if int8 ever carries them
	d.head = (d.head + 1) & mask
	d.size--
	return v, true
}

// RemoveLast removes and returns the back element. The bool is false if empty. O(1).
func (d *Int8) RemoveLast() (int8, bool) {
	if d.size == 0 {
		return 0, false
	}
	mask := len(d.items) - 1
	d.size--
	idx := (d.head + d.size) & mask
	v := d.items[idx]
	d.items[idx] = 0
	return v, true
}

// PeekFirst returns the front element without removing it. The bool is false if empty.
func (d *Int8) PeekFirst() (int8, bool) {
	if d.size == 0 {
		return 0, false
	}
	return d.items[d.head], true
}

// PeekLast returns the back element without removing it. The bool is false if empty.
func (d *Int8) PeekLast() (int8, bool) {
	if d.size == 0 {
		return 0, false
	}
	mask := len(d.items) - 1
	return d.items[(d.head+d.size-1)&mask], true
}

// Len returns the number of elements in the deque. Use d.Len() == 0 to test
// for emptiness.
func (d *Int8) Len() int { return d.size }

// Clear removes all elements. The backing buffer is retained.
func (d *Int8) Clear() {
	// Wipe slots so retained references are released. Cheap for value types.
	mask := len(d.items) - 1
	for i := 0; i < d.size; i++ {
		d.items[(d.head+i)&mask] = 0
	}
	d.head = 0
	d.size = 0
}

// Contains returns true if the deque contains the given value.
func (d *Int8) Contains(value int8) bool {
	mask := len(d.items) - 1
	for i := 0; i < d.size; i++ {
		v := d.items[(d.head+i)&mask]
		if v == value {
			return true
		}
	}
	return false
}

// ForEach applies the function to each element from front to back.
func (d *Int8) ForEach(f func(int8)) {
	mask := len(d.items) - 1
	for i := 0; i < d.size; i++ {
		f(d.items[(d.head+i)&mask])
	}
}

// at returns the logical i-th element (0 = front), mapping through the ring.
// The caller must ensure 0 <= i < d.size (so len(d.items) > 0 and the mask is
// valid).
func (d *Int8) at(i int) int8 {
	return d.items[(d.head+i)&(len(d.items)-1)]
}

// All returns an iter.Seq over the elements in logical front-to-back order,
// regardless of where head sits in the ring.
func (d *Int8) All() iter.Seq[int8] {
	return func(yield func(int8) bool) {
		for i := 0; i < d.size; i++ {
			if !yield(d.at(i)) {
				return
			}
		}
	}
}

// Segments cuts the deque into up to n balanced, contiguous, non-overlapping
// views over the LOGICAL front-to-back order (k = min(n, Len), or 1 when empty)
// whose concatenation reproduces All in order, so a *Int8 satisfies
// par.Segmenter[int8] and feeds par.From directly. Each view maps its
// logical index range through the ring on the fly — the physical wrap is
// invisible. The views are live over the deque: mutating it while a view is
// consumed is undefined behavior.
func (d *Int8) Segments(n int) []iter.Seq[int8] {
	return segment.SplitIndex(d.size, n, d.at)
}

// AnySatisfy returns true if any element satisfies the predicate.
func (d *Int8) AnySatisfy(predicate func(int8) bool) bool {
	mask := len(d.items) - 1
	for i := 0; i < d.size; i++ {
		if predicate(d.items[(d.head+i)&mask]) {
			return true
		}
	}
	return false
}

// AllSatisfy returns true if every element satisfies the predicate.
func (d *Int8) AllSatisfy(predicate func(int8) bool) bool {
	mask := len(d.items) - 1
	for i := 0; i < d.size; i++ {
		if !predicate(d.items[(d.head+i)&mask]) {
			return false
		}
	}
	return true
}

// ToSlice returns a copy of the elements in front-to-back order.
func (d *Int8) ToSlice() []int8 {
	out := make([]int8, d.size)
	if d.size == 0 {
		return out
	}
	cap := len(d.items)
	tail := cap - d.head
	if d.size <= tail {
		copy(out, d.items[d.head:d.head+d.size])
	} else {
		n := copy(out, d.items[d.head:])
		copy(out[n:], d.items[:d.size-n])
	}
	return out
}

// Equals returns true if the other deque has the same elements in the same order.
func (d *Int8) Equals(other *Int8) bool {
	if d.size != other.size {
		return false
	}
	dMask := len(d.items) - 1
	oMask := len(other.items) - 1
	for i := 0; i < d.size; i++ {
		a := d.items[(d.head+i)&dMask]
		b := other.items[(other.head+i)&oMask]
		if !(a == b) {
			return false
		}
	}
	return true
}

// String returns a string representation in front-to-back order.
func (d *Int8) String() string {
	if d.size == 0 {
		return "[]"
	}
	var sb strings.Builder
	sb.WriteString("[")
	mask := len(d.items) - 1
	for i := 0; i < d.size; i++ {
		if i > 0 {
			sb.WriteString(", ")
		}
		fmt.Fprintf(&sb, "%v", d.items[(d.head+i)&mask])
	}
	sb.WriteString("]")
	return sb.String()
}
