// Code generated by internal/codegen; DO NOT EDIT.

package multimap

import (
	"fmt"
	"strings"

	"github.com/mapdb/mapdb-golang/pump"
)

// CharInt32Set is a set multimap from uint16 keys to int32 values.
// Each key maps to a set of unique values (duplicates on Put are silently dropped).
type CharInt32Set struct {
	data map[uint16][]int32
	size int
}

// NewCharInt32Set creates a new empty CharInt32Set.
func NewCharInt32Set() *CharInt32Set {
	return &CharInt32Set{
		data: make(map[uint16][]int32),
		size: 0,
	}
}

// CharInt32SetBulkLoad builds a CharInt32Set from keys/values in a single
// pass, presizing the backing map for the input. keys[i] and values[i] form one
// pair (a length mismatch panics). The input need not be sorted; per-key value
// duplicates are dropped exactly as repeated Put. Duplicate keys are the normal
// grouping case, so the duplicate policy does not apply.
func CharInt32SetBulkLoad(keys []uint16, values []int32) *CharInt32Set {
	if len(keys) != len(values) {
		panic("mapdb: CharInt32SetBulkLoad: len(keys) != len(values)")
	}
	m := &CharInt32Set{
		data: make(map[uint16][]int32, len(keys)),
	}
	for i := range keys {
		m.Put(keys[i], values[i])
	}
	return m
}

// NewCharInt32SetFromSortedKeyValues builds a CharInt32Set from input sorted
// by ascending key and, within each key, ascending value. It validates key
// monotonicity in one pass and dedupes adjacent equal values per key (the sorted
// equivalent of the linear-scan dedupe Put performs). keys[i] and values[i] form
// one pair (a length mismatch panics). Out-of-order keys return
// pump.ErrNotSorted. The result is observably identical to the same pairs
// inserted with Put, provided values within a key are sorted (so equal values are
// adjacent); if they are not, use CharInt32SetBulkLoad instead.
func NewCharInt32SetFromSortedKeyValues(keys []uint16, values []int32) (*CharInt32Set, error) {
	if len(keys) != len(values) {
		panic("mapdb: NewCharInt32SetFromSortedKeyValues: len(keys) != len(values)")
	}
	m := &CharInt32Set{
		data: make(map[uint16][]int32),
	}
	i := 0
	for i < len(keys) {
		key := keys[i]
		if i > 0 && cmpKeyChar(key, keys[i-1]) <= 0 {
			return nil, pump.ErrNotSorted
		}
		j := i
		run := []int32{}
		for j < len(keys) && cmpKeyChar(keys[j], key) == 0 {
			v := values[j]
			if len(run) == 0 || !(run[len(run)-1] == v) {
				run = append(run, v)
			}
			j++
		}
		m.data[key] = run
		m.size += len(run)
		i = j
	}
	return m, nil
}

// Put adds a value to the set for the given key. Idempotent: a duplicate
// value for the same key is silently dropped.
func (m *CharInt32Set) Put(key uint16, value int32) {
	if m.data == nil {
		m.data = make(map[uint16][]int32)
	}
	for _, existing := range m.data[key] {
		if existing == value {
			return
		}
	}
	m.data[key] = append(m.data[key], value)
	m.size++
}

// Get returns a copy of the values for the given key. Returns nil if the key is absent.
func (m *CharInt32Set) Get(key uint16) []int32 {
	return m.GetAll(key)
}

// GetAll returns a copy of the values for the given key.
func (m *CharInt32Set) GetAll(key uint16) []int32 {
	vals := m.data[key]
	if vals == nil {
		return nil
	}
	result := make([]int32, len(vals))
	copy(result, vals)
	return result
}

// RemoveAll removes all values for the given key and returns them.
func (m *CharInt32Set) RemoveAll(key uint16) []int32 {
	vals, ok := m.data[key]
	if !ok {
		return nil
	}
	delete(m.data, key)
	m.size -= len(vals)
	return vals
}

// ContainsKey returns true if the multimap contains the given key.
func (m *CharInt32Set) ContainsKey(key uint16) bool {
	_, ok := m.data[key]
	return ok
}

// ContainsKeyValue returns true if the multimap contains the given key-value pair.
func (m *CharInt32Set) ContainsKeyValue(key uint16, value int32) bool {
	vals, ok := m.data[key]
	if !ok {
		return false
	}
	for _, v := range vals {
		if v == value {
			return true
		}
	}
	return false
}

// KeysCount returns the number of distinct keys.
func (m *CharInt32Set) KeysCount() int {
	return len(m.data)
}

// Len returns the number of elements. Use m.Len() == 0 to test for emptiness.
func (m *CharInt32Set) Len() int {
	return m.size
}

// Clear removes all entries from the multimap.
func (m *CharInt32Set) Clear() {
	m.data = make(map[uint16][]int32)
	m.size = 0
}

// ForEach calls the given function for each key-value pair.
func (m *CharInt32Set) ForEach(f func(uint16, int32)) {
	for key, vals := range m.data {
		for _, val := range vals {
			f(key, val)
		}
	}
}

// ForEachKeyValues calls the given function for each key with a copy of its values.
func (m *CharInt32Set) ForEachKeyValues(f func(uint16, []int32)) {
	for key, vals := range m.data {
		copied := make([]int32, len(vals))
		copy(copied, vals)
		f(key, copied)
	}
}

// Keys returns a slice of all distinct keys.
func (m *CharInt32Set) Keys() []uint16 {
	result := make([]uint16, 0, len(m.data))
	for key := range m.data {
		result = append(result, key)
	}
	return result
}

// Values returns a slice of all values across all keys.
func (m *CharInt32Set) Values() []int32 {
	result := make([]int32, 0, m.size)
	for _, vals := range m.data {
		result = append(result, vals...)
	}
	return result
}

// Select returns a new multimap containing only key-value pairs that satisfy the predicate.
func (m *CharInt32Set) Select(predicate func(uint16, int32) bool) *CharInt32Set {
	result := NewCharInt32Set()
	for key, vals := range m.data {
		for _, val := range vals {
			if predicate(key, val) {
				result.Put(key, val)
			}
		}
	}
	return result
}

// Reject returns a new multimap containing only key-value pairs that do not satisfy the predicate.
func (m *CharInt32Set) Reject(predicate func(uint16, int32) bool) *CharInt32Set {
	result := NewCharInt32Set()
	for key, vals := range m.data {
		for _, val := range vals {
			if !predicate(key, val) {
				result.Put(key, val)
			}
		}
	}
	return result
}

// String returns a string representation of the multimap.
func (m *CharInt32Set) String() string {
	if m.size == 0 {
		return "{}"
	}
	var sb strings.Builder
	sb.WriteString("{")
	first := true
	for key, vals := range m.data {
		if !first {
			sb.WriteString(", ")
		}
		fmt.Fprintf(&sb, "%v=[", key)
		for i, val := range vals {
			if i > 0 {
				sb.WriteString(", ")
			}
			fmt.Fprintf(&sb, "%v", val)
		}
		sb.WriteString("]")
		first = false
	}
	sb.WriteString("}")
	return sb.String()
}

// Equals returns true if the other multimap has the same key-value pairs in the same order per key.
func (m *CharInt32Set) Equals(other *CharInt32Set) bool {
	if m.size != other.size {
		return false
	}
	if len(m.data) != len(other.data) {
		return false
	}
	for key, vals := range m.data {
		otherVals, ok := other.data[key]
		if !ok || len(vals) != len(otherVals) {
			return false
		}
		for i, val := range vals {
			if !(val == otherVals[i]) {
				return false
			}
		}
	}
	return true
}

// KeysToSlice returns all distinct keys as a slice.
func (m *CharInt32Set) KeysToSlice() []uint16 {
	return m.Keys()
}

// ValuesToSlice returns all values as a slice.
func (m *CharInt32Set) ValuesToSlice() []int32 {
	return m.Values()
}

// PutReturning adds a key-value pair and returns the multimap (fluent API).
func (m *CharInt32Set) PutReturning(key uint16, value int32) *CharInt32Set {
	m.Put(key, value)
	return m
}

// RemoveKeyReturning removes all values for the key and returns the multimap (fluent API).
func (m *CharInt32Set) RemoveKeyReturning(key uint16) *CharInt32Set {
	m.RemoveAll(key)
	return m
}
