// Code generated by internal/codegen; DO NOT EDIT.

package multimap

import (
	"fmt"
	"math"
	"strings"

	"github.com/mapdb/mapdb-golang/pump"
)

// Float32Int16List is a list multimap from float32 keys to int16 values.
// Each key maps to a slice of values, preserving insertion order per key.
type Float32Int16List struct {
	data map[uint32][]int16
	keys map[uint32]float32
	size int
}

// NewFloat32Int16List creates a new empty Float32Int16List.
func NewFloat32Int16List() *Float32Int16List {
	return &Float32Int16List{
		data: make(map[uint32][]int16),
		keys: make(map[uint32]float32),
		size: 0,
	}
}

// Float32Int16ListBulkLoad builds a Float32Int16List from keys/values in a single
// pass, presizing the backing map for the input. keys[i] and values[i] form one
// pair (a length mismatch panics). The input need not be sorted; values are
// appended in input order, exactly as repeated Put. Duplicate keys are the normal
// grouping case and the duplicate policy does not apply (a list multimap keeps
// every value).
func Float32Int16ListBulkLoad(keys []float32, values []int16) *Float32Int16List {
	if len(keys) != len(values) {
		panic("mapdb: Float32Int16ListBulkLoad: len(keys) != len(values)")
	}
	m := &Float32Int16List{
		data: make(map[uint32][]int16, len(keys)),
		keys: make(map[uint32]float32, len(keys)),
	}
	for i := range keys {
		m.Put(keys[i], values[i])
	}
	return m
}

// NewFloat32Int16ListFromSortedKeys builds a Float32Int16List from input grouped
// by ascending key: all values for a key are contiguous, and keys appear in
// ascending order (the IEEE-754 total order for float keys). It validates the key
// monotonicity in one pass and assigns each key's value slice directly, preserving
// value order within a key run. keys[i] and values[i] form one pair (a length
// mismatch panics). Out-of-order or interleaved keys return pump.ErrNotSorted.
// The result is observably identical to the same pairs inserted with Put.
func NewFloat32Int16ListFromSortedKeys(keys []float32, values []int16) (*Float32Int16List, error) {
	if len(keys) != len(values) {
		panic("mapdb: NewFloat32Int16ListFromSortedKeys: len(keys) != len(values)")
	}
	m := &Float32Int16List{
		data: make(map[uint32][]int16),
		keys: make(map[uint32]float32),
	}
	i := 0
	for i < len(keys) {
		key := keys[i]
		if i > 0 && cmpKeyFloat32(key, keys[i-1]) <= 0 {
			return nil, pump.ErrNotSorted
		}
		j := i
		run := []int16{}
		for j < len(keys) && cmpKeyFloat32(keys[j], key) == 0 {
			run = append(run, values[j])
			j++
		}
		kb := math.Float32bits(key)
		m.data[kb] = run
		m.keys[kb] = key
		m.size += len(run)
		i = j
	}
	return m, nil
}

// NewFloat32Int16ListFromSortedKeyValues builds a Float32Int16List from input
// sorted by ascending key and, within each key, ascending value. It validates
// both key monotonicity and per-key value monotonicity (using the value type's
// own comparator — the IEEE-754 total order for float values) in one pass.
// Unlike set multimaps, list multimaps preserve equal adjacent values exactly.
// keys[i] and values[i] form one pair (a length mismatch panics).
// Out-of-order keys, or values that descend within a key run, return
// pump.ErrNotSorted before any partial collection is built. If your values are
// not sorted within each key, use Float32Int16ListBulkLoad instead.
func NewFloat32Int16ListFromSortedKeyValues(keys []float32, values []int16) (*Float32Int16List, error) {
	if len(keys) != len(values) {
		panic("mapdb: NewFloat32Int16ListFromSortedKeyValues: len(keys) != len(values)")
	}
	m := &Float32Int16List{
		data: make(map[uint32][]int16),
		keys: make(map[uint32]float32),
	}
	i := 0
	for i < len(keys) {
		key := keys[i]
		if i > 0 && cmpKeyFloat32(key, keys[i-1]) <= 0 {
			return nil, pump.ErrNotSorted
		}
		j := i
		run := []int16{}
		for j < len(keys) && cmpKeyFloat32(keys[j], key) == 0 {
			v := values[j]
			if len(run) > 0 && cmpKeyInt16(run[len(run)-1], v) > 0 {
				return nil, pump.ErrNotSorted // value descends within key run
			}
			run = append(run, v)
			j++
		}
		kb := math.Float32bits(key)
		m.data[kb] = run
		m.keys[kb] = key
		m.size += len(run)
		i = j
	}
	return m, nil
}

// Put adds a value to the list for the given key.
func (m *Float32Int16List) Put(key float32, value int16) {
	if m.data == nil {
		m.data = make(map[uint32][]int16)
		m.keys = make(map[uint32]float32)
	}
	kb := math.Float32bits(key)
	m.data[kb] = append(m.data[kb], value)
	m.keys[kb] = key
	m.size++
}

// Get returns a copy of the values for the given key. Returns nil if the key is absent.
func (m *Float32Int16List) Get(key float32) []int16 {
	return m.GetAll(key)
}

// GetAll returns a copy of the values for the given key.
func (m *Float32Int16List) GetAll(key float32) []int16 {
	vals := m.data[math.Float32bits(key)]
	if vals == nil {
		return nil
	}
	result := make([]int16, len(vals))
	copy(result, vals)
	return result
}

// RemoveAll removes all values for the given key and returns them.
func (m *Float32Int16List) RemoveAll(key float32) []int16 {
	kb := math.Float32bits(key)
	vals, ok := m.data[kb]
	if !ok {
		return nil
	}
	delete(m.data, kb)
	delete(m.keys, kb)
	m.size -= len(vals)
	return vals
}

// ContainsKey returns true if the multimap contains the given key.
func (m *Float32Int16List) ContainsKey(key float32) bool {
	_, ok := m.data[math.Float32bits(key)]
	return ok
}

// ContainsKeyValue returns true if the multimap contains the given key-value pair.
func (m *Float32Int16List) ContainsKeyValue(key float32, value int16) bool {
	vals, ok := m.data[math.Float32bits(key)]
	if !ok {
		return false
	}
	for _, v := range vals {
		if v == value {
			return true
		}
	}
	return false
}

// KeysCount returns the number of distinct keys.
func (m *Float32Int16List) KeysCount() int {
	return len(m.data)
}

// Len returns the number of elements. Use m.Len() == 0 to test for emptiness.
func (m *Float32Int16List) Len() int {
	return m.size
}

// Clear removes all entries from the multimap.
func (m *Float32Int16List) Clear() {
	m.data = make(map[uint32][]int16)
	m.keys = make(map[uint32]float32)
	m.size = 0
}

// ForEach calls the given function for each key-value pair.
func (m *Float32Int16List) ForEach(f func(float32, int16)) {
	for kb, vals := range m.data {
		key := m.keys[kb]
		for _, val := range vals {
			f(key, val)
		}
	}
}

// ForEachKeyValues calls the given function for each key with a copy of its values.
func (m *Float32Int16List) ForEachKeyValues(f func(float32, []int16)) {
	for kb, vals := range m.data {
		key := m.keys[kb]
		copied := make([]int16, len(vals))
		copy(copied, vals)
		f(key, copied)
	}
}

// Keys returns a slice of all distinct keys.
func (m *Float32Int16List) Keys() []float32 {
	result := make([]float32, 0, len(m.data))
	for _, key := range m.keys {
		result = append(result, key)
	}
	return result
}

// Values returns a slice of all values across all keys.
func (m *Float32Int16List) Values() []int16 {
	result := make([]int16, 0, m.size)
	for _, vals := range m.data {
		result = append(result, vals...)
	}
	return result
}

// Select returns a new multimap containing only key-value pairs that satisfy the predicate.
func (m *Float32Int16List) Select(predicate func(float32, int16) bool) *Float32Int16List {
	result := NewFloat32Int16List()
	for kb, vals := range m.data {
		key := m.keys[kb]
		for _, val := range vals {
			if predicate(key, val) {
				result.Put(key, val)
			}
		}
	}
	return result
}

// Reject returns a new multimap containing only key-value pairs that do not satisfy the predicate.
func (m *Float32Int16List) Reject(predicate func(float32, int16) bool) *Float32Int16List {
	result := NewFloat32Int16List()
	for kb, vals := range m.data {
		key := m.keys[kb]
		for _, val := range vals {
			if !predicate(key, val) {
				result.Put(key, val)
			}
		}
	}
	return result
}

// String returns a string representation of the multimap.
func (m *Float32Int16List) String() string {
	if m.size == 0 {
		return "{}"
	}
	var sb strings.Builder
	sb.WriteString("{")
	first := true
	for kb, vals := range m.data {
		key := m.keys[kb]
		if !first {
			sb.WriteString(", ")
		}
		fmt.Fprintf(&sb, "%v=[", key)
		for i, val := range vals {
			if i > 0 {
				sb.WriteString(", ")
			}
			fmt.Fprintf(&sb, "%v", val)
		}
		sb.WriteString("]")
		first = false
	}
	sb.WriteString("}")
	return sb.String()
}

// Equals returns true if the other multimap has the same key-value pairs in the same order per key.
func (m *Float32Int16List) Equals(other *Float32Int16List) bool {
	if m.size != other.size {
		return false
	}
	if len(m.data) != len(other.data) {
		return false
	}
	for kb, vals := range m.data {
		otherVals, ok := other.data[kb]
		if !ok || len(vals) != len(otherVals) {
			return false
		}
		for i, val := range vals {
			if !(val == otherVals[i]) {
				return false
			}
		}
	}
	return true
}

// KeysToSlice returns all distinct keys as a slice.
func (m *Float32Int16List) KeysToSlice() []float32 {
	return m.Keys()
}

// ValuesToSlice returns all values as a slice.
func (m *Float32Int16List) ValuesToSlice() []int16 {
	return m.Values()
}

// PutReturning adds a key-value pair and returns the multimap (fluent API).
func (m *Float32Int16List) PutReturning(key float32, value int16) *Float32Int16List {
	m.Put(key, value)
	return m
}

// RemoveKeyReturning removes all values for the key and returns the multimap (fluent API).
func (m *Float32Int16List) RemoveKeyReturning(key float32) *Float32Int16List {
	m.RemoveAll(key)
	return m
}
