// Code generated by internal/codegen; DO NOT EDIT.

package multimap

// cmpKeyInt32 is the three-way ordering for int32 multimap keys used
// by the FromSorted bulk-load validators.
func cmpKeyInt32(a, b int32) int {
	switch {
	case a < b:
		return -1
	case a > b:
		return 1
	default:
		return 0
	}
}
