// Code generated by internal/codegen; DO NOT EDIT.

package multimap

import (
	"fmt"
	"strings"
)

// Int32Int32SetMultimap is a set multimap from int32 keys to int32 values.
// Each key maps to a set of unique values (duplicates on Put are silently dropped).
type Int32Int32SetMultimap struct {
	data map[int32][]int32
	size int
}

// NewInt32Int32SetMultimap creates a new empty Int32Int32SetMultimap.
func NewInt32Int32SetMultimap() *Int32Int32SetMultimap {
	return &Int32Int32SetMultimap{
		data: make(map[int32][]int32),
		size: 0,
	}
}

// Put adds a value to the set for the given key. Idempotent: a duplicate
// value for the same key is silently dropped.
func (m *Int32Int32SetMultimap) Put(key int32, value int32) {
	if m.data == nil {
		m.data = make(map[int32][]int32)
	}
	for _, existing := range m.data[key] {
		if existing == value {
			return
		}
	}
	m.data[key] = append(m.data[key], value)
	m.size++
}

// Get returns a copy of the values for the given key. Returns nil if the key is absent.
func (m *Int32Int32SetMultimap) Get(key int32) []int32 {
	return m.GetAll(key)
}

// GetAll returns a copy of the values for the given key.
func (m *Int32Int32SetMultimap) GetAll(key int32) []int32 {
	vals := m.data[key]
	if vals == nil {
		return nil
	}
	result := make([]int32, len(vals))
	copy(result, vals)
	return result
}

// RemoveAll removes all values for the given key and returns them.
func (m *Int32Int32SetMultimap) RemoveAll(key int32) []int32 {
	vals, ok := m.data[key]
	if !ok {
		return nil
	}
	delete(m.data, key)
	m.size -= len(vals)
	return vals
}

// ContainsKey returns true if the multimap contains the given key.
func (m *Int32Int32SetMultimap) ContainsKey(key int32) bool {
	_, ok := m.data[key]
	return ok
}

// ContainsKeyValue returns true if the multimap contains the given key-value pair.
func (m *Int32Int32SetMultimap) ContainsKeyValue(key int32, value int32) bool {
	vals, ok := m.data[key]
	if !ok {
		return false
	}
	for _, v := range vals {
		if v == value {
			return true
		}
	}
	return false
}

// KeysCount returns the number of distinct keys.
func (m *Int32Int32SetMultimap) KeysCount() int {
	return len(m.data)
}

// Size returns the total number of values across all keys.
func (m *Int32Int32SetMultimap) Size() int {
	return m.size
}

// Len returns the number of elements. It is an alias for Size, matching
// Go convention (sort.Interface, container/list, bytes.Buffer).
func (m *Int32Int32SetMultimap) Len() int { return m.Size() }

// IsEmpty returns true if the multimap contains no values.
func (m *Int32Int32SetMultimap) IsEmpty() bool {
	return m.size == 0
}

// Clear removes all entries from the multimap.
func (m *Int32Int32SetMultimap) Clear() {
	m.data = make(map[int32][]int32)
	m.size = 0
}

// ForEach calls the given function for each key-value pair.
func (m *Int32Int32SetMultimap) ForEach(f func(int32, int32)) {
	for key, vals := range m.data {
		for _, val := range vals {
			f(key, val)
		}
	}
}

// ForEachKeyValues calls the given function for each key with a copy of its values.
func (m *Int32Int32SetMultimap) ForEachKeyValues(f func(int32, []int32)) {
	for key, vals := range m.data {
		copied := make([]int32, len(vals))
		copy(copied, vals)
		f(key, copied)
	}
}

// Keys returns a slice of all distinct keys.
func (m *Int32Int32SetMultimap) Keys() []int32 {
	result := make([]int32, 0, len(m.data))
	for key := range m.data {
		result = append(result, key)
	}
	return result
}

// Values returns a slice of all values across all keys.
func (m *Int32Int32SetMultimap) Values() []int32 {
	result := make([]int32, 0, m.size)
	for _, vals := range m.data {
		result = append(result, vals...)
	}
	return result
}

// Select returns a new multimap containing only key-value pairs that satisfy the predicate.
func (m *Int32Int32SetMultimap) Select(predicate func(int32, int32) bool) *Int32Int32SetMultimap {
	result := NewInt32Int32SetMultimap()
	for key, vals := range m.data {
		for _, val := range vals {
			if predicate(key, val) {
				result.Put(key, val)
			}
		}
	}
	return result
}

// Reject returns a new multimap containing only key-value pairs that do not satisfy the predicate.
func (m *Int32Int32SetMultimap) Reject(predicate func(int32, int32) bool) *Int32Int32SetMultimap {
	result := NewInt32Int32SetMultimap()
	for key, vals := range m.data {
		for _, val := range vals {
			if !predicate(key, val) {
				result.Put(key, val)
			}
		}
	}
	return result
}

// String returns a string representation of the multimap.
func (m *Int32Int32SetMultimap) String() string {
	if m.size == 0 {
		return "{}"
	}
	var sb strings.Builder
	sb.WriteString("{")
	first := true
	for key, vals := range m.data {
		if !first {
			sb.WriteString(", ")
		}
		fmt.Fprintf(&sb, "%v=[", key)
		for i, val := range vals {
			if i > 0 {
				sb.WriteString(", ")
			}
			fmt.Fprintf(&sb, "%v", val)
		}
		sb.WriteString("]")
		first = false
	}
	sb.WriteString("}")
	return sb.String()
}

// Equals returns true if the other multimap has the same key-value pairs in the same order per key.
func (m *Int32Int32SetMultimap) Equals(other *Int32Int32SetMultimap) bool {
	if m.size != other.size {
		return false
	}
	if len(m.data) != len(other.data) {
		return false
	}
	for key, vals := range m.data {
		otherVals, ok := other.data[key]
		if !ok || len(vals) != len(otherVals) {
			return false
		}
		for i, val := range vals {
			if !(val == otherVals[i]) {
				return false
			}
		}
	}
	return true
}

// KeysToSlice returns all distinct keys as a slice.
func (m *Int32Int32SetMultimap) KeysToSlice() []int32 {
	return m.Keys()
}

// ValuesToSlice returns all values as a slice.
func (m *Int32Int32SetMultimap) ValuesToSlice() []int32 {
	return m.Values()
}

// WithKeyValue adds a key-value pair and returns the multimap (fluent API).
func (m *Int32Int32SetMultimap) WithKeyValue(key int32, value int32) *Int32Int32SetMultimap {
	m.Put(key, value)
	return m
}

// WithoutKey removes all values for the key and returns the multimap (fluent API).
func (m *Int32Int32SetMultimap) WithoutKey(key int32) *Int32Int32SetMultimap {
	m.RemoveAll(key)
	return m
}
