// Code generated by internal/codegen; DO NOT EDIT.

package multimap

import (
	"fmt"
	"strings"
)

// Int64Int8ListMultimap is a list multimap from int64 keys to int8 values.
// Each key maps to a slice of values, preserving insertion order per key.
type Int64Int8ListMultimap struct {
	data map[int64][]int8
	size int
}

// NewInt64Int8ListMultimap creates a new empty Int64Int8ListMultimap.
func NewInt64Int8ListMultimap() *Int64Int8ListMultimap {
	return &Int64Int8ListMultimap{
		data: make(map[int64][]int8),
		size: 0,
	}
}

// Put adds a value to the list for the given key.
func (m *Int64Int8ListMultimap) Put(key int64, value int8) {
	if m.data == nil {
		m.data = make(map[int64][]int8)
	}
	m.data[key] = append(m.data[key], value)
	m.size++
}

// Get returns a copy of the values for the given key. Returns nil if the key is absent.
func (m *Int64Int8ListMultimap) Get(key int64) []int8 {
	return m.GetAll(key)
}

// GetAll returns a copy of the values for the given key.
func (m *Int64Int8ListMultimap) GetAll(key int64) []int8 {
	vals := m.data[key]
	if vals == nil {
		return nil
	}
	result := make([]int8, len(vals))
	copy(result, vals)
	return result
}

// RemoveAll removes all values for the given key and returns them.
func (m *Int64Int8ListMultimap) RemoveAll(key int64) []int8 {
	vals, ok := m.data[key]
	if !ok {
		return nil
	}
	delete(m.data, key)
	m.size -= len(vals)
	return vals
}

// ContainsKey returns true if the multimap contains the given key.
func (m *Int64Int8ListMultimap) ContainsKey(key int64) bool {
	_, ok := m.data[key]
	return ok
}

// ContainsKeyValue returns true if the multimap contains the given key-value pair.
func (m *Int64Int8ListMultimap) ContainsKeyValue(key int64, value int8) bool {
	vals, ok := m.data[key]
	if !ok {
		return false
	}
	for _, v := range vals {
		if v == value {
			return true
		}
	}
	return false
}

// KeysCount returns the number of distinct keys.
func (m *Int64Int8ListMultimap) KeysCount() int {
	return len(m.data)
}

// Size returns the total number of values across all keys.
func (m *Int64Int8ListMultimap) Size() int {
	return m.size
}

// Len returns the number of elements. It is an alias for Size, matching
// Go convention (sort.Interface, container/list, bytes.Buffer).
func (m *Int64Int8ListMultimap) Len() int { return m.Size() }

// IsEmpty returns true if the multimap contains no values.
func (m *Int64Int8ListMultimap) IsEmpty() bool {
	return m.size == 0
}

// Clear removes all entries from the multimap.
func (m *Int64Int8ListMultimap) Clear() {
	m.data = make(map[int64][]int8)
	m.size = 0
}

// ForEach calls the given function for each key-value pair.
func (m *Int64Int8ListMultimap) ForEach(f func(int64, int8)) {
	for key, vals := range m.data {
		for _, val := range vals {
			f(key, val)
		}
	}
}

// ForEachKeyValues calls the given function for each key with a copy of its values.
func (m *Int64Int8ListMultimap) ForEachKeyValues(f func(int64, []int8)) {
	for key, vals := range m.data {
		copied := make([]int8, len(vals))
		copy(copied, vals)
		f(key, copied)
	}
}

// Keys returns a slice of all distinct keys.
func (m *Int64Int8ListMultimap) Keys() []int64 {
	result := make([]int64, 0, len(m.data))
	for key := range m.data {
		result = append(result, key)
	}
	return result
}

// Values returns a slice of all values across all keys.
func (m *Int64Int8ListMultimap) Values() []int8 {
	result := make([]int8, 0, m.size)
	for _, vals := range m.data {
		result = append(result, vals...)
	}
	return result
}

// Select returns a new multimap containing only key-value pairs that satisfy the predicate.
func (m *Int64Int8ListMultimap) Select(predicate func(int64, int8) bool) *Int64Int8ListMultimap {
	result := NewInt64Int8ListMultimap()
	for key, vals := range m.data {
		for _, val := range vals {
			if predicate(key, val) {
				result.Put(key, val)
			}
		}
	}
	return result
}

// Reject returns a new multimap containing only key-value pairs that do not satisfy the predicate.
func (m *Int64Int8ListMultimap) Reject(predicate func(int64, int8) bool) *Int64Int8ListMultimap {
	result := NewInt64Int8ListMultimap()
	for key, vals := range m.data {
		for _, val := range vals {
			if !predicate(key, val) {
				result.Put(key, val)
			}
		}
	}
	return result
}

// String returns a string representation of the multimap.
func (m *Int64Int8ListMultimap) String() string {
	if m.size == 0 {
		return "{}"
	}
	var sb strings.Builder
	sb.WriteString("{")
	first := true
	for key, vals := range m.data {
		if !first {
			sb.WriteString(", ")
		}
		fmt.Fprintf(&sb, "%v=[", key)
		for i, val := range vals {
			if i > 0 {
				sb.WriteString(", ")
			}
			fmt.Fprintf(&sb, "%v", val)
		}
		sb.WriteString("]")
		first = false
	}
	sb.WriteString("}")
	return sb.String()
}

// Equals returns true if the other multimap has the same key-value pairs in the same order per key.
func (m *Int64Int8ListMultimap) Equals(other *Int64Int8ListMultimap) bool {
	if m.size != other.size {
		return false
	}
	if len(m.data) != len(other.data) {
		return false
	}
	for key, vals := range m.data {
		otherVals, ok := other.data[key]
		if !ok || len(vals) != len(otherVals) {
			return false
		}
		for i, val := range vals {
			if !(val == otherVals[i]) {
				return false
			}
		}
	}
	return true
}

// KeysToSlice returns all distinct keys as a slice.
func (m *Int64Int8ListMultimap) KeysToSlice() []int64 {
	return m.Keys()
}

// ValuesToSlice returns all values as a slice.
func (m *Int64Int8ListMultimap) ValuesToSlice() []int8 {
	return m.Values()
}

// WithKeyValue adds a key-value pair and returns the multimap (fluent API).
func (m *Int64Int8ListMultimap) WithKeyValue(key int64, value int8) *Int64Int8ListMultimap {
	m.Put(key, value)
	return m
}

// WithoutKey removes all values for the key and returns the multimap (fluent API).
func (m *Int64Int8ListMultimap) WithoutKey(key int64) *Int64Int8ListMultimap {
	m.RemoveAll(key)
	return m
}
