// Code generated by internal/codegen; DO NOT EDIT.

package multimap

import (
	"fmt"
	"math"
	"strings"

	"github.com/mapdb/mapdb-golang/pump"
)

// Int8Float32List is a list multimap from int8 keys to float32 values.
// Each key maps to a slice of values, preserving insertion order per key.
type Int8Float32List struct {
	data map[int8][]float32
	size int
}

// NewInt8Float32List creates a new empty Int8Float32List.
func NewInt8Float32List() *Int8Float32List {
	return &Int8Float32List{
		data: make(map[int8][]float32),
		size: 0,
	}
}

// Int8Float32ListBulkLoad builds a Int8Float32List from keys/values in a single
// pass, presizing the backing map for the input. keys[i] and values[i] form one
// pair (a length mismatch panics). The input need not be sorted; values are
// appended in input order, exactly as repeated Put. Duplicate keys are the normal
// grouping case and the duplicate policy does not apply (a list multimap keeps
// every value).
func Int8Float32ListBulkLoad(keys []int8, values []float32) *Int8Float32List {
	if len(keys) != len(values) {
		panic("mapdb: Int8Float32ListBulkLoad: len(keys) != len(values)")
	}
	m := &Int8Float32List{
		data: make(map[int8][]float32, len(keys)),
	}
	for i := range keys {
		m.Put(keys[i], values[i])
	}
	return m
}

// NewInt8Float32ListFromSortedKeys builds a Int8Float32List from input grouped
// by ascending key: all values for a key are contiguous, and keys appear in
// ascending order (the IEEE-754 total order for float keys). It validates the key
// monotonicity in one pass and assigns each key's value slice directly, preserving
// value order within a key run. keys[i] and values[i] form one pair (a length
// mismatch panics). Out-of-order or interleaved keys return pump.ErrNotSorted.
// The result is observably identical to the same pairs inserted with Put.
func NewInt8Float32ListFromSortedKeys(keys []int8, values []float32) (*Int8Float32List, error) {
	if len(keys) != len(values) {
		panic("mapdb: NewInt8Float32ListFromSortedKeys: len(keys) != len(values)")
	}
	m := &Int8Float32List{
		data: make(map[int8][]float32),
	}
	i := 0
	for i < len(keys) {
		key := keys[i]
		if i > 0 && cmpKeyInt8(key, keys[i-1]) <= 0 {
			return nil, pump.ErrNotSorted
		}
		j := i
		run := []float32{}
		for j < len(keys) && cmpKeyInt8(keys[j], key) == 0 {
			run = append(run, values[j])
			j++
		}
		m.data[key] = run
		m.size += len(run)
		i = j
	}
	return m, nil
}

// NewInt8Float32ListFromSortedKeyValues builds a Int8Float32List from input
// sorted by ascending key and, within each key, ascending value. It validates
// both key monotonicity and per-key value monotonicity (using the value type's
// own comparator — the IEEE-754 total order for float values) in one pass.
// Unlike set multimaps, list multimaps preserve equal adjacent values exactly.
// keys[i] and values[i] form one pair (a length mismatch panics).
// Out-of-order keys, or values that descend within a key run, return
// pump.ErrNotSorted before any partial collection is built. If your values are
// not sorted within each key, use Int8Float32ListBulkLoad instead.
func NewInt8Float32ListFromSortedKeyValues(keys []int8, values []float32) (*Int8Float32List, error) {
	if len(keys) != len(values) {
		panic("mapdb: NewInt8Float32ListFromSortedKeyValues: len(keys) != len(values)")
	}
	m := &Int8Float32List{
		data: make(map[int8][]float32),
	}
	i := 0
	for i < len(keys) {
		key := keys[i]
		if i > 0 && cmpKeyInt8(key, keys[i-1]) <= 0 {
			return nil, pump.ErrNotSorted
		}
		j := i
		run := []float32{}
		for j < len(keys) && cmpKeyInt8(keys[j], key) == 0 {
			v := values[j]
			if len(run) > 0 && cmpKeyFloat32(run[len(run)-1], v) > 0 {
				return nil, pump.ErrNotSorted // value descends within key run
			}
			run = append(run, v)
			j++
		}
		m.data[key] = run
		m.size += len(run)
		i = j
	}
	return m, nil
}

// Put adds a value to the list for the given key.
func (m *Int8Float32List) Put(key int8, value float32) {
	if m.data == nil {
		m.data = make(map[int8][]float32)
	}
	m.data[key] = append(m.data[key], value)
	m.size++
}

// Get returns a copy of the values for the given key. Returns nil if the key is absent.
func (m *Int8Float32List) Get(key int8) []float32 {
	return m.GetAll(key)
}

// GetAll returns a copy of the values for the given key.
func (m *Int8Float32List) GetAll(key int8) []float32 {
	vals := m.data[key]
	if vals == nil {
		return nil
	}
	result := make([]float32, len(vals))
	copy(result, vals)
	return result
}

// RemoveAll removes all values for the given key and returns them.
func (m *Int8Float32List) RemoveAll(key int8) []float32 {
	vals, ok := m.data[key]
	if !ok {
		return nil
	}
	delete(m.data, key)
	m.size -= len(vals)
	return vals
}

// ContainsKey returns true if the multimap contains the given key.
func (m *Int8Float32List) ContainsKey(key int8) bool {
	_, ok := m.data[key]
	return ok
}

// ContainsKeyValue returns true if the multimap contains the given key-value pair.
func (m *Int8Float32List) ContainsKeyValue(key int8, value float32) bool {
	vals, ok := m.data[key]
	if !ok {
		return false
	}
	for _, v := range vals {
		if math.Float32bits(v) == math.Float32bits(value) {
			return true
		}
	}
	return false
}

// KeysCount returns the number of distinct keys.
func (m *Int8Float32List) KeysCount() int {
	return len(m.data)
}

// Len returns the number of elements. Use m.Len() == 0 to test for emptiness.
func (m *Int8Float32List) Len() int {
	return m.size
}

// Clear removes all entries from the multimap.
func (m *Int8Float32List) Clear() {
	m.data = make(map[int8][]float32)
	m.size = 0
}

// ForEach calls the given function for each key-value pair.
func (m *Int8Float32List) ForEach(f func(int8, float32)) {
	for key, vals := range m.data {
		for _, val := range vals {
			f(key, val)
		}
	}
}

// ForEachKeyValues calls the given function for each key with a copy of its values.
func (m *Int8Float32List) ForEachKeyValues(f func(int8, []float32)) {
	for key, vals := range m.data {
		copied := make([]float32, len(vals))
		copy(copied, vals)
		f(key, copied)
	}
}

// Keys returns a slice of all distinct keys.
func (m *Int8Float32List) Keys() []int8 {
	result := make([]int8, 0, len(m.data))
	for key := range m.data {
		result = append(result, key)
	}
	return result
}

// Values returns a slice of all values across all keys.
func (m *Int8Float32List) Values() []float32 {
	result := make([]float32, 0, m.size)
	for _, vals := range m.data {
		result = append(result, vals...)
	}
	return result
}

// Select returns a new multimap containing only key-value pairs that satisfy the predicate.
func (m *Int8Float32List) Select(predicate func(int8, float32) bool) *Int8Float32List {
	result := NewInt8Float32List()
	for key, vals := range m.data {
		for _, val := range vals {
			if predicate(key, val) {
				result.Put(key, val)
			}
		}
	}
	return result
}

// Reject returns a new multimap containing only key-value pairs that do not satisfy the predicate.
func (m *Int8Float32List) Reject(predicate func(int8, float32) bool) *Int8Float32List {
	result := NewInt8Float32List()
	for key, vals := range m.data {
		for _, val := range vals {
			if !predicate(key, val) {
				result.Put(key, val)
			}
		}
	}
	return result
}

// String returns a string representation of the multimap.
func (m *Int8Float32List) String() string {
	if m.size == 0 {
		return "{}"
	}
	var sb strings.Builder
	sb.WriteString("{")
	first := true
	for key, vals := range m.data {
		if !first {
			sb.WriteString(", ")
		}
		fmt.Fprintf(&sb, "%v=[", key)
		for i, val := range vals {
			if i > 0 {
				sb.WriteString(", ")
			}
			fmt.Fprintf(&sb, "%v", val)
		}
		sb.WriteString("]")
		first = false
	}
	sb.WriteString("}")
	return sb.String()
}

// Equals returns true if the other multimap has the same key-value pairs in the same order per key.
func (m *Int8Float32List) Equals(other *Int8Float32List) bool {
	if m.size != other.size {
		return false
	}
	if len(m.data) != len(other.data) {
		return false
	}
	for key, vals := range m.data {
		otherVals, ok := other.data[key]
		if !ok || len(vals) != len(otherVals) {
			return false
		}
		for i, val := range vals {
			if !(math.Float32bits(val) == math.Float32bits(otherVals[i])) {
				return false
			}
		}
	}
	return true
}

// KeysToSlice returns all distinct keys as a slice.
func (m *Int8Float32List) KeysToSlice() []int8 {
	return m.Keys()
}

// ValuesToSlice returns all values as a slice.
func (m *Int8Float32List) ValuesToSlice() []float32 {
	return m.Values()
}

// PutReturning adds a key-value pair and returns the multimap (fluent API).
func (m *Int8Float32List) PutReturning(key int8, value float32) *Int8Float32List {
	m.Put(key, value)
	return m
}

// RemoveKeyReturning removes all values for the key and returns the multimap (fluent API).
func (m *Int8Float32List) RemoveKeyReturning(key int8) *Int8Float32List {
	m.RemoveAll(key)
	return m
}
