// Code generated by internal/codegen; DO NOT EDIT.

package multimap

import (
	"fmt"
	"iter"
	"strings"

	"github.com/mapdb/mapdb-golang/pump"
)

// Int8CharList is a list multimap from int8 keys to uint16 values.
// Each key maps to a slice of values, preserving insertion order per key.
type Int8CharList struct {
	data map[int8][]uint16
	size int
}

// NewInt8CharList creates a new empty Int8CharList.
func NewInt8CharList() *Int8CharList {
	return &Int8CharList{
		data: make(map[int8][]uint16),
		size: 0,
	}
}

// Int8CharListBulkLoad builds a Int8CharList from keys/values in a single
// pass, presizing the backing map for the input. keys[i] and values[i] form one
// pair (a length mismatch panics). The input need not be sorted; values are
// appended in input order, exactly as repeated Put. Duplicate keys are the normal
// grouping case and the duplicate policy does not apply (a list multimap keeps
// every value).
func Int8CharListBulkLoad(keys []int8, values []uint16) *Int8CharList {
	if len(keys) != len(values) {
		panic("mapdb: Int8CharListBulkLoad: len(keys) != len(values)")
	}
	m := &Int8CharList{
		data: make(map[int8][]uint16, len(keys)),
	}
	for i := range keys {
		m.Put(keys[i], values[i])
	}
	return m
}

// NewInt8CharListFromSortedKeys builds a Int8CharList from input grouped
// by ascending key: all values for a key are contiguous, and keys appear in
// ascending order (the IEEE-754 total order for float keys). It validates the key
// monotonicity in one pass and assigns each key's value slice directly, preserving
// value order within a key run. keys[i] and values[i] form one pair (a length
// mismatch panics). Out-of-order or interleaved keys return pump.ErrNotSorted.
// The result is observably identical to the same pairs inserted with Put.
func NewInt8CharListFromSortedKeys(keys []int8, values []uint16) (*Int8CharList, error) {
	if len(keys) != len(values) {
		panic("mapdb: NewInt8CharListFromSortedKeys: len(keys) != len(values)")
	}
	m := &Int8CharList{
		data: make(map[int8][]uint16),
	}
	i := 0
	for i < len(keys) {
		key := keys[i]
		if i > 0 && cmpKeyInt8(key, keys[i-1]) <= 0 {
			return nil, pump.ErrNotSorted
		}
		j := i
		run := []uint16{}
		for j < len(keys) && cmpKeyInt8(keys[j], key) == 0 {
			run = append(run, values[j])
			j++
		}
		m.data[key] = run
		m.size += len(run)
		i = j
	}
	return m, nil
}

// NewInt8CharListFromSortedKeyValues builds a Int8CharList from input
// sorted by ascending key and, within each key, ascending value. It validates
// both key monotonicity and per-key value monotonicity (using the value type's
// own comparator — the IEEE-754 total order for float values) in one pass.
// Unlike set multimaps, list multimaps preserve equal adjacent values exactly.
// keys[i] and values[i] form one pair (a length mismatch panics).
// Out-of-order keys, or values that descend within a key run, return
// pump.ErrNotSorted before any partial collection is built. If your values are
// not sorted within each key, use Int8CharListBulkLoad instead.
func NewInt8CharListFromSortedKeyValues(keys []int8, values []uint16) (*Int8CharList, error) {
	if len(keys) != len(values) {
		panic("mapdb: NewInt8CharListFromSortedKeyValues: len(keys) != len(values)")
	}
	m := &Int8CharList{
		data: make(map[int8][]uint16),
	}
	i := 0
	for i < len(keys) {
		key := keys[i]
		if i > 0 && cmpKeyInt8(key, keys[i-1]) <= 0 {
			return nil, pump.ErrNotSorted
		}
		j := i
		run := []uint16{}
		for j < len(keys) && cmpKeyInt8(keys[j], key) == 0 {
			v := values[j]
			if len(run) > 0 && cmpKeyChar(run[len(run)-1], v) > 0 {
				return nil, pump.ErrNotSorted // value descends within key run
			}
			run = append(run, v)
			j++
		}
		m.data[key] = run
		m.size += len(run)
		i = j
	}
	return m, nil
}

// Put adds a value to the list for the given key.
func (m *Int8CharList) Put(key int8, value uint16) {
	if m.data == nil {
		m.data = make(map[int8][]uint16)
	}
	m.data[key] = append(m.data[key], value)
	m.size++
}

// Get returns a copy of the values for the given key. Returns nil if the key is absent.
func (m *Int8CharList) Get(key int8) []uint16 {
	return m.GetAll(key)
}

// GetAll returns a copy of the values for the given key.
func (m *Int8CharList) GetAll(key int8) []uint16 {
	vals := m.data[key]
	if vals == nil {
		return nil
	}
	result := make([]uint16, len(vals))
	copy(result, vals)
	return result
}

// RemoveAll removes all values for the given key and returns them.
func (m *Int8CharList) RemoveAll(key int8) []uint16 {
	vals, ok := m.data[key]
	if !ok {
		return nil
	}
	delete(m.data, key)
	m.size -= len(vals)
	return vals
}

// ContainsKey returns true if the multimap contains the given key.
func (m *Int8CharList) ContainsKey(key int8) bool {
	_, ok := m.data[key]
	return ok
}

// ContainsKeyValue returns true if the multimap contains the given key-value pair.
func (m *Int8CharList) ContainsKeyValue(key int8, value uint16) bool {
	vals, ok := m.data[key]
	if !ok {
		return false
	}
	for _, v := range vals {
		if v == value {
			return true
		}
	}
	return false
}

// KeysCount returns the number of distinct keys.
func (m *Int8CharList) KeysCount() int {
	return len(m.data)
}

// Len returns the number of elements. Use m.Len() == 0 to test for emptiness.
func (m *Int8CharList) Len() int {
	return m.size
}

// Clear removes all entries from the multimap.
func (m *Int8CharList) Clear() {
	m.data = make(map[int8][]uint16)
	m.size = 0
}

// ForEach calls the given function for each key-value pair.
func (m *Int8CharList) ForEach(f func(int8, uint16)) {
	for key, vals := range m.data {
		for _, val := range vals {
			f(key, val)
		}
	}
}

// All returns an iter.Seq2 that yields every key-value pair (law 1). Iteration
// order is unspecified — keys follow Go map order; a key's values keep their
// per-key insertion order. Unlike ForEach it is rangeable and honors an early
// break, and it bridges into the seq/par layers via seq.From2(m.All()).
func (m *Int8CharList) All() iter.Seq2[int8, uint16] {
	return func(yield func(int8, uint16) bool) {
		for key, vals := range m.data {
			for _, val := range vals {
				if !yield(key, val) {
					return
				}
			}
		}
	}
}

// ForEachKeyValues calls the given function for each key with a copy of its values.
func (m *Int8CharList) ForEachKeyValues(f func(int8, []uint16)) {
	for key, vals := range m.data {
		copied := make([]uint16, len(vals))
		copy(copied, vals)
		f(key, copied)
	}
}

// Keys returns a slice of all distinct keys.
func (m *Int8CharList) Keys() []int8 {
	result := make([]int8, 0, len(m.data))
	for key := range m.data {
		result = append(result, key)
	}
	return result
}

// Values returns a slice of all values across all keys.
func (m *Int8CharList) Values() []uint16 {
	result := make([]uint16, 0, m.size)
	for _, vals := range m.data {
		result = append(result, vals...)
	}
	return result
}

// Select returns a new multimap containing only key-value pairs that satisfy the predicate.
func (m *Int8CharList) Select(predicate func(int8, uint16) bool) *Int8CharList {
	result := NewInt8CharList()
	for key, vals := range m.data {
		for _, val := range vals {
			if predicate(key, val) {
				result.Put(key, val)
			}
		}
	}
	return result
}

// Reject returns a new multimap containing only key-value pairs that do not satisfy the predicate.
func (m *Int8CharList) Reject(predicate func(int8, uint16) bool) *Int8CharList {
	result := NewInt8CharList()
	for key, vals := range m.data {
		for _, val := range vals {
			if !predicate(key, val) {
				result.Put(key, val)
			}
		}
	}
	return result
}

// String returns a string representation of the multimap.
func (m *Int8CharList) String() string {
	if m.size == 0 {
		return "{}"
	}
	var sb strings.Builder
	sb.WriteString("{")
	first := true
	for key, vals := range m.data {
		if !first {
			sb.WriteString(", ")
		}
		fmt.Fprintf(&sb, "%v=[", key)
		for i, val := range vals {
			if i > 0 {
				sb.WriteString(", ")
			}
			fmt.Fprintf(&sb, "%v", val)
		}
		sb.WriteString("]")
		first = false
	}
	sb.WriteString("}")
	return sb.String()
}

// Equals returns true if the other multimap has the same key-value pairs in the same order per key.
func (m *Int8CharList) Equals(other *Int8CharList) bool {
	if m.size != other.size {
		return false
	}
	if len(m.data) != len(other.data) {
		return false
	}
	for key, vals := range m.data {
		otherVals, ok := other.data[key]
		if !ok || len(vals) != len(otherVals) {
			return false
		}
		for i, val := range vals {
			if !(val == otherVals[i]) {
				return false
			}
		}
	}
	return true
}

// KeysToSlice returns all distinct keys as a slice.
func (m *Int8CharList) KeysToSlice() []int8 {
	return m.Keys()
}

// ValuesToSlice returns all values as a slice.
func (m *Int8CharList) ValuesToSlice() []uint16 {
	return m.Values()
}

// PutReturning adds a key-value pair and returns the multimap (fluent API).
func (m *Int8CharList) PutReturning(key int8, value uint16) *Int8CharList {
	m.Put(key, value)
	return m
}

// RemoveKeyReturning removes all values for the key and returns the multimap (fluent API).
func (m *Int8CharList) RemoveKeyReturning(key int8) *Int8CharList {
	m.RemoveAll(key)
	return m
}
